import { create } from "@stylexjs/stylex"
import { colors } from "./theme.stylex"

export const className = (properties: { readonly className?: string | undefined }): string => properties.className ?? ""

export const styles = create({
  document: { colorScheme: "light dark", backgroundColor: colors.background, scrollPaddingTop: 48 },
  body: { margin: 0 },
  page: {
    minHeight: "100dvh",
    backgroundColor: colors.background,
    color: colors.foreground,
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    fontSize: 15,
    lineHeight: 1.7,
    WebkitFontSmoothing: "antialiased",
    colorScheme: "light dark",
    "::selection": { backgroundColor: colors.selectionBackground, color: colors.selectionForeground },
  },
  light: { colorScheme: "light" },
  dark: { colorScheme: "dark" },
  link: {
    color: "inherit",
    textDecoration: "none",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "transparent",
  },
  button: {
    font: "inherit",
    color: "inherit",
    padding: 0,
    borderWidth: 0,
    borderStyle: "solid",
    backgroundColor: "transparent",
    cursor: "pointer",
    touchAction: "manipulation",
    WebkitTapHighlightColor: "transparent",
  },
  focus: {
    ":focus-visible": {
      outlineWidth: 2,
      outlineStyle: "solid",
      outlineColor: colors.accent,
      outlineOffset: 3,
      borderRadius: 6,
    },
  },
  focusReset: { ":focus": { outlineWidth: 0, outlineStyle: "none" } },
  skip: {
    position: "fixed",
    top: -80,
    left: 280,
    padding: "8px 16px",
    backgroundColor: colors.panel,
    zIndex: 100,
    borderRadius: 8,
    ":focus": { top: 12 },
  },
  icon: { width: 17, height: 17, display: "block", flexShrink: 0 },
  brand: { display: "flex", alignItems: "center", gap: 10, fontWeight: 580, fontSize: 19, letterSpacing: "-.5px" },
  brandIcon: { display: "block", width: 29, height: 29 },
  sidebar: {
    boxSizing: "border-box",
    position: "fixed",
    inset: "0 auto 0 0",
    width: 264,
    zIndex: 20,
    display: { default: "flex", "@media (max-width: 959px)": "none" },
    flexDirection: "column",
    backgroundColor: colors.background,
    padding: "28px 16px 16px 20px",
    borderRightWidth: 1,
    borderRightStyle: "solid",
    borderRightColor: colors.line,
  },
  sidebarBrand: { margin: "0 10px 23px" },
  searchTrigger: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    textAlign: "left",
    color: colors.muted,
    width: "100%",
    padding: "10px 12px",
    borderRadius: 8,
    fontSize: 13,
    boxSizing: "border-box",
    flexShrink: 0,
    transition: "background-color 120ms, color 120ms",
    ":hover": { backgroundColor: colors.hover, color: colors.foreground },
  },
  shortcut: { marginLeft: "auto", font: "inherit", fontSize: 11, color: colors.faint, whiteSpace: "nowrap" },
  navScroll: {
    overflowY: "auto",
    minHeight: 0,
    marginTop: 23,
    marginRight: -6,
    paddingRight: 6,
    overscrollBehavior: "contain",
    scrollbarWidth: "thin",
    scrollbarColor: `${colors.line} transparent`,
    flex: 1,
  },
  navGroup: { marginBottom: 25 },
  navGroupTitle: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    margin: "0 12px 8px",
    fontSize: 11,
    color: colors.faint,
  },
  navCount: { fontSize: 10, fontVariantNumeric: "tabular-nums" },
  navItems: { position: "relative" },
  navLink: {
    position: "relative",
    display: "flex",
    alignItems: "center",
    padding: "0 12px",
    height: 36,
    boxSizing: "border-box",
    borderRadius: 8,
    fontSize: 13,
    lineHeight: 1.25,
    color: colors.muted,
    transition: "color 100ms",
    ":hover": { color: colors.foreground },
  },
  navActive: { color: colors.foreground, backgroundColor: colors.selected, fontWeight: 530 },
  hoverTrack: (y: number, opacity: number, height: number) => ({
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height,
    transform: `translate3d(0, ${y}px, 0)`,
    opacity,
    borderRadius: 8,
    backgroundColor: colors.hover,
    pointerEvents: "none",
    willChange: "transform, opacity",
  }),
  sidebarFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.line,
    padding: "14px 9px 0",
    marginTop: 12,
    fontSize: 11,
    color: colors.faint,
  },
  themeButton: {
    display: "flex",
    gap: 7,
    alignItems: "center",
    padding: "5px 7px",
    borderRadius: 6,
    fontSize: 11,
    ":hover": { backgroundColor: colors.hover, color: colors.foreground },
  },
  mobileBar: {
    display: { default: "none", "@media (max-width: 959px)": "flex" },
    height: 66,
    alignItems: "center",
    justifyContent: "space-between",
    paddingInline: 22,
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    position: "sticky",
    top: 0,
    zIndex: 20,
    backgroundColor: colors.background,
  },
  mobileActions: { display: "flex", alignItems: "center", gap: 8 },
  iconButton: {
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    color: colors.muted,
    ":hover": { backgroundColor: colors.hover, color: colors.foreground },
  },
  main: {
    marginLeft: { default: 264, "@media (max-width: 959px)": 0 },
    minWidth: 0,
    padding: {
      default: "91px 56px 32px",
      "@media (max-width: 1199px)": "70px 44px 28px",
      "@media (max-width: 599px)": "40px 22px 22px",
    },
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: { default: "minmax(0, 760px) 160px", "@media (max-width: 1279px)": "minmax(0, 760px)" },
    gap: 56,
    maxWidth: 1000,
    marginInline: "auto",
    alignItems: "start",
  },
  homeGrid: { gridTemplateColumns: "minmax(0, 800px)", maxWidth: 800 },
  article: { minWidth: 0, scrollMarginTop: 40 },
  eyebrow: { margin: "0 0 14px", color: colors.faint, fontSize: 12, fontWeight: 450 },
  h1: {
    fontSize: { default: 34, "@media (max-width: 599px)": 29 },
    letterSpacing: "-1.2px",
    fontWeight: 600,
    lineHeight: 1.2,
    margin: 0,
    textWrap: "balance",
  },
  homeTitle: {
    fontSize: { default: 48, "@media (max-width: 599px)": 37 },
    letterSpacing: "-1.8px",
    lineHeight: 1.12,
    maxWidth: 640,
  },
  description: { color: colors.muted, fontSize: 16, maxWidth: 680, lineHeight: 1.75, margin: "18px 0 0" },
  articleHeader: { marginBottom: 43 },
  homeHeader: { marginBottom: 56 },
  ctaRow: { display: "flex", gap: 12, flexWrap: "wrap", marginTop: 25 },
  cta: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 9,
    padding: "8px 16px",
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 480,
    transition: "transform 120ms, opacity 120ms",
    ":active": { transform: "scale(.97)" },
    ":hover": { opacity: 0.85 },
    "@media (prefers-reduced-motion: reduce)": { transition: "none" },
  },
  ctaPrimary: {
    backgroundColor: colors.foreground,
    color: colors.background,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.foreground,
  },
  ctaSecondary: { borderWidth: 1, borderStyle: "solid", borderColor: colors.line, backgroundColor: colors.soft },
  p: { margin: "15px 0", color: colors.muted, lineHeight: 1.85 },
  h2: {
    margin: "49px 0 15px",
    fontSize: 22,
    lineHeight: 1.35,
    letterSpacing: "-.55px",
    fontWeight: 540,
    scrollMarginTop: 95,
  },
  headingLink: { ":hover": { color: colors.accent } },
  inlineCode: {
    fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    fontSize: ".87em",
    backgroundColor: colors.soft,
    borderRadius: 4,
    padding: "2px 4px",
    color: colors.foreground,
    overflowWrap: "anywhere",
  },
  codeFigure: {
    position: "relative",
    margin: "22px 0",
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    backgroundColor: colors.soft,
    overflow: "hidden",
  },
  pre: {
    margin: 0,
    padding: "22px 24px",
    overflowX: "auto",
    tabSize: 2,
    scrollbarWidth: "thin",
    scrollbarColor: `${colors.line} transparent`,
    fontSize: { default: 12.5, "@media (max-width: 599px)": 11.5 },
    lineHeight: 1.9,
  },
  code: {
    fontFamily: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    display: "block",
    width: "max-content",
    minWidth: "100%",
  },
  codeLine: { display: "block", minHeight: "1.9em", paddingRight: 28 },
  token: (light: string, dark: string) => ({ color: `light-dark(${light}, ${dark})` }),
  copyButton: {
    position: "absolute",
    top: 10,
    right: 10,
    zIndex: 1,
    borderRadius: 6,
    padding: 7,
    backgroundColor: colors.soft,
    color: colors.muted,
    opacity: 0.8,
    transition: "opacity 120ms, transform 120ms",
    ":hover": { opacity: 1, color: colors.foreground, backgroundColor: colors.panel },
    ":active": { transform: "scale(.93)" },
  },
  output: {
    margin: "-8px 0 28px",
    padding: "13px 20px",
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: colors.line,
    color: colors.muted,
    fontSize: 12,
    lineHeight: 1.8,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontFamily: '"SFMono-Regular", Consolas, monospace',
  },
  outputLabel: {
    display: "block",
    fontFamily: "Inter, sans-serif",
    color: colors.faint,
    fontSize: 10,
    marginBottom: 5,
  },
  copyStatus: {
    position: "absolute",
    right: 42,
    top: 13,
    fontSize: 11,
    color: colors.muted,
    backgroundColor: colors.soft,
    paddingInline: 5,
  },
  copyError: { padding: "0 20px 12px", color: colors.copyError, fontSize: 12 },
  note: {
    margin: "24px 0",
    padding: "13px 18px",
    borderLeftWidth: 2,
    borderLeftStyle: "solid",
    borderLeftColor: colors.line,
    color: colors.muted,
    fontSize: 13,
  },
  noteTitle: { margin: "0 0 5px", color: colors.foreground, fontWeight: 500 },
  noteText: { margin: 0 },
  list: { paddingLeft: 20, margin: "18px 0", color: colors.muted },
  listItem: { paddingLeft: 4, marginBlock: 7 },
  tableScroll: { overflowX: "auto", marginBlock: 24 },
  table: { borderCollapse: "collapse", width: "100%", fontSize: 13, textAlign: "left" },
  cell: {
    padding: "12px 14px 12px 0",
    verticalAlign: "top",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    color: colors.muted,
    fontWeight: 400,
    minWidth: 150,
  },
  tableHeading: { color: colors.foreground, fontWeight: 500 },
  related: { display: "grid", gap: 8, marginBlock: 25 },
  relatedLink: {
    display: "flex",
    alignItems: "center",
    gap: 18,
    justifyContent: "space-between",
    padding: "15px 18px",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 9,
    fontSize: 13,
    ":hover": { backgroundColor: colors.hover },
  },
  relatedDescription: { display: "block", marginTop: 4, color: colors.muted, fontSize: 12 },
  toc: {
    display: { default: "block", "@media (max-width: 1279px)": "none" },
    position: "sticky",
    top: 60,
    fontSize: 11,
  },
  tocTitle: { color: colors.foreground, margin: "0 0 14px", fontWeight: 500 },
  tocLink: {
    display: "block",
    color: colors.faint,
    paddingBlock: 6,
    lineHeight: 1.5,
    ":hover": { color: colors.foreground },
  },
  pageFooter: {
    marginTop: 58,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.line,
    display: "flex",
    justifyContent: "space-between",
    gap: 20,
  },
  footerLink: { display: "flex", gap: 12, alignItems: "center", fontSize: 13, ":hover": { color: colors.accent } },
  footerLabel: { display: "block", color: colors.faint, fontSize: 10, marginBottom: 3 },
  footerRight: { textAlign: "right", marginLeft: "auto" },
  colophon: {
    display: "flex",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 52,
    paddingTop: 20,
    fontSize: 10,
    color: colors.faint,
  },
  dialog: {
    boxSizing: "border-box",
    position: "fixed",
    inset: 0,
    margin: 0,
    padding: 0,
    width: "100%",
    height: "100%",
    maxWidth: "none",
    maxHeight: "none",
    backgroundColor: "transparent",
    borderWidth: 0,
    borderStyle: "solid",
    color: colors.foreground,
    fontFamily: "inherit",
    overflow: "hidden",
    outlineWidth: 0,
    outlineStyle: "none",
    "::backdrop": { backgroundColor: "transparent" },
  },
  backdrop: (progress: number) => ({
    position: "absolute",
    inset: 0,
    backgroundColor: "rgb(0 0 0 / .5)",
    opacity: progress,
  }),
  searchPanel: (progress: number) => ({
    position: "relative",
    top: { default: "min(16vh, 150px)", "@media (max-width: 599px)": 80 },
    marginInline: "auto",
    width: "calc(100% - 32px)",
    maxWidth: 600,
    maxHeight: "calc(100dvh - 120px)",
    display: "flex",
    flexDirection: "column",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    borderRadius: 14,
    backgroundColor: colors.panel,
    boxShadow: colors.shadow,
    transform: `translate3d(0, ${(1 - progress) * -12}px, 0) scale(${0.97 + 0.03 * progress})`,
    opacity: progress,
    overflow: "hidden",
    willChange: "transform, opacity",
    lineHeight: 1.5,
  }),
  searchInputRow: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    padding: "18px 20px",
    borderBottomWidth: 1,
    borderBottomStyle: "solid",
    borderBottomColor: colors.line,
    color: colors.muted,
  },
  searchInput: {
    borderWidth: 0,
    borderStyle: "solid",
    outlineWidth: 0,
    outlineStyle: "none",
    backgroundColor: "transparent",
    color: colors.foreground,
    font: "inherit",
    fontSize: 15,
    width: "100%",
    minWidth: 0,
    padding: 0,
    "::placeholder": { color: colors.faint },
  },
  searchHint: { margin: "16px 20px 8px", fontSize: 11, color: colors.faint },
  searchList: {
    overflowY: "auto",
    padding: "0 8px 8px",
    minHeight: 80,
    scrollbarWidth: "thin",
    scrollbarColor: `${colors.line} transparent`,
  },
  searchListInner: { position: "relative" },
  searchResult: {
    display: "flex",
    position: "relative",
    alignItems: "center",
    gap: 14,
    padding: "10px 12px",
    height: 64,
    boxSizing: "border-box",
    borderRadius: 8,
    color: colors.foreground,
    fontSize: 13,
  },
  resultText: { minWidth: 0 },
  resultCategory: { display: "block", fontSize: 10, color: colors.faint, marginBottom: 3 },
  resultTitle: { display: "block", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  resultArrow: { color: colors.faint, marginLeft: "auto" },
  searchFooter: {
    borderTopWidth: 1,
    borderTopStyle: "solid",
    borderTopColor: colors.line,
    padding: "11px 18px",
    color: colors.faint,
    fontSize: 10,
    display: "flex",
    gap: 16,
  },
  key: {
    font: "inherit",
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.line,
    padding: "1px 4px",
    borderRadius: 4,
    marginLeft: 4,
  },
  emptySearch: { padding: "32px 20px", color: colors.muted, fontSize: 13, textAlign: "center" },
  drawer: (progress: number) => ({
    position: "relative",
    height: "100%",
    width: "min(300px, calc(100vw - 48px))",
    backgroundColor: colors.background,
    padding: "24px 16px 18px",
    boxSizing: "border-box",
    display: "flex",
    flexDirection: "column",
    transform: `translate3d(${(progress - 1) * 100}%, 0, 0)`,
    boxShadow: colors.shadow,
    willChange: "transform",
  }),
  drawerHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", margin: "0 6px 20px" },
  srOnly: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderWidth: 0,
  },
})
