import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const coreAgentReference = definePage({
  path: "/docs/reference/core-agent",
  title: "Agent and run functions",
  navTitle: "Agent",
  group: "Reference",
  description: "Typed Agent.make input/output, run, stream, start, truthful requirements, RunError, and Resume.",
  content: [
    lead(
      "The Agent namespace defines a typed agent value, process-local run and stream projections, a durable Runtime start, and every option and service a run consumes.",
    ),
    command("Install", "bun add effect@4.0.0-rc.112 generalist"),
    h2("agent-make", "Agent.make"),
    p(
      "An ",
      code("Agent<Tools, R, ..., InputSchema, OutputSchema>"),
      " is a plain value ",
      code("{ name, input, output, instructions?, toolkit, policy, model?, memory?, metadata? }"),
      ", not a service. ",
      code("Agent.make(options)"),
      " fills defaults:",
    ),
    table(
      ["Option", "Type", "Default"],
      [
        [[code("name")], [code("string")], "required"],
        [[code("input")], [code("Schema")], [code("Schema.String")]],
        [[code("output")], [code("Schema")], [code("Schema.String")]],
        [[code("instructions")], [code("string")], "none"],
        [[code("toolkit")], [code("Ai.Toolkit.Toolkit<Tools>")], [code("Ai.Toolkit.empty")]],
        [[code("policy")], [code("Policy.Policy")], [code("Policy.defaultPolicy")]],
        [[code("model")], [code("ModelRegistry.ModelSelection")], "none"],
        [[code("memory")], [code("Memory.Key")], "none"],
        [[code("metadata")], [code("Readonly<Record<string, unknown>>")], "none"],
      ],
    ),
    p(
      code("model"),
      " is a default model selection resolved through ",
      code("ModelRegistry"),
      " at run time. ",
      code("memory"),
      " is the default memory key unless ",
      code("RunOptions.memory.key"),
      " overrides it. ",
      code("metadata"),
      " is host data carried with the agent value for registries and durable hosts.",
    ),
    p(
      code("R"),
      " contains every required service selected by the definition. A direct-model agent carries ",
      code("LanguageModel"),
      "; setting ",
      code("model"),
      " replaces it with ",
      code("ModelRegistry.ModelRegistry"),
      "; setting ",
      code("memory"),
      " adds ",
      code("Memory"),
      ". Static tools add their handler and codec requirements. The visible ",
      code("model"),
      " field is the only agent-level model default. For a registry-free run, omit it and provide a concrete ",
      code("LanguageModel"),
      " layer at the ",
      code("Agent.run"),
      " or ",
      code("Agent.stream"),
      " run boundary, where the layer requirements and scoped lifetime remain visible.",
    ),
    h2("run-functions", "Run functions"),
    table(
      ["Function", "Signature", "Notes"],
      [
        [
          [code("Agent.allocateRun")],
          [
            code(
              "(agent: Agent<..., I, O>, options: RunOptions) => Effect<RunHandle<Event<O.Type>, ...>, Steering.PolicyInvalid, Scope>",
            ),
          ],
          "Allocates one Run ID, event stream, and producer-only steer/followUp capability before lazy execution",
        ],
        [
          [code("Agent.stream")],
          [code("(agent: Agent<..., I, O>, input: I.Type, options?) => Stream<Event<O.Type>, RunError, ...>")],
          "Streams the loop and ends with Completed carrying the decoded output",
        ],
        [
          [code("Agent.run")],
          [code("(agent: Agent<..., I, O>, input: I.Type, options?) => Effect<O.Type, RunError, ...>")],
          "Folds the same stream to its schema-decoded output; supports data-last use",
        ],
        [
          [code("Agent.start")],
          [code("(agent, input, options) => Effect<RunHandle, StartError, Runtime>")],
          "Starts an Agent registered by unique name with Runtime and returns typed await/events",
        ],
      ],
    ),
    h2("run-options", "RunOptions"),
    table(
      ["Field", "Type", "Notes"],
      [
        [
          [code("history")],
          [code("Ai.Prompt.RawInput"), " (optional)"],
          "Prior transcript, used verbatim as the initial chat history; no system message is prepended",
        ],
        [
          [code("system")],
          [code("string"), " (optional)"],
          ["Overrides the derived system message when ", code("history"), " is not set"],
        ],
        [
          [code("resume")],
          [code("Resume"), " (optional)"],
          ["Re-entry after ", code("AgentSuspended"), ": verify and execute the checkpointed call"],
        ],
        [
          [code("sessionId")],
          [code("string"), " (optional)"],
          "Sole host-assigned Session identity; it never selects the process-local Run inbox",
        ],
        [
          [code("steering")],
          [code("Steering.Options"), " (optional)"],
          "Finite per-Run lane capacities, drain modes, overload behavior, and aggregate pending-byte bound",
        ],
        [
          [code("toolOutputMaxBytes")],
          [code("number"), " (optional)"],
          "Spill successful tool outputs whose encoded size exceeds this byte limit",
        ],
        [
          [code("compaction.contextWindow")],
          [code("number"), " (optional)"],
          "Context-window hint for optional compaction",
        ],
        [
          [code("memory.key")],
          [code("Memory.Key"), " (optional)"],
          ["Consult the Memory service for this run, overriding ", code("agent.memory"), " when present"],
        ],
      ],
    ),
    h2("run-services", "Requirements"),
    p(
      "A no-tool run needs a model, either as a direct ",
      code("Ai.LanguageModel.LanguageModel"),
      " layer or as ",
      code("agent.model"),
      " resolved through ",
      code("ModelRegistry"),
      ". Static toolkits conservatively retain their Effect AI handler and codec requirements. A ",
      code("ToolExecutor"),
      " override can handle calls at runtime but does not discharge those configured requirements. Configured or run-specific memory adds ",
      code("Memory"),
      ". Ambient enhancements such as approvals, compaction, instructions, middleware, resilience, permissions, sessions, skills, tokenization, tool execution overrides, and output spill remain optional. Steering is owned directly by each RunHandle, not discovered as an ambient service.",
    ),
    table(
      ["Service", "When it is needed"],
      [
        [[code("Ai.LanguageModel.LanguageModel")], ["When the agent has no ", code("model"), " default"]],
        [[code("ModelRegistry.ModelRegistry")], ["When the agent has a ", code("model"), " default"]],
        [[code("Ai.Tool.HandlersFor<Tools>")], ["When local toolkit handlers execute in-process"]],
        [[code("Memory.Memory")], ["When agent or run configuration selects a memory key"]],
        [[code('Input["EncodingServices"]')], ["When the Agent input schema needs services"]],
        [[code('Output["DecodingServices"]')], ["When the Agent output schema needs services"]],
        [[code("ToolExecutor.ToolExecutor")], ["Optional override for remote, client, MCP, sandbox, or durable tools"]],
        [[code("Approvals.Approvals")], ["Ambient optional approval behavior"]],
        [[code("ModelMiddleware.ModelMiddleware")], ["Ambient optional model input/output middleware"]],
      ],
    ),
    h2("run-error", "RunError"),
    p(
      "The error channel of every run function is the union ",
      code(
        "AgentError | InvalidOutput | AgentSuspended | ResumeMismatch | Error | PolicyStopped | TurnLimitExceeded | MiddlewareViolation | DuplicateToolCallId | ProgressOverflow | ToolNameCollision | AiError | LanguageModelNotRegistered | FrameworkFailure",
      ),
      ". Field shapes are tabulated in ",
      link("/docs/reference/core-events", "AgentEvent and errors"),
      ".",
    ),
    h2("resume", "Resume"),
    p(
      code("Resume"),
      " is ",
      code("{ suspension: AgentSuspended }"),
      ". The host passes the exact ",
      code("AgentSuspended"),
      " error as ",
      code("RunOptions.resume"),
      "; the run verifies it against the authoritative checkpoint before executing the unresolved call.",
    ),
    h2("result", "Typed result"),
    table(
      ["Type", "Shape"],
      [
        [[code("Agent.run(agent, input)")], [code("Effect<Agent.Output<typeof agent>, ...>")]],
        [[code("Completed<A>")], [code("{ output: A; text: string; turns: number; transcript: Prompt }")]],
      ],
    ),
    p(
      "For the loop behind these functions, see ",
      link("/docs/learn/agent-loop", "The agent loop"),
      ". For structured runs, see ",
      link("/docs/guides/structured-output", "How to get schema-validated output"),
      "; for deterministic runs in CI, see ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
    h2("agent-program-hosting", "Agent Program hosting"),
    table(
      ["Export", "Purpose", "Minimal use"],
      [
        [
          [code("ProgramManifest")],
          "Schema and canonical pin for sandboxed JavaScript source, codecs, allowed capabilities, and bounded resources",
          [
            code("ProgramManifest.make({ name, source, sandbox, input, output, capabilities, budget })"),
            " returns the validated manifest and its content pin",
          ],
        ],
        [
          [code("ProgramCapabilities")],
          "Host-owned encoded operations available only while sandboxed Program source is running",
          [
            code("yield* ProgramCapabilities.ProgramCapabilities"),
            " resolves the service before calling ",
            code("callTool"),
            ", ",
            code("callStep"),
            ", ",
            code("runAgent"),
            ", or ",
            code("log"),
          ],
        ],
      ],
    ),
  ],
})
