import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const coreAgentReference = definePage({
  path: "/docs/reference/core-agent",
  title: "Agent and run functions",
  navTitle: "Agent",
  group: "Reference",
  description: "Agent.make, stream and generate run functions, truthful requirements, RunError, Resume, and Result.",
  content: [
    lead(
      "The Agent namespace of tenetkit defines an opaque agent value, the stream and generate run functions, and every option and service a run consumes.",
    ),
    command("Install", "bun add tenetkit"),
    h2("agent-make", "Agent.make"),
    p(
      "An ",
      code("Agent<Tools, R>"),
      " is a plain value ",
      code("{ name, instructions?, toolkit, policy, model?, memory?, metadata? }"),
      ", not a service. ",
      code("Agent.make(options)"),
      " fills defaults:",
    ),
    table(
      ["Option", "Type", "Default"],
      [
        [[code("name")], [code("string")], "required"],
        [[code("instructions")], [code("string")], "none"],
        [[code("toolkit")], [code("Ai.Toolkit.Toolkit<Tools>")], [code("Ai.Toolkit.empty")]],
        [[code("policy")], [code("TurnPolicy.Policy")], [code("TurnPolicy.defaultPolicy")]],
        [[code("model")], [code("ModelRegistry.ModelSelection")], "none"],
        [[code("memory")], [code("Memory.Key")], "none"],
        [[code("metadata")], [code("Readonly<Record<string, unknown>>")], "none"],
      ],
    ),
    p(
      code("model"),
      " is a default model selection resolved through ",
      code("ModelRegistry"),
      " at run time. ",
      code("memory"),
      " is the default memory key unless ",
      code("RunOptions.memory.key"),
      " overrides it. ",
      code("metadata"),
      " is host data carried with the agent value for registries and durable hosts.",
    ),
    p(
      code("R"),
      " contains every required service selected by the definition. A direct-model agent carries ",
      code("LanguageModel"),
      "; setting ",
      code("model"),
      " replaces it with ",
      code("ModelRegistry.ModelRegistry"),
      "; setting ",
      code("memory"),
      " adds ",
      code("Memory"),
      ". Static tools add their handler and codec requirements. The visible ",
      code("model"),
      " field is the only agent-level model default. For a registry-free run, omit it and provide a concrete ",
      code("LanguageModel"),
      " layer at the ",
      code("Agent.stream"),
      " or ",
      code("Agent.generate"),
      " run boundary, where the layer requirements and scoped lifetime remain visible.",
    ),
    h2("run-functions", "Run functions"),
    table(
      ["Function", "Signature", "Notes"],
      [
        [
          [code("Agent.stream")],
          [code("(agent: Agent<Tools, R>, options: O) => Stream<AgentEvent.Event, RunError, RunRequirements<R, O>>")],
          "Streams text or schema-validated output; persistence and output are selected by options",
        ],
        [
          [code("Agent.generate")],
          [code("(agent: Agent<Tools, R>, options: O) => Effect<RunResult<O>, RunError, RunRequirements<R, O>>")],
          "Folds the same run; required output returns ObjectResult, while optional or union output produces the corresponding result union",
        ],
      ],
    ),
    h2("run-options", "RunOptions"),
    table(
      ["Field", "Type", "Notes"],
      [
        [
          [code("prompt")],
          [code("Ai.Prompt.RawInput")],
          ["User input for the first turn; ignored when ", code("resume"), " is set"],
        ],
        [
          [code("history")],
          [code("Ai.Prompt.RawInput"), " (optional)"],
          "Prior transcript, used verbatim as the initial chat history; no system message is prepended",
        ],
        [
          [code("system")],
          [code("string"), " (optional)"],
          ["Overrides the derived system message when ", code("history"), " is not set"],
        ],
        [
          [code("resume")],
          [code("Resume"), " (optional)"],
          ["Re-entry after ", code("AgentSuspended"), ": verify and execute the checkpointed call"],
        ],
        [[code("sessionId")], [code("string"), " (optional)"], "Opaque host-assigned identity for this run/session"],
        [
          [code("toolOutputMaxBytes")],
          [code("number"), " (optional)"],
          "Spill successful tool outputs whose encoded size exceeds this byte limit",
        ],
        [
          [code("compaction.contextWindow")],
          [code("number"), " (optional)"],
          "Context-window hint for optional compaction",
        ],
        [
          [code("memory.key")],
          [code("Memory.Key"), " (optional)"],
          ["Consult the Memory service for this run, overriding ", code("agent.memory"), " when present"],
        ],
        [
          [code("persistence")],
          [code("{ chatId: string; timeToLive?: Duration.Input }"), " (optional)"],
          "Runs on a persisted chat",
        ],
        [
          [code("output")],
          [code("{ schema: S; name?: string; prompt?: Ai.Prompt.RawInput }"), " (optional)"],
          [
            "Adds one terminal structured-output turn; name defaults to ",
            code('"output"'),
            " and prompt defaults to ",
            code("Agent.defaultObjectPrompt"),
          ],
        ],
      ],
    ),
    h2("run-services", "Requirements"),
    p(
      "A no-tool run needs a model, either as a direct ",
      code("Ai.LanguageModel.LanguageModel"),
      " layer or as ",
      code("agent.model"),
      " resolved through ",
      code("ModelRegistry"),
      ". Static toolkits conservatively retain their Effect AI handler and codec requirements. A ",
      code("ToolExecutor"),
      " override can handle calls at runtime but does not discharge those configured requirements. Configured or run-specific memory adds ",
      code("Memory"),
      ", and persistence options add ",
      code("Chat.Persistence"),
      " and an application-scoped ",
      code("Agent.Runtime"),
      ". Ambient enhancements such as approvals, compaction, instructions, middleware, resilience, permissions, sessions, skills, steering, tokenization, tool execution overrides, and output spill remain optional.",
    ),
    table(
      ["Service", "When it is needed"],
      [
        [[code("Ai.LanguageModel.LanguageModel")], ["When the agent has no ", code("model"), " default"]],
        [[code("ModelRegistry.ModelRegistry")], ["When the agent has a ", code("model"), " default"]],
        [[code("Ai.Tool.HandlersFor<Tools>")], ["When local toolkit handlers execute in-process"]],
        [[code("Memory.Memory")], ["When agent or run configuration selects a memory key"]],
        [[code("Ai.Chat.Persistence")], ["When RunOptions.persistence is set"]],
        [
          [code("Agent.Runtime")],
          ["When RunOptions.persistence is set; provide Agent.layerRuntime once per application"],
        ],
        [[code('S["DecodingServices"]')], ["When RunOptions.output.schema is set"]],
        [[code("ToolExecutor.ToolExecutor")], ["Optional override for remote, client, MCP, sandbox, or durable tools"]],
        [[code("Approvals.Approvals")], ["Ambient optional approval behavior"]],
        [[code("ModelMiddleware.ModelMiddleware")], ["Ambient optional model input/output middleware"]],
      ],
    ),
    h2("run-error", "RunError"),
    p(
      "The error channel of every run function is the union ",
      code(
        "AgentError | AgentSuspended | ResumeMismatch | TurnPolicyError | TurnPolicyStopped | TurnLimitExceeded | MiddlewareViolation | DuplicateToolCallId | ProgressOverflow | ToolNameCollision | AiError | LanguageModelNotRegistered | FrameworkFailure",
      ),
      ". Field shapes are tabulated in ",
      link("/docs/reference/core-events", "AgentEvent and errors"),
      ".",
    ),
    h2("resume", "Resume"),
    p(
      code("Resume"),
      " is ",
      code("{ suspension: AgentSuspended }"),
      ". The host passes the exact ",
      code("AgentSuspended"),
      " error as ",
      code("RunOptions.resume"),
      "; the run verifies it against the authoritative checkpoint before executing the unresolved call.",
    ),
    h2("result", "Result"),
    table(
      ["Type", "Shape"],
      [
        [[code("Result")], [code("{ text: string; turns: number; transcript: Ai.Prompt.Prompt }")]],
        [[code("ObjectResult<A>")], [code("Result"), " plus ", code("{ value: A }")]],
      ],
    ),
    p(
      "For the loop behind these functions, see ",
      link("/docs/learn/agent-loop", "The agent loop"),
      ". For structured runs, see ",
      link("/docs/guides/structured-output", "How to get schema-validated output"),
      "; for deterministic runs in CI, see ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
