import { callout, code, command, definePage, h2, h3, lead, link, p, table } from "../../../prose"
export const coreEventsReference = definePage({
  path: "/docs/reference/core-events",
  title: "AgentEvent and errors",
  navTitle: "AgentEvent",
  group: "Reference",
  description: "Process-local loop events, normalized model responses, telemetry, and typed run failures.",
  content: [
    lead(
      "AgentEvent is the process-local observation surface of the core loop. Runtime keeps the semantic execution facts from that stream, adds durable lifecycle facts, and deliberately excludes raw provider fragments.",
    ),
    command("Install", "bun add effect@4.0.0-rc.112 tenetkit@0.43.0"),
    h2("model-output", "Model output has two observation levels"),
    table(
      ["Event", "Fields", "Contract"],
      [
        [
          [code("ModelPart")],
          [
            code("turn"),
            ", ",
            code("modelCallId"),
            ", ",
            code("modelAttemptId"),
            ", ",
            code("attempt"),
            ", ",
            code("part"),
          ],
          [
            "A raw ",
            code("Ai.Response.StreamPart"),
            " visible only while directly observing ",
            code("Agent.stream"),
            ". It is tentative provider activity, not durable response authority.",
          ],
        ],
        [
          [code("ModelResponseCommitted")],
          [code("turn"), ", ", code("operationKey"), ", model identities, ", code("response"), ", ", code("digest")],
          [
            "Exactly one normalized semantic response after the model operation commits. ",
            code("response.content"),
            " contains complete text, reasoning, tool, source, file, metadata, and finish parts rather than provider deltas.",
          ],
        ],
      ],
    ),
    callout(
      "info",
      "Runtime persists semantics, not provider fragments",
      code("tenetkit/runtime"),
      " excludes ",
      code("ModelPart"),
      " from RunEvent history. Successful model operations publish ",
      code("ModelResponseCommitted"),
      "; a run that is cancelled or fails after output escaped can publish one ",
      code("ModelResponseInterrupted"),
      " with the normalized content observed before settlement. Database history, cursors, checkpoints, replay, SSE, WebSocket, and FoldKit all consume those semantic events.",
    ),
    h2("loop-events", "Loop and telemetry events"),
    p(
      "The rest of the union describes turn boundaries, tool execution and progress, approvals, steering, handoffs, structured output, completion, and model-call telemetry. Every event carries its stable correlation fields; ",
      code("turn"),
      " is 0-based wherever present.",
    ),
    table(
      ["Family", "Events", "Purpose"],
      [
        [
          "Turns and results",
          [code("TurnStarted"), ", ", code("TurnCompleted"), ", ", code("StructuredOutput"), ", ", code("Completed")],
          "Frame turns, expose transcripts, and report terminal values",
        ],
        [
          "Tools and approvals",
          [
            code("ToolExecutionStarted"),
            ", ",
            code("ToolProgress"),
            ", ",
            code("ToolExecutionCompleted"),
            ", ",
            code("ApprovalRequested"),
          ],
          "Describe tool execution without replacing Effect AI tool-call and tool-result payloads",
        ],
        [
          "Control flow",
          [
            code("SteeringDrained"),
            ", ",
            code("HandoffRequested"),
            ", ",
            code("HandoffCompleted"),
            ", ",
            code("HandoffRejected"),
          ],
          "Record observed steering and same-run specialist transitions",
        ],
        [
          "Model telemetry",
          [
            code("ModelCallStarted"),
            ", attempt/retry/fallback events, call completion or failure, and compaction events",
          ],
          "Expose provider-neutral lifecycle and retry decisions separately from semantic response content",
        ],
      ],
    ),
    h3("add-usage", "addUsage"),
    p(
      code("AgentEvent.addUsage(left, right)"),
      " returns the fieldwise sum of two ",
      code("Ai.Response.Usage"),
      " values, preserving ",
      code("undefined"),
      " when neither side reports a field.",
    ),
    h2("error-classes", "Error classes"),
    p("Expected failures are Schema tagged error classes under ", code("tenetkit/"), ". Key loop failures include:"),
    table(
      ["Error", "Raised when"],
      [
        [[code("AgentError")], "The loop fails and preserves its 0-based turn and cause"],
        [[code("RunEndedWithoutOutput")], "A terminal model turn leaves no committed assistant answer"],
        [
          [code("TurnLimitExceeded"), " / ", code("TurnPolicyStopped")],
          "Pending tool results cannot be re-fed under the active policy",
        ],
        [[code("MiddlewareViolation")], "A middleware hook breaks the loop contract, such as dropping a tool call"],
        [[code("AgentSuspended")], "A tool wait or approval parks a process-local run"],
        [[code("ResumeMismatch")], "A supplied suspension does not match the authoritative checkpoint"],
      ],
    ),
    callout(
      "info",
      "AgentSuspended is a contract, not a failure",
      "The host resolves the token out of band and re-enters through ",
      code("RunOptions.resume"),
      " with the exact suspension. TenetKit verifies it before any resumed side effect.",
    ),
    p(
      "For the loop that emits these events, see ",
      link("/docs/learn/agent-loop", "The agent loop"),
      ". For durable RunEvents and live previews, see ",
      link("/docs/reference/runtime", "tenetkit/runtime"),
      ".",
    ),
  ],
})
