import { callout, code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const corePoliciesReference = definePage({
  path: "/docs/reference/core-policies",
  title: "Policies and gating",
  navTitle: "Policies",
  group: "Reference",
  description: "TurnPolicy, Approvals, and Permissions: every decision union and layer constructor.",
  content: [
    lead(
      "Three namespaces of tenetkit gate what a run may do next: TurnPolicy decides follow-up turns, Approvals enforces needsApproval, and Permissions evaluates allow/deny/ask rules per tool call.",
    ),
    command("Install", "bun add tenetkit"),
    h2("turn-policy", "TurnPolicy"),
    p(
      "A policy is ",
      code("TurnPolicy<R> = { decide: (info: TurnInfo) => Effect<Decision, TurnPolicyError, R> }"),
      ", consulted before each follow-up turn. ",
      code("TurnInfo"),
      " carries ",
      code("turn"),
      " (0-based count of completed model turns), ",
      code("history"),
      ", and ",
      code("pendingToolResults"),
      ".",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("decision.continue(overrides?)"), " / ", code("decision.stop(reason)")],
          [
            code("Decision"),
            " constructors; ",
            code("TurnOverrides"),
            " may set ",
            code("instructions"),
            ", ",
            code("model"),
            " (a LanguageModel layer), and ",
            code("activeTools"),
            " for the next turn",
          ],
        ],
        [[code("make<R>(decide)")], "Policy from a decide Effect whose R remains in Agent run requirements"],
        [
          [code("forever")],
          "Continue after every turn; the run still completes naturally without pending tool results",
        ],
        [[code("recurs(n)")], ["Continue for at most ", code("n"), " follow-up turns after the first"]],
        [[code("untilToolCall(name)")], "Continue while the named tool has not yet been called this run"],
        [[code("both(first, second)")], ["Both must continue; overrides merge with ", code("second"), " winning"]],
        [[code("defaultPolicy")], [code("forever")]],
      ],
    ),
    h2("approvals", "Approvals"),
    p(
      "Resolution flow for permission asks and ",
      code("Ai.Tool.needsApproval"),
      ", which ",
      code("effect/unstable/ai"),
      " declares but never enforces. The interface is ",
      code("resolve: (pending: Pending) => Effect<Resolution>"),
      "; absent host policy uses the auto-approve default.",
    ),
    table(
      ["Resolution", "Fields", "Loop behavior"],
      [
        [[code("Approved")], [code("remember?")], "The optional rule is remembered, then the tool executes"],
        [[code("Denied")], [code("reason?")], ["The model receives a failed tool result with ", code("reason")]],
        [[code("Pending")], [code("token")], ["The run suspends with ", code('AgentSuspended{ reason: "approval" }')]],
      ],
    ),
    table(
      ["Layer", "Behavior"],
      [
        [[code("Approvals.layerAutoApprove")], "Every resolution returns Approved, the default choice"],
        [[code("Approvals.layerDenyAll")], "Every resolution returns Denied; useful in tests and lockdown"],
        [[code("Approvals.layerTest(implementation)")], "Layer from an explicit service"],
      ],
    ),
    h2("permissions", "Permissions"),
    p(
      "The rule matcher consulted before Approvals. Its only member is ",
      code("evaluate: (request: ToolAuthorization.AccessRequest) => Effect<Decision, PermissionError>"),
      ". Absent host policy uses allow-all permissions and an in-memory RuleStore.",
    ),
    table(
      ["Type", "Members", "Notes"],
      [
        [[code("Level")], [code('"allow" | "deny" | "ask"')], "What a matched rule grants"],
        [
          [code("Rule")],
          [code("pattern"), ", ", code("level"), ", ", code("reason?")],
          [
            "Pattern is ",
            code("tool"),
            " or ",
            code("tool:params"),
            " with ",
            code("*"),
            " globs matched against projected param text",
          ],
        ],
        [
          [code("Ruleset")],
          [code("rules"), ", ", code("fallback?")],
          ["Last matching rule wins; fallback defaults to ", code('"ask"')],
        ],
        [
          [code("AccessRequest")],
          [code("call"), ", ", code("agentName"), ", ", code("turn"), ", ", code("sessionId?")],
          "The shared access-boundary request",
        ],
        [[code("Decision")], [code("Allow | Deny{reason?} | Ask{token}")], "Resolved policy decision for one call"],
      ],
    ),
    table(
      ["Export", "Notes"],
      [
        [[code("matches(pattern, tool, params)")], "Match one permission pattern against a tool call"],
        [
          [code("evaluate(ruleset, tool, params)")],
          ["Pure ruleset evaluation to a ", code("Level"), " with last-match semantics"],
        ],
        [[code("layerRuleset(ruleset)")], "Policy layer from a static ruleset"],
        [[code("layerAllowAll")], "Policy layer that allows every call"],
        [[code("layerRuleStoreMemory(initialRules?)")], "Non-durable in-memory remembered-rule store"],
        [[code("layerTest"), " / ", code("layerRuleStoreTest")], "Layers from explicit services"],
        [[code("PermissionError")], ["Tagged error with ", code("message")]],
      ],
    ),
    callout(
      "info",
      "Deny rules fail closed",
      "When a params projection is incomplete (non-text leaves), a matching deny-level tool pattern applies regardless of its params pattern.",
    ),
    p(
      "See ",
      link("/docs/guides/turn-policy", "How to control turn budgets"),
      ", ",
      link("/docs/guides/approvals", "How to require human approval for a tool"),
      ", and ",
      link("/docs/guides/permissions", "How to gate tools with permission rules"),
      ".",
    ),
  ],
})
