import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const agentGuidanceReference = definePage({
  path: "/docs/reference/agent-guidance",
  title: "tenetkit/agent-guidance",
  navTitle: "agent guidance",
  group: "Reference",
  description:
    "The agent-guidance engine: versioned entries, audited refinements, rollback, scope merge, bounded overview, and content-addressed snapshots.",
  content: [
    lead(
      "tenetkit/agent-guidance is the generic engine for agent guidance an agent may refine and a host may pin into a later Execution. It owns entry identity, versions, atomic proposals, rollback, scope overlay, bounded prompt overviews, and snapshot identity. Store locations, scope policy, and refine flows stay host-owned.",
    ),
    command("Install", "bun add tenetkit tenetkit/agent-guidance"),
    p("Requires ", code("tenetkit"), "."),
    h2("entries", "Entry kinds"),
    p(
      "One guidance state holds four kinds of entry, each keyed by ",
      code("id"),
      " within its kind. An id may repeat across kinds.",
    ),
    table(
      ["Kind", "Meaning"],
      [
        [[code("prompt")], "A durable prompt note appended to the agent's standing guidance"],
        [[code("memory")], "A durable fact or preference the agent should retain"],
        [[code("skill")], "A reusable procedure, usually with a callable reference and arguments"],
        [[code("subagent")], "A delegation spec describing a reusable child role"],
      ],
    ),
    p(
      "Every entry carries ",
      code("id"),
      ", ",
      code("kind"),
      ", ",
      code("scope"),
      ", ",
      code("title"),
      ", ",
      code("content"),
      ", optional ",
      code("path"),
      ", ",
      code("reference"),
      ", ",
      code("arguments"),
      ", ",
      code("metadata"),
      ", ",
      code("source"),
      ", plus ",
      code("createdAt"),
      ", ",
      code("updatedAt"),
      ", and a monotonic ",
      code("version"),
      " that starts at 1.",
    ),
    h2("authorship", "Authored and trusted proposals"),
    p(
      "An edit's ",
      code("revision"),
      " pins an entry's exact ",
      code("createdAt"),
      ", ",
      code("updatedAt"),
      ", and ",
      code("version"),
      ". Rollback needs it; an untrusted author must never have it. The engine makes that a contract rather than host advice.",
    ),
    table(
      ["Path", "Contract"],
      [
        [
          [code("Authorship.authorProposal")],
          [
            "The only entry point for model-originated input. It decodes against ",
            code("AuthoredProposal"),
            ", whose create and update edits have no ",
            code("revision"),
            " field at all",
          ],
        ],
        [
          [code("Refinement.applyProposal")],
          [
            "Accepts only the opaque ",
            code("AuthoredRefinementProposal"),
            " that authorship mints, so an untrusted proposal shape cannot reach the apply seam by accident",
          ],
        ],
        [
          [code("Refinement.applyTrustedProposal")],
          [
            "The separately named route for a proposal that may pin a ",
            code("revision"),
            ", which is how rollback and restore work",
          ],
        ],
        [
          [code("Refinement.rollbackProposal")],
          ["The trusted path, which does set ", code("revision"), " so a rollback restores the exact earlier entry"],
        ],
        [
          [code("Authorship.isAuthored")],
          "Reports whether a proposal leaves every revision to the engine, for host-side assertions",
        ],
      ],
    ),
    p(
      "A pinned revision is refused with ",
      code('AuthorshipRejected { reason: "pinned-revision" }'),
      " rather than silently stripped, so a caller learns its proposal was rejected instead of quietly getting different semantics. Malformed input, unknown edit tags, empty edit lists, and excess properties fail ",
      code('reason: "malformed"'),
      ". An accepted authored create always lands at version 1, and an accepted authored update always bumps to ",
      code("version + 1"),
      " while preserving the original ",
      code("createdAt"),
      ".",
    ),
    h2("refinement", "Apply and rollback"),
    p(
      code("Refinement.applyProposal(state, proposal, options?)"),
      " takes the authored proposal and ",
      code("Refinement.applyTrustedProposal(state, proposal, options?)"),
      " takes one that may pin a revision. Both are pure and atomic: they return ",
      code("Result<RefinementResult, RefinementRejected>"),
      ", apply every edit or none, and never mutate their input. Each applied edit records the exact ",
      code("before"),
      " and ",
      code("after"),
      " entry, which is what makes rollback exact.",
    ),
    table(
      ["Rejection", "Cause"],
      [
        [[code("baseline-drift")], ["The proposal pinned a ", code("baseSnapshot"), " that is not the current state"]],
        [[code("create-existing")], "A create targeted an id that already exists in that kind"],
        [[code("update-missing")], "An update targeted an entry that does not exist"],
        [[code("delete-missing")], "A delete targeted an entry that does not exist"],
        [[code("duplicate-target")], "One proposal edited the same kind and id twice"],
        [[code("version-drift")], ["An edit pinned a ", code("baseVersion"), " that is not the entry's version"]],
        [[code("kind-capacity")], ["The result exceeded ", code("maxEntriesPerKind")]],
        [[code("rollback-not-newest")], "A rollback targeted anything other than the newest refinement"],
      ],
    ),
    p(
      code("Refinement.rollbackProposal(result, options)"),
      " builds the inverse proposal: edits reversed, each guarded by the version it undoes, and ",
      code("baseSnapshot"),
      " derived from the supplied current state. It marks the refinement being reversed, so applying anything other than the newest fails ",
      code("rollback-not-newest"),
      " before an inverse edit can report a misleading entry conflict. Applying the newest inverse restores the earlier snapshot exactly.",
    ),
    h2("merge", "Scope merge"),
    p(
      code("Merge.mergeStates(outer, inner)"),
      " overlays one scope on another. An inner entry wins over an outer entry of the same kind and id, an override applies only within a kind, every surviving entry keeps the scope that authored it, and the merged state takes the inner scope. Refinement history merges by instant, then scope, then proposal id, so the result is deterministic.",
    ),
    h2("overview", "Bounded prompt overview"),
    p(
      code("Overview.formatOverview(state, options?)"),
      " renders the compact overview a system prompt carries. Its size depends only on ",
      code("maxEntriesPerKind"),
      ", ",
      code("maxContentLength"),
      ", ",
      code("maxTitleLength"),
      ", and ",
      code("maxRefinements"),
      " — never on how many entries or refinements the state holds — so growing guidance cannot grow the prompt. Selection is id-sorted and kinds render in canonical order, so the same state always renders the same text. Full entries are read on demand from the state itself.",
    ),
    h2("snapshot", "Snapshot identity"),
    p(
      code("Snapshot.snapshot(state)"),
      " pins one exact state as ",
      code("guidance-snapshot:v1:sha256:<digest>"),
      " over the schema version, scope, and encoded entries. Refinement history is audit data and stays outside the identity, so recording an event does not change what a snapshot means. ",
      code("Snapshot.encode"),
      " produces the closed-JSON payload a durable host records in an executable registration under codec ",
      code("tenetkit/agent-guidance/snapshot"),
      ", version ",
      code("1"),
      ", and ",
      code("Snapshot.decode(id, payload)"),
      " reconstructs the exact state or fails ",
      code("SnapshotMismatch"),
      " or ",
      code("SnapshotInvalid"),
      ".",
    ),
    h2("store", "Store port and layers"),
    p(
      code("Store"),
      " is the load and save seam, keyed by scope. Loading an unknown scope yields an empty state; every other failure is a typed ",
      code("StoreError"),
      " carrying ",
      code('reason: "corrupt" | "encode" | "unreadable" | "unwritable"'),
      ".",
    ),
    table(
      ["Layer", "Use"],
      [
        [[code("Store.layerMemory")], "In-process state for tests and hosts without durable storage"],
        [[code("Store.layerTest")], "A supplied implementation for exercising host behavior"],
        [[code("FileSystemStore.layer({ path })")], ["Durable state over ", code("FileSystem"), " and ", code("Path")]],
      ],
    ),
    p(
      "The durable store keeps the location decision with the host through ",
      code("path(scope)"),
      " and owns only encoding and atomicity. A save writes a uniquely named temporary file at mode ",
      code("0600"),
      " inside the destination directory, creating it at mode ",
      code("0700"),
      " when missing, then renames it over the target. A reader never observes a partial state, a failed write leaves the previous state intact and removes its temporary, saves of one scope are serialized, and a corrupt file fails typed and stays on disk instead of resetting the scope. See ",
      link("/docs/reference/core-context", "tenetkit context"),
      " for the instruction and skill seams a host composes it with.",
    ),
  ],
})
