import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"

export const runtimeReference = definePage({
  path: "/docs/reference/runtime",
  title: "tenetkit/runtime",
  navTitle: "runtime",
  group: "Reference",
  description: "Addressable Run admission, canonical events, inspection, waits, stores, and workers.",
  content: [
    lead("tenetkit/runtime owns the authoritative lifecycle for addressable TenetKit runs."),
    command("Install", "bun add tenetkit tenetkit/runtime"),
    p("Published on npm at 0.14.0. All Runtime events and protocol adapters project from this package."),
    h2("surface", "Core surface"),
    table(
      ["Namespace", "Role"],
      [
        [
          [code("Runtime")],
          "Admission, durable events and history, disposable live previews, listing, waits, signals, cancellation, and inspection",
        ],
        [[code("RunEvent")], "Canonical persisted lifecycle and agent-loop event schema"],
        [[code("RunStore")], "Memory and SQLite storage seam"],
        [[code("RunSchema")], "PostgreSQL schema plan, check, and predeploy apply operations"],
        [[code("MysqlRunSchema")], "MySQL schema plan, check, predeploy apply, and dirty-state operations"],
        [[code("RunClaims"), " / ", code("RuntimeWorker")], "Multi-worker claims, leases, and worker loops"],
        [[code("Address"), " / ", code("ExecutableRef"), " / ", code("Cursor")], "Schema-backed boundary identities"],
      ],
    ),
    h2("staged-root", "Staged root activation"),
    p(
      code("Runtime.admit(input)"),
      " durably admits exactly one caller-identified root as queued without allowing a worker, scheduler, model, or tool to execute it. ",
      code("Runtime.activate({ runId })"),
      " independently makes that root runnable and returns its current ",
      code("RunInspection"),
      ". Activation and cancellation serialize in the authoritative store: cancellation that wins remains terminal across later activation, while duplicate activation appends only one attempt. Exact repeated admission returns the same receipt; changed payloads and conflicting Run IDs fail typed. ",
      code("Runtime.start(input)"),
      " remains the ordinary immediate path.",
    ),
    h2("model-output", "Semantic history and disposable previews"),
    p(
      code("Runtime.events"),
      " and ",
      code("Runtime.history"),
      " expose semantic model outcomes: one ",
      code("ModelResponseCommitted"),
      " after a successful model operation, or one ",
      code("ModelResponseInterrupted"),
      " when a run settles after partial output. Their normalized response content is stored, cursor-addressed, replayable, and projected by transport adapters.",
    ),
    p(
      code("Runtime.previews({ runId })"),
      " is a separate process-local observer for append-only text and reasoning while a provider attempt is live. Each frame and cadence buffer is bounded to ",
      code("ModelPreview.MaxPayloadCharacters"),
      " UTF-16 code units and cadence-limited by ",
      code("ModelPreview.MaxCadenceMillis"),
      ". Frame sequences and per-channel UTF-16 offsets expose loss to slow or late subscribers. Preview events are lossy, safe to drop, and never written to a database, assigned a RunEvent sequence, included in a cursor or checkpoint, replayed durably, or projected through the transport and FoldKit Chat contracts.",
    ),
    h2("layers", "Runtime layers"),
    p(
      code("Runtime.layerMemory"),
      " is ephemeral and loses state when its process exits. ",
      code("SqliteRuntime.layerSqlite"),
      " from ",
      code("tenetkit/runtime/sqlite-bun"),
      " is durable for one process. ",
      code("Runtime.layerPostgres"),
      " and ",
      code("Runtime.layerMysql"),
      " support multi-worker claims and require the schema to be applied before Runtime startup. PostgreSQL uses ",
      code("RunSchema"),
      "; MySQL 8+ uses ",
      code("MysqlRunSchema"),
      ".",
    ),
    p(
      "See ",
      link("/docs/reference/transport", "transport"),
      ", ",
      link("/docs/reference/a2a", "A2A"),
      ", and ",
      link("/docs/reference/ag-ui", "AG-UI"),
      " for projections.",
    ),
  ],
})
