import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const replReference = definePage({
  path: "/docs/reference/repl",
  title: "tenetkit/repl",
  navTitle: "repl",
  group: "Reference",
  description: "The one typescript cell tool, cell result and failure schemas, KernelProfile, and the kernel ports.",
  content: [
    lead(
      "tenetkit/repl gives an agent one persistent TypeScript cell per Session. The root export is contracts only, so projections, decoders, and test hosts import it without any worker code; tenetkit/repl/bun carries the Bun kernel and is the only module with process dependencies.",
    ),
    command("Install", "bun add tenetkit tenetkit/repl"),
    p("Requires ", code("tenetkit"), "."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("Cell"),
            ", ",
            code("CellTool"),
            ", ",
            code("KernelProfile"),
            ", ",
            code("KernelPool"),
            ", ",
            code("KernelStateStore"),
            ", ",
            code("HostBindingRegistry"),
            ", and ",
            code("TestKernel"),
          ],
        ],
        [[code("./bun")], "The Bun kernel implementation; the only module with process dependencies"],
      ],
    ),
    h2("cell-tool", "CellTool"),
    p(
      code("CellTool.tool"),
      " is one Effect AI tool named ",
      code("typescript"),
      " whose parameters are exactly one bounded string field named ",
      code("code"),
      " (",
      code("CellTool.maxSourceBytes"),
      ", 64 KiB). Success is ",
      code("Cell.CellResult"),
      "; failure is ",
      code("Cell.CellFailure"),
      " with ",
      code('failureMode: "return"'),
      ", so a failed cell re-enters the model as an observation instead of failing the run.",
    ),
    p(
      code("CellTool.layer"),
      " provides ",
      code("ToolExecutor.ToolExecutor"),
      " over ",
      code("ToolContext"),
      " and ",
      code("KernelPool"),
      ": it passes the call's ",
      code("signal"),
      " into the kernel, emits one progress update per cell event, and maps the terminal outcome. One shared namespace means ",
      code("CellTool.scheduling"),
      " is always ",
      code("{ maxConcurrency: 1, parallelSafe: [] }"),
      ", so every cell is an authored-order exclusive barrier.",
    ),
    h2("cell", "Cell result, failures, and events"),
    table(
      ["Type", "Meaning"],
      [
        [[code("CellResult")], "Complete formatted value, stdout and stderr, duration, and kernel epoch"],
        [[code("CellExecutionFailed")], "The cell threw; the namespace, the kernel, and every prior binding survive"],
        [[code("KernelUnavailable")], "No kernel could run the cell; nothing was evaluated"],
        [[code("KernelProtocolViolation")], "The kernel broke the cell protocol"],
        [[code("CellOutcomeUnknown")], "The cell may or may not have committed; a host resolves it explicitly"],
      ],
    ),
    p(
      code("Cell.CellEvent"),
      " is the closed union of ",
      code("KernelStarting"),
      ", ",
      code("KernelReady"),
      ", ",
      code("Stdout"),
      ", ",
      code("Stderr"),
      ", ",
      code("Result"),
      ", ",
      code("Display"),
      ", ",
      code("StateRestored"),
      ", ",
      code("StateLost"),
      ", and ",
      code("KernelRestarted"),
      ". Every event carries its ",
      code("cellId"),
      " and a cell-local ",
      code("sequence"),
      " that starts at 0 and increases by exactly one. ",
      code("Cell.validateSequence({ sessionId, events })"),
      " rejects a gap, a repeat, a non-zero start, and interleaving from a second cell.",
    ),
    h2("kernel-profile", "KernelProfile"),
    p(
      code("KernelProfile.make"),
      " pins one kernel epoch: contract and protocol versions, runtime identity and digest, bindings digest, workspace paths, ingestion limits, and trust mode. It declares no secret-bearing field, and unknown keys are dropped from both the encoded form and the digest; the content of its free-text identifier and path fields is host-supplied and is not scanned, so a host that embeds a secret in a path persists and renders it. A foreign protocol version fails to decode. ",
      code("KernelProfile.digest"),
      " is the content-addressed identity, and ",
      code("KernelProfile.bindingsDigest(names)"),
      " is independent of mount order.",
    ),
    h2("ports", "Kernel ports"),
    table(
      ["Service", "Interface"],
      [
        [
          [code("KernelPool")],
          [code("execute"), ", ", code("inspect"), ", ", code("interrupt"), ", ", code("restart"), ", ", code("close")],
        ],
        [[code("KernelStateStore")], [code("load"), ", ", code("save"), ", ", code("drop")]],
        [[code("HostBindingRegistry")], [code("descriptors"), ", ", code("resolve"), ", ", code("invoke")]],
      ],
    ),
    p(
      code("HostBindingRegistry.make(modules)"),
      " mounts named Schema-typed host modules into the kernel namespace and rejects duplicate module or operation names. Operation failures are tagged so a cell discriminates them as data, and schema faults report their stage.",
    ),
    h2("state", "State is working memory"),
    p(
      "Kernel variables are never durable authority. TenetKit operations, events, Session entries, and children remain the only truth; a restart reports exactly which bindings were restored and which were lost; and an uncertain cell is never replayed. ",
      code("KernelStateStore"),
      " snapshots are best effort, and their manifest names every restored and every dropped binding.",
    ),
    h2("test-kernel", "TestKernel"),
    p(
      code("TestKernel.layerTestPool({ profile, script? })"),
      " and ",
      code("TestKernel.layerMemoryStore"),
      " evaluate nothing but enforce the observable contract, so hosts and projections are tested without a worker process. See ",
      link("/docs/reference/core-tools", "tenetkit tools"),
      " for the executor and progress seams they compose with.",
    ),
  ],
})
