import { sha256Text } from "../../../core/durable/canonical-json.js"

export const SCHEMA_VERSION = 2
export const SCHEMA_META_TABLE = "tenetkit_schema_meta"
export const MIGRATIONS_TABLE = "tenetkit_sql_migrations"
export const MIGRATION_NAME = "tenetkit_runtime"

export const SCHEMA_STATEMENTS: ReadonlyArray<string> = [
  `CREATE TABLE IF NOT EXISTS tenetkit_schema_meta (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  version INTEGER NOT NULL,
  checksum TEXT NOT NULL,
  dirty INTEGER NOT NULL DEFAULT 0,
  applied_at TEXT NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_lanes (
  session_id TEXT PRIMARY KEY,
  accepted_sequence INTEGER NOT NULL,
  queue_json TEXT NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_runs (
  run_id TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  address TEXT NOT NULL,
  session_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  message_json TEXT NOT NULL,
  message_digest TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  executable_ref_json TEXT NOT NULL,
  executable_manifest_json TEXT NOT NULL,
  root_run_id TEXT NOT NULL,
  depth INTEGER NOT NULL,
  max_depth INTEGER NOT NULL,
  max_subagents INTEGER NOT NULL,
  parent_run_id TEXT,
  invocation_id TEXT,
  active_wait_id TEXT,
  attempt INTEGER NOT NULL DEFAULT 0,
  attempt_fence INTEGER NOT NULL DEFAULT 0,
  last_sequence INTEGER NOT NULL DEFAULT -1,
  cancellation_requested INTEGER NOT NULL DEFAULT 0,
  cancel_reason TEXT,
  terminal_event_id TEXT,
  accepted_sequence INTEGER NOT NULL,
  responded_wait_ids_json TEXT NOT NULL,
  driver_checkpoint_json TEXT,
  suspension_json TEXT,
  continuation_json TEXT,
  pending_outcome_json TEXT,
  owner_worker_id TEXT,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (address, session_id, idempotency_key)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_events (
  run_id TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  event_id TEXT NOT NULL UNIQUE,
  event_json TEXT NOT NULL,
  PRIMARY KEY (run_id, sequence),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_operations (
  run_id TEXT NOT NULL,
  operation_id TEXT NOT NULL,
  operation_key TEXT NOT NULL,
  kind TEXT NOT NULL,
  status TEXT NOT NULL,
  input_digest TEXT NOT NULL,
  input_json TEXT NOT NULL,
  result_json TEXT,
  error_json TEXT,
  replay_policy TEXT NOT NULL,
  attempt INTEGER NOT NULL,
  started_at TEXT,
  finished_at TEXT,
  resolution_idempotency_key TEXT,
  resolution_json TEXT,
  PRIMARY KEY (run_id, operation_id),
  UNIQUE (run_id, operation_key),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_waits (
  run_id TEXT NOT NULL,
  wait_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL,
  response_json TEXT,
  opened_at TEXT NOT NULL,
  closed_at TEXT,
  PRIMARY KEY (run_id, wait_id),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_links (
  parent_run_id TEXT NOT NULL,
  child_run_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  readiness TEXT NOT NULL,
  terminal_event_id TEXT,
  created_at TEXT NOT NULL,
  settled_at TEXT,
  PRIMARY KEY (parent_run_id, child_run_id),
  UNIQUE (child_run_id),
  FOREIGN KEY (parent_run_id) REFERENCES tenetkit_runs(run_id),
  FOREIGN KEY (child_run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_run_links_readiness_idx ON tenetkit_run_links(parent_run_id, readiness, created_at, child_run_id)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_external_child_placements (
  placement_id TEXT PRIMARY KEY,
  parent_run_id TEXT NOT NULL,
  partition TEXT NOT NULL,
  external_run_id TEXT NOT NULL,
  invocation_id TEXT NOT NULL,
  request_digest TEXT NOT NULL,
  executable_digest TEXT NOT NULL,
  wait_id TEXT,
  suspension_identity TEXT,
  acknowledged INTEGER NOT NULL DEFAULT 0,
  cancel_requested INTEGER NOT NULL DEFAULT 0,
  settlement_id TEXT,
  outcome_json TEXT,
  outcome_event_id TEXT,
  created_at TEXT NOT NULL,
  settled_at TEXT,
  FOREIGN KEY (parent_run_id) REFERENCES tenetkit_runs(run_id),
  UNIQUE (partition, external_run_id),
  UNIQUE (parent_run_id, invocation_id),
  CHECK ((settlement_id IS NULL AND outcome_json IS NULL AND outcome_event_id IS NULL AND settled_at IS NULL)
    OR (settlement_id IS NOT NULL AND outcome_json IS NOT NULL AND outcome_event_id IS NOT NULL AND settled_at IS NOT NULL))
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_external_child_placements_parent_idx ON tenetkit_external_child_placements(parent_run_id, settlement_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_external_roots (
  placement_id TEXT PRIMARY KEY,
  parent_partition TEXT NOT NULL,
  parent_run_id TEXT NOT NULL,
  partition TEXT NOT NULL,
  run_id TEXT NOT NULL UNIQUE,
  session_id TEXT NOT NULL,
  request_digest TEXT NOT NULL,
  executable_digest TEXT NOT NULL,
  admission_digest TEXT NOT NULL,
  activated INTEGER NOT NULL DEFAULT 0,
  settlement_acknowledged INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL,
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_steering (
  entry_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  idempotency_key TEXT NOT NULL,
  digest TEXT NOT NULL,
  prompt_json TEXT NOT NULL,
  consumed_operation_id TEXT,
  discarded_reason TEXT,
  UNIQUE (run_id, sequence),
  UNIQUE (run_id, idempotency_key),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_run_steering_pending_idx ON tenetkit_run_steering(run_id, consumed_operation_id, discarded_reason, sequence)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_agent_names (
  scope TEXT NOT NULL,
  name TEXT NOT NULL,
  run_id TEXT NOT NULL,
  PRIMARY KEY (scope, name),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_agent_names_run_idx ON tenetkit_agent_names(run_id)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_messages (
  entry_id TEXT PRIMARY KEY,
  target_session_id TEXT NOT NULL,
  sequence INTEGER NOT NULL,
  from_address TEXT NOT NULL,
  from_run_id TEXT NOT NULL,
  to_address TEXT NOT NULL,
  message_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  digest TEXT NOT NULL,
  bytes INTEGER NOT NULL,
  admitted_at_millis INTEGER NOT NULL,
  prompt_json TEXT NOT NULL,
  correlation_id TEXT NOT NULL,
  causation_id TEXT,
  in_reply_to TEXT,
  metadata_json TEXT NOT NULL,
  delivered_run_id TEXT,
  steering_entry_id TEXT,
  UNIQUE (target_session_id, message_id, idempotency_key),
  UNIQUE (target_session_id, sequence)
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_messages_pending_idx ON tenetkit_messages(target_session_id, delivered_run_id, sequence)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_runs_lane_idx ON tenetkit_runs(session_id, status)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_runs_schedule_idx ON tenetkit_runs(status, created_at, run_id)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_run_operations_status_idx ON tenetkit_run_operations(status)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_fan_outs (
  fan_out_id TEXT PRIMARY KEY,
  parent_run_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  input_digest TEXT NOT NULL,
  join_json TEXT NOT NULL,
  remainder TEXT NOT NULL,
  concurrency INTEGER NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  UNIQUE (parent_run_id, idempotency_key),
  FOREIGN KEY (parent_run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_fan_out_members (
  fan_out_id TEXT NOT NULL,
  ordinal INTEGER NOT NULL,
  member_key TEXT NOT NULL,
  selection TEXT NOT NULL,
  display_label TEXT,
  prompt_json TEXT NOT NULL,
  origin_json TEXT,
  child_run_id TEXT NOT NULL UNIQUE,
  depth INTEGER NOT NULL,
  status TEXT NOT NULL,
  terminal_event_id TEXT,
  outcome_json TEXT,
  PRIMARY KEY (fan_out_id, ordinal),
  UNIQUE (fan_out_id, member_key),
  FOREIGN KEY (fan_out_id) REFERENCES tenetkit_fan_outs(fan_out_id),
  FOREIGN KEY (child_run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_fan_out_members_status_idx ON tenetkit_fan_out_members(fan_out_id, status, ordinal)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_tree_roots (
  root_run_id TEXT PRIMARY KEY,
  earliest_position INTEGER NOT NULL DEFAULT 0,
  last_position INTEGER NOT NULL DEFAULT -1,
  FOREIGN KEY (root_run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_tree_event_index (
  root_run_id TEXT NOT NULL,
  position INTEGER NOT NULL,
  run_id TEXT NOT NULL,
  run_sequence INTEGER NOT NULL,
  event_id TEXT NOT NULL,
  PRIMARY KEY (root_run_id, position),
  UNIQUE (event_id),
  UNIQUE (run_id, run_sequence),
  FOREIGN KEY (root_run_id) REFERENCES tenetkit_tree_roots(root_run_id),
  FOREIGN KEY (run_id, run_sequence) REFERENCES tenetkit_run_events(run_id, sequence),
  FOREIGN KEY (event_id) REFERENCES tenetkit_run_events(event_id)
  )`,
  `CREATE TABLE IF NOT EXISTS tenetkit_program_runs (
  run_id TEXT PRIMARY KEY,
  program_pin TEXT NOT NULL,
  budget_json TEXT NOT NULL,
  deadline_millis INTEGER NOT NULL,
  tool_calls INTEGER NOT NULL DEFAULT 0,
  agent_runs INTEGER NOT NULL DEFAULT 0,
  tokens INTEGER NOT NULL DEFAULT 0,
  log_bytes INTEGER NOT NULL DEFAULT 0,
  active_slots INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_program_operations (
  run_id TEXT NOT NULL,
  operation_name TEXT NOT NULL,
  kind TEXT NOT NULL,
  capability TEXT NOT NULL,
  input_digest TEXT NOT NULL,
  input_json TEXT NOT NULL,
  replay_policy TEXT NOT NULL,
  status TEXT NOT NULL,
  result_json TEXT,
  error_json TEXT,
  wait_id TEXT,
  fan_out_id TEXT,
  child_run_ids_json TEXT NOT NULL,
  resolution_idempotency_key TEXT,
  resolution_json TEXT,
  PRIMARY KEY (run_id, operation_name),
  FOREIGN KEY (run_id) REFERENCES tenetkit_program_runs(run_id)
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_executable_registrations (
  pin TEXT PRIMARY KEY,
  codec TEXT NOT NULL,
  version TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  registration_digest TEXT NOT NULL
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_run_registrations (
  run_id TEXT NOT NULL,
  pin TEXT NOT NULL,
  PRIMARY KEY (run_id, pin),
  FOREIGN KEY (run_id) REFERENCES tenetkit_runs(run_id),
  FOREIGN KEY (pin) REFERENCES tenetkit_executable_registrations(pin)
  )`,
  `CREATE INDEX IF NOT EXISTS tenetkit_run_registrations_pin_idx ON tenetkit_run_registrations(pin)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_sessions (
  session_id TEXT PRIMARY KEY,
  leaf_id TEXT,
  next_seq INTEGER NOT NULL DEFAULT 0,
  writer_epoch INTEGER NOT NULL DEFAULT 0,
  writer_run_id TEXT,
  writer_owner_id TEXT,
  writer_attempt_fence INTEGER,
  updated_at TEXT NOT NULL,
  CHECK ((writer_run_id IS NULL AND writer_owner_id IS NULL AND writer_attempt_fence IS NULL)
    OR (writer_run_id IS NOT NULL AND writer_owner_id IS NOT NULL AND writer_attempt_fence IS NOT NULL))
)`,
  `CREATE TABLE IF NOT EXISTS tenetkit_session_entries (
  session_id TEXT NOT NULL,
  entry_id TEXT NOT NULL,
  parent_id TEXT,
  seq INTEGER NOT NULL,
  tag TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (session_id, entry_id)
)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS tenetkit_session_entries_seq_idx ON tenetkit_session_entries(session_id, seq)`,
  `CREATE INDEX IF NOT EXISTS tenetkit_session_entries_parent_idx ON tenetkit_session_entries(session_id, parent_id)`,
]

export const SCHEMA_TABLES: ReadonlyArray<string> = SCHEMA_STATEMENTS.flatMap(
  (statement) => statement.match(/^CREATE TABLE IF NOT EXISTS (\w+)/)?.slice(1, 2) ?? [],
)

export const schemaChecksum = (): string => sha256Text(`${SCHEMA_STATEMENTS.join("\n")}\nversion=${SCHEMA_VERSION}`)
