import eventTrace from "virtual:source/src/snippets/learn/agent-loop/event-trace.ts"
import eventTraceExpected from "virtual:source/src/snippets/learn/agent-loop/event-trace.expected.txt"
import { code, codeBlock, definePage, h2, link, p } from "../../prose"
export const agentLoop = definePage({
  path: "/docs/learn/agent-loop",
  title: "The agent loop",
  navTitle: "The agent loop",
  group: "Learn",
  description:
    "What a turn is, when follow-up turns run, and why the AgentEvent stream is the whole observable surface of a TenetKit run.",
  content: [
    p(
      "An ",
      code("Agent"),
      " is a plain value: a name, instructions, a toolkit, and a turn policy. Nothing runs when you call ",
      code("Agent.make"),
      ". The loop starts when you hand that value to ",
      code("Agent.stream"),
      ", the primitive every other run function derives from, together with the four services a run requires. This page explains what happens between the first model call and the terminal ",
      code("Completed"),
      " event.",
    ),
    h2("what-a-turn-is", "What a turn is"),
    p(
      "A turn is one model call plus the sequential execution of every tool call that model call emits. Turn 0 always runs. When the model responds with tool calls, TenetKit executes them in order through the ",
      code("ToolExecutor"),
      " service, collects the results, and feeds them back to the model via ",
      code("Ai.Prompt.fromResponseParts(...)"),
      " as the next turn's input. Under the hood the loop drives an ",
      code("Ai.Chat"),
      " with ",
      code("disableToolCallResolution: true"),
      ", so TenetKit, not the model client, owns tool execution, gating, and re-feeding.",
    ),
    p(
      "Pending tool results are never silently dropped. If the policy stops the loop while results are still waiting to be re-fed, the run fails with ",
      code("TurnLimitExceeded"),
      " only for a configured recurrence cap, or with ",
      code("TurnPolicyStopped"),
      " for another explicit stop reason. Both list the pending calls rather than pretending the conversation ended cleanly.",
    ),
    h2("turn-policy-gates-follow-ups", "TurnPolicy gates follow-up turns"),
    p(
      code("TurnPolicy"),
      " is a plain value carried by the agent, in the same spirit as an Effect ",
      code("Schedule"),
      ", not a service you provide. It is consulted only when tool results are pending: a turn that produced plain text completes the run regardless of policy. The default is ",
      code("forever"),
      ", which never caps follow-up turns; ",
      code("recurs(n)"),
      " bounds them explicitly, and ",
      code("untilToolCall"),
      " and ",
      code("both"),
      " compose other stopping conditions. ",
      link("/docs/guides/turn-policy", "How to control turn budgets"),
      " covers per-turn overrides and a token-budget recipe.",
    ),
    h2("the-event-stream-is-the-api", "The event stream is the API"),
    p(
      "Everything observable about a process-local run arrives through ",
      code("AgentEvent.Event"),
      ": turn, tool, approval, steering, handoff, structured-output, completion, and model telemetry facts share one ordered stream. A successful model operation emits one ",
      code("ModelResponseCommitted"),
      " whose normalized ",
      code("response.content"),
      " is the semantic output for downstream projections. Direct ",
      code("Agent.stream"),
      " observers can also see tentative ",
      code("ModelPart"),
      " provider fragments, but those are deliberately not durable authority. This trace filters that local-only detail so the semantic loop is clear:",
    ),
    codeBlock({ label: "event-trace.ts", source: eventTrace, expectedOutput: eventTraceExpected }),
    p(
      "Turn 0 commits a normalized tool-call response, executes the tool, and completes; turn 1 re-feeds the result and commits the text response, so the run ends with ",
      code("Completed"),
      ". Each ",
      code("TurnCompleted"),
      " carries the full transcript so far. A durable Runtime stores normalized response content once in Session and persists a compact semantic event referencing that exact entry; observer transports hydrate the reference. Provider fragments are never durable. The event contracts live in ",
      link("/docs/reference/core-events", "AgentEvent and errors"),
      ".",
    ),
    h2("everything-else-is-a-fold", "generate and the object runs are folds"),
    p(
      code("Agent.generate"),
      " runs the same stream and folds it down to the terminal ",
      code("Completed"),
      " event, returning ",
      code("{ text, turns, transcript }"),
      ". ",
      code("Agent.stream"),
      " and ",
      code("Agent.generate"),
      " run the identical loop and then one terminal structured-output turn validated against your schema; see ",
      link("/docs/guides/structured-output", "How to get schema-validated output"),
      ". There is no second loop implementation to learn: one primitive, three folds.",
    ),
    p(
      "Runs do not always end in ",
      code("Completed"),
      ": a tool that needs a human parks the run on the error channel instead, which is the subject of ",
      link("/docs/learn/suspension", "Suspension as a typed error"),
      ". To build the loop yourself from an empty directory, start with ",
      link("/docs/start/quickstart", "the quickstart"),
      ".",
    ),
  ],
})
