import eventTrace from "../../snippets/learn/agent-loop/event-trace.ts?raw"
import eventTraceExpected from "../../snippets/learn/agent-loop/event-trace.expected.txt?raw"
import * as Prose from "../../prose"

export const agentLoop = Prose.definePage({
  path: "/docs/learn/agent-loop",
  title: "The agent loop",
  navTitle: "The agent loop",
  group: "Learn",
  description:
    "What a turn is, when follow-up turns run, and why the AgentEvent stream is the whole observable surface of a Batonfx run.",
  content: [
    Prose.p(
      "An ",
      Prose.code("Agent"),
      " is a plain value: a name, instructions, a toolkit, and a turn policy. Nothing runs when you call ",
      Prose.code("Agent.make"),
      ". The loop starts when you hand that value to ",
      Prose.code("Agent.stream"),
      ", the primitive every other run function derives from, together with the four services a run requires. This page explains what happens between the first model call and the terminal ",
      Prose.code("Completed"),
      " event.",
    ),
    Prose.h2("what-a-turn-is", "What a turn is"),
    Prose.p(
      "A turn is one model call plus the sequential execution of every tool call that model call emits. Turn 0 always runs. When the model responds with tool calls, Batonfx executes them in order through the ",
      Prose.code("ToolExecutor"),
      " service, collects the results, and feeds them back to the model via ",
      Prose.code("Ai.Prompt.fromResponseParts(...)"),
      " as the next turn's input. Under the hood the loop drives an ",
      Prose.code("Ai.Chat"),
      " with ",
      Prose.code("disableToolCallResolution: true"),
      ", so Batonfx, not the model client, owns tool execution, gating, and re-feeding.",
    ),
    Prose.p(
      "Pending tool results are never silently dropped. If the policy stops the loop while results are still waiting to be re-fed, the run fails with ",
      Prose.code("TurnLimitExceeded"),
      " listing the pending calls, rather than pretending the conversation ended cleanly.",
    ),
    Prose.h2("turn-policy-gates-follow-ups", "TurnPolicy gates follow-up turns"),
    Prose.p(
      Prose.code("TurnPolicy"),
      " is a plain value carried by the agent, in the same spirit as an Effect ",
      Prose.code("Schedule"),
      ", not a service you provide. It is consulted only when tool results are pending: a turn that produced plain text completes the run regardless of policy. The default is ",
      Prose.code("recurs(8)"),
      ", allowing up to eight follow-up turns; ",
      Prose.code("untilToolCall"),
      " and ",
      Prose.code("both"),
      " compose other stopping conditions. ",
      Prose.link("/docs/guides/turn-policy", "How to control turn budgets"),
      " covers per-turn overrides and a token-budget recipe.",
    ),
    Prose.h2("the-event-stream-is-the-api", "The event stream is the API"),
    Prose.p(
      "Everything observable about a run arrives as one closed union, ",
      Prose.code("AgentEvent.Event"),
      ", with exactly nine members: ",
      Prose.code("TurnStarted"),
      ", ",
      Prose.code("ModelPart"),
      ", ",
      Prose.code("ToolExecutionStarted"),
      ", ",
      Prose.code("ToolProgress"),
      ", ",
      Prose.code("ToolExecutionCompleted"),
      ", ",
      Prose.code("ApprovalRequested"),
      ", ",
      Prose.code("TurnCompleted"),
      ", ",
      Prose.code("StructuredOutput"),
      ", and ",
      Prose.code("Completed"),
      ". Hosts persist these events, render them in a UI, or translate them onto a transport without the core loop knowing or caring. This trace uses a scripted model and runs with zero credentials:",
    ),
    Prose.codeBlock({ label: "event-trace.ts", source: eventTrace, expectedOutput: eventTraceExpected }),
    Prose.p(
      "Turn 0 calls the model, executes the tool, and completes; turn 1 re-feeds the result and the model answers in text, so the run ends with ",
      Prose.code("Completed"),
      ". Each ",
      Prose.code("TurnCompleted"),
      " carries the full transcript so far, which is the export point durable hosts read. The field-by-field contract for all nine events lives in ",
      Prose.link("/docs/reference/core-events", "AgentEvent and errors"),
      ".",
    ),
    Prose.h2("everything-else-is-a-fold", "generate and the object runs are folds"),
    Prose.p(
      Prose.code("Agent.generate"),
      " runs the same stream and folds it down to the terminal ",
      Prose.code("Completed"),
      " event, returning ",
      Prose.code("{ text, turns, transcript }"),
      ". ",
      Prose.code("Agent.streamObject"),
      " and ",
      Prose.code("Agent.generateObject"),
      " run the identical loop and then one terminal structured-output turn validated against your schema; see ",
      Prose.link("/docs/guides/structured-output", "How to get schema-validated output"),
      ". There is no second loop implementation to learn: one primitive, three folds.",
    ),
    Prose.p(
      "Runs do not always end in ",
      Prose.code("Completed"),
      ": a tool that needs a human parks the run on the error channel instead, which is the subject of ",
      Prose.link("/docs/learn/suspension", "Suspension as a typed error"),
      ". To build the loop yourself from an empty directory, start with ",
      Prose.link("/docs/start/quickstart", "the quickstart"),
      ".",
    ),
  ],
})
