import portableTranscript from "../../snippets/learn/one-payload-vocabulary/portable-transcript.ts?raw"
import portableTranscriptExpected from "../../snippets/learn/one-payload-vocabulary/portable-transcript.expected.txt?raw"
import * as Prose from "../../prose"

export const onePayloadVocabulary = Prose.definePage({
  path: "/docs/learn/one-payload-vocabulary",
  title: "One payload vocabulary",
  navTitle: "One payload vocabulary",
  group: "Learn",
  description:
    "Batonfx has no message type of its own: Ai.Prompt and Ai.Response from effect/unstable/ai are the payload vocabulary end to end.",
  content: [
    Prose.p(
      "Most agent frameworks define their own message shape and then translate at every boundary: provider messages in, framework messages through the middle, UI messages out. Batonfx refuses that translation layer. The payload vocabulary is ",
      Prose.code("Ai.Prompt"),
      " and ",
      Prose.code("Ai.Response"),
      " from ",
      Prose.code("effect/unstable/ai"),
      ", end to end. Batonfx adds loop framing only — no second wire format.",
    ),
    Prose.h2("one-vocabulary-end-to-end", "One vocabulary end to end"),
    Prose.p(
      "Your prompt enters a run as ",
      Prose.code("Ai.Prompt.RawInput"),
      ". The model's output flows through the loop as ",
      Prose.code("Ai.Response"),
      " stream parts, passed through unchanged inside ",
      Prose.code("ModelPart"),
      " events. Tool results are re-fed to the model via ",
      Prose.code("Ai.Prompt.fromResponseParts(...)"),
      ". And the transcript on ",
      Prose.code("TurnCompleted"),
      " and ",
      Prose.code("Completed"),
      " is an ordinary ",
      Prose.code("Ai.Prompt.Prompt"),
      ". At no point does a Batonfx-specific message type appear between you and the model.",
    ),
    Prose.h2("what-makepart-is", "What makePart is"),
    Prose.p(
      Prose.code("Ai.Response.makePart"),
      " is the upstream constructor for typed stream parts — ",
      Prose.code("text-delta"),
      ", ",
      Prose.code("tool-call"),
      ", ",
      Prose.code("tool-result"),
      ", and friends. It matters for docs and tests because a scripted model built with ",
      Prose.code("Ai.LanguageModel.make"),
      " emits exactly the same parts a real provider does. Every zero-credential example on this site speaks the production vocabulary; there is no test-only dialect to unlearn when you wire a real provider.",
    ),
    Prose.h2("what-this-buys-the-host", "What this buys the host"),
    Prose.p(
      "Because the transcript is a plain ",
      Prose.code("Ai.Prompt.Prompt"),
      ", it is portable to any consumer of ",
      Prose.code("effect/unstable/ai"),
      " — including a later Batonfx run. Here a run's transcript is handed straight back as ",
      Prose.code("history"),
      " for a second run, with no conversion step:",
    ),
    Prose.codeBlock({
      label: "portable-transcript.ts",
      source: portableTranscript,
      expectedOutput: portableTranscriptExpected,
    }),
    Prose.p(
      "The printed roles — ",
      Prose.code("system user assistant tool"),
      " — are upstream message roles, not Batonfx inventions. The same portability holds outward: a durable host can persist the transcript, a transport can serialize events with upstream schemas, and an eval harness can assert on response parts, all against types owned by ",
      Prose.code("effect"),
      " rather than by this framework.",
    ),
    Prose.h2("the-invariant", "The invariant"),
    Prose.p(
      "The rule is blunt: payload vocabulary is ",
      Prose.code("Ai.Prompt"),
      "/",
      Prose.code("Ai.Response"),
      "; Batonfx adds loop framing only. Even ",
      Prose.link("/docs/guides/serve-transport", "the wire frames"),
      " that carry a run over SSE or WebSocket wrap the same ",
      Prose.code("AgentEvent"),
      " values rather than re-encoding them. The one thing Batonfx does define — the nine-member event union and its typed errors — is framing about the loop, not a message format, and it is catalogued in ",
      Prose.link("/docs/reference/core-events", "AgentEvent and errors"),
      ". How that framing drives the loop is the subject of ",
      Prose.link("/docs/learn/agent-loop", "The agent loop"),
      ".",
    ),
  ],
})
