import portableTranscript from "virtual:source/src/snippets/learn/one-payload-vocabulary/portable-transcript.ts"
import portableTranscriptExpected from "virtual:source/src/snippets/learn/one-payload-vocabulary/portable-transcript.expected.txt"
import { code, codeBlock, definePage, h2, link, p } from "../../prose"
export const onePayloadVocabulary = definePage({
  path: "/docs/learn/one-payload-vocabulary",
  title: "One payload vocabulary",
  navTitle: "One payload vocabulary",
  group: "Learn",
  description:
    "TenetKit has no message type of its own: Ai.Prompt and Ai.Response from effect/unstable/ai are the payload vocabulary end to end.",
  content: [
    p(
      "Most agent frameworks define their own message shape and then translate at every boundary: provider messages in, framework messages through the middle, UI messages out. TenetKit refuses that translation layer. The payload vocabulary is ",
      code("Ai.Prompt"),
      " and ",
      code("Ai.Response"),
      " from ",
      code("effect/unstable/ai"),
      ", end to end. TenetKit adds loop framing only, with no second wire format.",
    ),
    h2("one-vocabulary-end-to-end", "One vocabulary end to end"),
    p(
      "Your prompt enters a run as ",
      code("Ai.Prompt.RawInput"),
      ". Providers may produce delta-shaped ",
      code("Ai.Response.StreamPart"),
      " values while a call is live, but the authoritative model outcome is one ",
      code("ModelResponseCommitted"),
      " carrying normalized, complete ",
      code("Ai.Response"),
      " content. Tool results are re-fed to the model via ",
      code("Ai.Prompt.fromResponseParts(...)"),
      ". The transcript on ",
      code("TurnCompleted"),
      " and ",
      code("Completed"),
      " is an ordinary ",
      code("Ai.Prompt.Prompt"),
      ". At no point does a TenetKit-specific message type appear between you and the model.",
    ),
    h2("what-makepart-is", "What makePart is"),
    p(
      code("Ai.Response.makePart"),
      " is the upstream constructor for typed stream parts: ",
      code("text-delta"),
      ", ",
      code("tool-call"),
      ", ",
      code("tool-result"),
      ", and friends. It matters for docs and tests because a scripted model built with ",
      code("Ai.LanguageModel.make"),
      " emits exactly the same parts a real provider does. Every zero-credential example on this site speaks the production vocabulary; there is no test-only dialect to unlearn when you wire a real provider.",
    ),
    h2("what-this-buys-the-host", "What this buys the host"),
    p(
      "Because the transcript is a plain ",
      code("Ai.Prompt.Prompt"),
      ", it is portable to any consumer of ",
      code("effect/unstable/ai"),
      ", including a later TenetKit run. Here a run's transcript is handed straight back as ",
      code("history"),
      " for a second run, with no conversion step:",
    ),
    codeBlock({
      label: "portable-transcript.ts",
      source: portableTranscript,
      expectedOutput: portableTranscriptExpected,
    }),
    p(
      "The printed roles (",
      code("system user assistant tool"),
      ") are upstream message roles, not TenetKit inventions. The same portability holds outward: a durable host stores normalized response content once in Session and persists a compact event reference, transport resolves that reference into a semantic observer event with upstream payload schemas, and an eval harness can assert on normalized response parts, all against types owned by ",
      code("effect"),
      " rather than by this framework.",
    ),
    h2("the-invariant", "The invariant"),
    p(
      "The rule is blunt: payload vocabulary is ",
      code("Ai.Prompt"),
      "/",
      code("Ai.Response"),
      "; TenetKit adds loop framing only. Even ",
      link("/docs/guides/serve-transport", "the wire frames"),
      " that carry a run over SSE or WebSocket wrap canonical Runtime ",
      code("RunEvent"),
      " values rather than re-encoding provider fragments. Successful and interrupted model operations cross that boundary as ",
      code("ModelResponseCommitted"),
      " or ",
      code("ModelResponseInterrupted"),
      ". TenetKit's event unions and typed errors are framing about the loop, not a second message format, and they are catalogued in ",
      link("/docs/reference/core-events", "AgentEvent and errors"),
      ". How that framing drives the loop is the subject of ",
      link("/docs/learn/agent-loop", "The agent loop"),
      ".",
    ),
  ],
})
