import fourLayers from "../../snippets/learn/seams-as-services/four-layers.ts?raw"
import fourLayersExpected from "../../snippets/learn/seams-as-services/four-layers.expected.txt?raw"
import * as Prose from "../../prose"

export const seamsAsServices = Prose.definePage({
  path: "/docs/learn/seams-as-services",
  title: "Seams as services",
  navTitle: "Seams as services",
  group: "Learn",
  description:
    "Four required services, roughly eleven optional seams discovered at run time, and a test layer for every one of them.",
  content: [
    Prose.p(
      "Batonfx has no plugin API. Every extension point is an Effect service, and a plugin is a ",
      Prose.code("Layer"),
      ". That one decision splits the framework's surface into two tiers: a small set of services a run cannot start without, and a larger set of optional seams the loop discovers at run time with ",
      Prose.code("Effect.serviceOption"),
      ".",
    ),
    Prose.h2("the-four-required-services", "The four required services"),
    Prose.p(
      "The requirement is written in the type. ",
      Prose.code("Agent.stream"),
      " needs ",
      Prose.code("RunServices"),
      ", a union of exactly four services:",
    ),
    Prose.table(
      ["Service", "What it decides", "Default when you have nothing to decide"],
      [
        [[Prose.code("Ai.LanguageModel.LanguageModel")], "Which model answers each turn", "None — always yours"],
        [
          [Prose.code("ToolExecutor.ToolExecutor")],
          "How tool calls execute",
          [Prose.code("fromToolkit"), " runs the toolkit's handlers in-process"],
        ],
        [
          [Prose.code("Approvals.Approvals")],
          ["Whether a ", Prose.code("needsApproval"), " tool may run"],
          [Prose.code("Approvals.autoApprove")],
        ],
        [
          [Prose.code("ModelMiddleware.ModelMiddleware")],
          "What transforms prompts and parts",
          [Prose.code("ModelMiddleware.identityLayer")],
        ],
      ],
    ),
    Prose.p(
      "Even an agent with no tools provides all four — the point is that the seams always exist, not that they always do something:",
    ),
    Prose.codeBlock({ label: "four-layers.ts", source: fourLayers, expectedOutput: fourLayersExpected }),
    Prose.h2("optional-seams", "Optional seams, discovered not demanded"),
    Prose.p(
      "Everything else is optional. At run start the loop probes for each seam with ",
      Prose.code("Effect.serviceOption"),
      " and takes the default path when the service is absent: ",
      Prose.code("Instructions"),
      ", ",
      Prose.code("SkillSource"),
      ", ",
      Prose.code("Permissions"),
      ", ",
      Prose.code("Steering"),
      ", ",
      Prose.code("Compaction"),
      ", ",
      Prose.code("Memory"),
      ", ",
      Prose.code("Session.SessionStore"),
      ", ",
      Prose.code("ModelResilience"),
      ", ",
      Prose.code("ToolOutputStore"),
      ", ",
      Prose.code("Ai.Chat.Persistence"),
      ", and ",
      Prose.code("Ai.Tokenizer.Tokenizer"),
      ".",
    ),
    Prose.p(
      "Absent means default — and default means the documented base behavior, exactly. No ",
      Prose.code("Permissions"),
      " layer means tools run under the ordinary approval path; no ",
      Prose.code("Compaction"),
      " means context is never rewritten; no ",
      Prose.code("Memory"),
      " means nothing is recalled or remembered. Your application pays for the seams it uses and never configures the ones it does not. The guides for ",
      Prose.link("/docs/guides/permissions", "permissions"),
      ", ",
      Prose.link("/docs/guides/memory", "memory"),
      ", and ",
      Prose.link("/docs/guides/compaction", "compaction"),
      " each show a single layer switching the behavior on.",
    ),
    Prose.h2("every-seam-ships-a-test-layer", "Every seam ships a test layer"),
    Prose.p(
      "A repository invariant backs the pattern: every behavior-bearing seam exposes a ",
      Prose.code("testLayer"),
      " or memory layer. ",
      Prose.code("ToolExecutor.testLayer"),
      " scripts tool outcomes, ",
      Prose.code("Approvals.testLayer"),
      " scripts decisions, ",
      Prose.code("Session.memoryLayer"),
      " keeps the event log in a ",
      Prose.code("Ref"),
      ", and a scripted ",
      Prose.code("Ai.LanguageModel.make"),
      " stands in for the model itself. Tests and CI evals swap implementations through layers alone — the run under test is the production code path with different providers, which is how ",
      Prose.link("/docs/guides/testing-evals", "agents are tested and evaled in CI"),
      " without an API key.",
    ),
    Prose.h2("why-this-makes-batonfx-embeddable", "Why this makes Batonfx embeddable"),
    Prose.p(
      "Because every seam is a service, a host can replace any of them without Batonfx importing host code. An in-process CLI provides four layers and is done. A durable runtime provides the same four plus durable implementations of the optional seams — a Postgres-backed ",
      Prose.code("SessionStore"),
      ", a blob-backed ",
      Prose.code("ToolOutputStore"),
      ", wait-backed approvals — and the loop cannot tell the difference. That swap is exactly how Relayfx hosts Batonfx, the subject of ",
      Prose.link("/docs/learn/baton-and-relay", "Batonfx and Relayfx: where durability lives"),
      ".",
    ),
  ],
})
