import fourLayers from "../../snippets/learn/seams-as-services/four-layers.ts?raw"
import fourLayersExpected from "../../snippets/learn/seams-as-services/four-layers.expected.txt?raw"
import { code, codeBlock, definePage, h2, link, p, table } from "../../prose"
export const seamsAsServices = definePage({
  path: "/docs/learn/seams-as-services",
  title: "Seams as services",
  navTitle: "Seams as services",
  group: "Learn",
  description:
    "One required model service, optional seams discovered at run time, and a test layer for every behavior-bearing seam.",
  content: [
    p(
      "Batonfx has no plugin API. Every extension point is an Effect service, and a plugin is a ",
      code("Layer"),
      ". That one decision splits the framework's surface into two tiers: the model service a run cannot start without, handler layers required by the tools you attach, and optional seams the loop discovers at run time with ",
      code("Effect.serviceOption"),
      ".",
    ),
    h2("the-required-service", "The required service"),
    p(
      "The requirement is written in the type. ",
      code("Agent.stream"),
      " always needs a ",
      code("LanguageModel"),
      " in context. Tool handler layers are required only for the toolkit calls the model can make:",
    ),
    table(
      ["Layer", "What it decides", "When you provide it"],
      [
        [[code("Ai.LanguageModel.LanguageModel")], "Which model answers each turn", "Always"],
        [
          [code("toolkit.toLayer({ ...handlers })")],
          "How in-process Effect AI tools execute",
          "When the agent advertises tools with local handlers",
        ],
        [
          [code("ToolExecutor.ToolExecutor")],
          "Where externally placed tools execute",
          "Only when overriding local toolkit handlers for durable waits, clients, remote workers, MCP, or sandboxes",
        ],
      ],
    ),
    p("An agent with no tools can run with only a model layer:"),
    codeBlock({ label: "four-layers.ts", source: fourLayers, expectedOutput: fourLayersExpected }),
    h2("optional-seams", "Optional seams, discovered not demanded"),
    p(
      "Everything else is optional. At run start the loop probes for each seam with ",
      code("Effect.serviceOption"),
      " and takes the default path when the service is absent: ",
      code("Instructions"),
      ", ",
      code("SkillSource"),
      ", ",
      code("Permissions"),
      ", ",
      code("Steering"),
      ", ",
      code("Compaction"),
      ", ",
      code("Memory"),
      ", ",
      code("Session.SessionStore"),
      ", ",
      code("ModelResilience"),
      ", ",
      code("ToolOutputStore"),
      ", ",
      code("Approvals"),
      ", ",
      code("ModelMiddleware"),
      ", ",
      code("Ai.Chat.Persistence"),
      ", and ",
      code("Ai.Tokenizer.Tokenizer"),
      ".",
    ),
    p(
      "Absent means default, and default means the documented base behavior, exactly. No ",
      code("Permissions"),
      " layer means tools run under the ordinary approval path; no ",
      code("Compaction"),
      " means context is never rewritten; no ",
      code("Memory"),
      " means nothing is recalled or remembered. Your application pays for the seams it uses and never configures the ones it does not. The guides for ",
      link("/docs/guides/permissions", "permissions"),
      ", ",
      link("/docs/guides/memory", "memory"),
      ", and ",
      link("/docs/guides/compaction", "compaction"),
      " each show a single layer switching the behavior on.",
    ),
    h2("every-seam-ships-a-test-layer", "Every seam ships a test layer"),
    p(
      "A repository invariant backs the pattern: every behavior-bearing seam exposes a ",
      code("testLayer"),
      " or memory layer. ",
      code("ToolExecutor.testLayer"),
      " scripts tool outcomes, ",
      code("Approvals.testLayer"),
      " scripts decisions, ",
      code("Session.memoryLayer"),
      " keeps the event log in a ",
      code("Ref"),
      ", and a scripted ",
      code("Ai.LanguageModel.make"),
      " stands in for the model itself. Tests and CI evals swap implementations through layers alone: the run under test is the production code path with different providers, which is how ",
      link("/docs/guides/testing-evals", "agents are tested and evaled in CI"),
      " without an API key.",
    ),
    h2("why-this-makes-batonfx-embeddable", "Why this makes Batonfx embeddable"),
    p(
      "Because every seam is a service, a host can replace any of them without Batonfx importing host code. An in-process CLI provides a model and the handler layers for its local tools. A durable runtime provides the same model/tool surface plus durable implementations of optional seams (a Postgres-backed ",
      code("SessionStore"),
      ", a blob-backed ",
      code("ToolOutputStore"),
      ", wait-backed approvals) and the loop cannot tell the difference. That swap is exactly how Relayfx hosts Batonfx, the subject of ",
      link("/docs/learn/baton-and-relay", "Batonfx and Relayfx: where durability lives"),
      ".",
    ),
  ],
})
