import projection from "../../snippets/learn/sessions-and-history/projection.ts?raw"
import projectionExpected from "../../snippets/learn/sessions-and-history/projection.expected.txt?raw"
import * as Prose from "../../prose"

export const sessionsAndHistory = Prose.definePage({
  path: "/docs/learn/sessions-and-history",
  title: "Sessions, history, and persistence",
  navTitle: "Sessions & history",
  group: "Learn",
  description:
    "The append-only session entry log, buildContext as a pure projection, and the three ways a run can carry history.",
  content: [
    Prose.p(
      "Batonfx separates two ideas that most frameworks fuse: the record of a conversation, and the context a model sees. The record is an append-only log; the context is a pure function of a path through it. This page explains the ",
      Prose.code("Session"),
      " seam and the three ways a run can carry history at all.",
    ),
    Prose.h2("an-append-only-log", "An append-only log with a leaf pointer"),
    Prose.p(
      "A session is a log of entries plus a mutable current-leaf pointer. The entry union is closed at three members: ",
      Prose.code("Message"),
      " stores one ",
      Prose.code("Ai.Prompt.Message"),
      " verbatim; ",
      Prose.code("Compaction"),
      " stores a summary and a ",
      Prose.code("firstKeptEntryId"),
      " marking where verbatim history resumes; ",
      Prose.code("BranchSummary"),
      " stores a digest of an abandoned branch. Each entry has an id and a ",
      Prose.code("parentId"),
      ", so the log is a tree. Nothing is ever rewritten or deleted — branching means moving the leaf pointer and appending a new child, and the ",
      Prose.code("SessionStore"),
      " service (",
      Prose.code("append"),
      ", ",
      Prose.code("path"),
      ", ",
      Prose.code("setLeaf"),
      ", ",
      Prose.code("leaf"),
      ") is the entire boundary.",
    ),
    Prose.h2("context-is-a-projection", "Context is a projection, not a copy"),
    Prose.p(
      "The prompt the model sees is never stored separately. ",
      Prose.code("Session.buildContext(path)"),
      " purely projects a root-to-leaf path into an ",
      Prose.code("Ai.Prompt.Prompt"),
      ": messages project verbatim, branch summaries become system notes, and the last compaction on the path wins — it emits one checkpoint message and then only entries from ",
      Prose.code("firstKeptEntryId"),
      " onward. Compaction is lossless in the log and lossy only in the projection:",
    ),
    Prose.codeBlock({ label: "projection.ts", source: projection, expectedOutput: projectionExpected }),
    Prose.p(
      "After the compaction entry the projected context shrinks to a checkpoint plus the kept tail, while the log still holds all five entries. Rewinding is moving the leaf; auditing is reading the log; shrinking context is appending an entry. ",
      Prose.link("/docs/guides/compaction", "How to stay inside the context window"),
      " covers the strategy that decides when Batonfx appends one for you.",
    ),
    Prose.h2("three-ways-to-carry-history", "Three ways a run carries history"),
    Prose.p("A run can be given its past in three mutually independent ways, each fitting a different owner:"),
    Prose.table(
      ["Run option", "Mechanism", "Use it when"],
      [
        [
          [Prose.code("history")],
          "The prior transcript is used verbatim as the initial chat, no system message prepended",
          "The host already owns transcript storage — resuming after suspension, replaying an exported transcript",
        ],
        [
          [Prose.code("persistence.chatId")],
          [
            "The loop runs on a persisted ",
            Prose.code("Ai.Chat"),
            " via ",
            Prose.code("Chat.layerPersisted"),
            "; history accumulates across runs under one id",
          ],
          "You want multi-run conversations with storage delegated to an upstream persistence layer",
        ],
        [
          [Prose.code("SessionStore"), " seam"],
          ["The structured entry log above; the loop wires it in when ", Prose.code("Compaction"), " is also present"],
          "You need branchable, auditable history with compaction checkpoints recorded as entries",
        ],
      ],
    ),
    Prose.p(
      Prose.code("history"),
      " and ",
      Prose.code("persistence.chatId"),
      " are mutually exclusive on one run — verbatim history and accumulated chat state would fight over the same seat. The full ",
      Prose.code("RunOptions"),
      " field table lives in ",
      Prose.link("/docs/reference/core-agent", "Agent and run functions"),
      ", and the session contract in ",
      Prose.link("/docs/reference/core-context", "Context seams"),
      ".",
    ),
    Prose.h2("where-durable-history-lives", "Where durable history lives"),
    Prose.p(
      "Everything on this page is non-durable by design: ",
      Prose.code("Session.memoryLayer"),
      " is a ",
      Prose.code("Ref"),
      ", and the persisted-chat layer in the examples backs onto memory too. Durable, addressable conversation storage belongs to the host — a durable runtime implements ",
      Prose.code("SessionStore"),
      " over its own database and provides it as a layer, which is exactly what Relayfx does. Why that split exists is the subject of ",
      Prose.link("/docs/learn/baton-and-relay", "Batonfx and Relayfx: where durability lives"),
      ".",
    ),
  ],
})
