import projection from "../../snippets/learn/sessions-and-history/projection.ts?raw"
import projectionExpected from "../../snippets/learn/sessions-and-history/projection.expected.txt?raw"
import { code, codeBlock, definePage, h2, link, p, table } from "../../prose"
export const sessionsAndHistory = definePage({
  path: "/docs/learn/sessions-and-history",
  title: "Sessions, history, and persistence",
  navTitle: "Sessions & history",
  group: "Learn",
  description:
    "The append-only session entry log, Effect AI prompt projection, and the three ways a run can carry history.",
  content: [
    p(
      "Batonfx separates two ideas that most frameworks fuse: the record of a conversation, and the context a model sees. The record is an append-only log; the context is a pure function of a path through it. This page explains the ",
      code("Session"),
      " seam and the three ways a run can carry history at all.",
    ),
    h2("an-append-only-log", "An append-only log with a leaf pointer"),
    p(
      "A session is a log of entries plus a mutable current-leaf pointer. The entry union is closed and prompt-native: ",
      code("Message"),
      " stores one ",
      code("Ai.Prompt.Message"),
      " verbatim; ",
      code("ToolCall"),
      " and ",
      code("ToolResult"),
      " store Effect AI tool-call and result parts without inventing another wire shape; ",
      code("Memory"),
      ", ",
      code("Skill"),
      ", ",
      code("Steering"),
      ", and ",
      code("Handoff"),
      " record the context seams robust agents need; ",
      code("Compaction"),
      " version 2 stores the exact projected history used by live Chat, while legacy entries retain summary and ",
      code("firstKeptEntryId"),
      " decoding; ",
      code("BranchSummary"),
      " stores a digest of an abandoned branch. Each entry has an id and a ",
      code("parentId"),
      ", so the log is a tree. Nothing is ever rewritten or deleted: branching means moving the leaf pointer and appending a new child, and the ",
      code("SessionStore"),
      " service (",
      code("append"),
      ", ",
      code("appendCheckpoint"),
      ", ",
      code("path"),
      ", ",
      code("setLeaf"),
      ", ",
      code("leaf"),
      ") is the entire boundary.",
    ),
    h2("context-is-a-projection", "Context is a projection, not a copy"),
    p(
      "The prompt the model sees is never stored separately. ",
      code("Session.buildContext(path)"),
      " purely projects a root-to-leaf path into an ",
      code("Ai.Prompt.Prompt"),
      ": prompt-native entries keep their roles and parts, context notes become tagged system messages, and the last compaction on the path wins. Version 2 uses its exact stored projection followed by later entries; legacy checkpoints emit a summary and continue from ",
      code("firstKeptEntryId"),
      ". Compaction is lossless in the log and lossy only in the projection:",
    ),
    codeBlock({ label: "projection.ts", source: projection, expectedOutput: projectionExpected }),
    p(
      "After the compaction entry the projected context shrinks to a checkpoint plus the kept tail, while the log still holds all five entries. Rewinding is moving the leaf; auditing is reading the log; shrinking context is appending an entry. ",
      link("/docs/guides/compaction", "How to stay inside the context window"),
      " covers the strategy that decides when Batonfx appends one for you.",
    ),
    h2("three-ways-to-carry-history", "Three ways a run carries history"),
    p("A run can be given its past in three mutually independent ways, each fitting a different owner:"),
    table(
      ["Run option", "Mechanism", "Use it when"],
      [
        [
          [code("history")],
          "The prior transcript is used verbatim as the initial chat, no system message prepended",
          "The host already owns transcript storage: resuming after suspension, replaying an exported transcript",
        ],
        [
          [code("persistence.chatId")],
          [
            "The loop runs on a persisted ",
            code("Ai.Chat"),
            " via ",
            code("Chat.layerPersisted"),
            "; history accumulates across runs under one id",
          ],
          "You want multi-run conversations with storage delegated to an upstream persistence layer",
        ],
        [
          [code("SessionStore"), " seam"],
          ["The structured entry log above; the loop wires it in when ", code("Compaction"), " is also present"],
          "You need branchable, auditable history with compaction checkpoints recorded as entries",
        ],
      ],
    ),
    p(
      code("history"),
      " uses an ordinary run while ",
      code("persistence.chatId"),
      " sets persistence on the same run entrypoint. Both are fields of the same option type; choose the history owner that fits the host. The full ",
      code("RunOptions"),
      " field table lives in ",
      link("/docs/reference/core-agent", "Agent and run functions"),
      ", and the session contract in ",
      link("/docs/reference/core-context", "Context seams"),
      ".",
    ),
    h2("where-durable-history-lives", "Where durable history lives"),
    p(
      "Everything on this page is non-durable by design: ",
      code("Session.layerMemory"),
      " is a ",
      code("Ref"),
      ", and the persisted-chat layer in the examples backs onto memory too. Durable, addressable conversation storage belongs to the host: a durable runtime implements ",
      code("SessionStore"),
      " over its own database and provides it as a layer, which is exactly what Relayfx does. Why that split exists is the subject of ",
      link("/docs/learn/baton-and-relay", "Batonfx and Relayfx: where durability lives"),
      ".",
    ),
  ],
})
