import suspendAndResume from "virtual:source/src/snippets/learn/suspension/suspend-and-resume.ts"
import suspendAndResumeExpected from "virtual:source/src/snippets/learn/suspension/suspend-and-resume.expected.txt"
import { code, codeBlock, definePage, h2, link, p, table } from "../../prose"
export const suspension = definePage({
  path: "/docs/learn/suspension",
  title: "Suspension as a typed error",
  navTitle: "Suspension",
  group: "Learn",
  description:
    "AgentSuspended on the error channel is the human-in-the-loop contract: the host stores a token and re-enters the run with RunOptions.resume.",
  content: [
    p(
      "Suspension is not failure handling. It is the human-in-the-loop contract: a typed statement that the run did not finish and must be re-entered once someone (a person, an external system, a durable runtime) resolves a token out-of-band. Generalist puts that statement on the stream's error channel as ",
      code("AgentSuspended"),
      ".",
    ),
    h2("the-shape", "A typed error with a deliberate shape"),
    p("The error carries five fields:"),
    table(
      ["Field", "Meaning"],
      [
        [[code("token")], "Opaque handle the host resolves out-of-band"],
        [
          [code("reason")],
          [
            code('"approval"'),
            " from an Approvals ",
            code("Pending"),
            " decision, or ",
            code('"tool-wait"'),
            " from a ToolExecutor ",
            code("Suspend"),
            " outcome",
          ],
        ],
        [[code("tool_call_id")], "Id of the pending tool call"],
        [[code("tool_name")], "Name of the pending tool"],
        [[code("tool_params")], "Params of the pending tool call"],
      ],
    ),
    p(
      "There are exactly two producers. ",
      code("Approvals.resolve"),
      " returning ",
      code("Pending"),
      " suspends a ",
      code("needsApproval"),
      " tool before it executes; ",
      code("ToolExecutor.execute"),
      " returning ",
      code("Suspend"),
      " parks a call whose result will arrive later. A ",
      link("/docs/guides/permissions", "permission rule"),
      " that asks and gets no in-process answer suspends through the same ",
      code('"approval"'),
      " path.",
    ),
    h2("suspend-resolve-resume", "Suspend, resolve, resume"),
    p(
      "The host's job is three steps: catch ",
      code("AgentSuspended"),
      ", store the token and the transcript, and later re-enter the run with ",
      code("RunOptions.resume"),
      " carrying the pending call. This run suspends on an approval and resumes to completion, with zero credentials:",
    ),
    codeBlock({
      label: "suspend-and-resume.ts",
      source: suspendAndResume,
      expectedOutput: suspendAndResumeExpected,
    }),
    p(
      "Three details of the re-entry contract are visible here. First, just before failing, the stream emits a trailing ",
      code("TurnCompleted"),
      " whose transcript includes the suspending turn; that is what the snippet stores and passes back as ",
      code("history"),
      ". Second, the resumed run executes the pending call first, before any model call, then re-feeds its result and continues under the normal turn policy. Third, gates are consulted again on re-entry: the ",
      code("Approvals"),
      " layer answers ",
      code("Approved"),
      " the second time because the host has resolved the token, which is exactly how a real host answers from its own approval record.",
    ),
    h2("why-the-shape-mirrors-a-tool-call", "Why the shape mirrors a tool call"),
    p(
      "The field shape (id, name, params) is deliberately the shape of a tool call, because that is what a durable host must persist to re-enter later. Store those three fields plus the token and the transcript, and a resume days later reconstructs the exact call identity the model emitted. generalist/runtime persists that suspension as a durable Run wait and applies its resolution to the authoritative core suspension on re-entry; see ",
      link("/docs/learn/native-runtime", "where durability lives"),
      ". generalist defines the suspension contract but does not persist it.",
    ),
    h2("why-an-error-and-not-a-callback", "Why an error and not a callback"),
    p(
      "A callback-based pause lives outside the type system: nothing forces you to handle it, and it composes poorly with scopes and interruption. A typed error on the ",
      code("RunError"),
      " channel composes with everything Effect already gives you: ",
      code("catchIf"),
      " and ",
      code("catchTag"),
      ", scoped resource cleanup on the way out, interruption, and retry combinators. A suspension tears the run down cleanly through ordinary error propagation, which is what makes it safe to resume from a different process entirely. For approvals over a live connection, where the wire carries the token to a browser and back, see ",
      link("/docs/guides/approvals", "How to require human approval"),
      " and ",
      link("/docs/guides/serve-transport", "How to serve an agent over SSE and WebSocket"),
      ".",
    ),
  ],
})
