import chatEntry from "virtual:source/src/snippets/guides/runtime/foldkit-chat/entry.ts"
import chatModel from "virtual:source/src/snippets/guides/runtime/foldkit-chat/model.ts"
import chatView from "virtual:source/src/snippets/guides/runtime/foldkit-chat/view.ts"
import { bullets, callout, code, codeBlock, command, definePage, h2, link, p } from "../../../prose"
export const foldkitChat = definePage({
  path: "/docs/guides/foldkit-chat",
  title: "How to build a chat UI with FoldKit",
  navTitle: "Build a FoldKit chat UI",
  group: "Guides",
  description:
    "Embed the headless Chat submodel in a FoldKit application, observe semantic RunEvents, and render committed entries, run state, and approvals.",
  content: [
    p(
      code("generalist/foldkit"),
      " adapts transport frames into FoldKit's Elm architecture. ",
      code("Connection.Connection"),
      " is a long-lived resource that observes decoded durable RunEvent frames and connection facts; ",
      code("Chat"),
      " is a headless submodel with a pure ",
      code("update"),
      " that projects those frames into display state. It ships no styled components; rendering stays yours.",
    ),
    command("Terminal", "bun add effect@4.0.0-rc.112 generalist@0.44.0 foldkit@0.148.2"),
    h2("embed-the-chat-model", "1. Open a session and embed the chat model"),
    p(
      "Embed ",
      code("Chat.Model"),
      " in the application model and route every ",
      code("Chat.Action"),
      " through one wrapper action. The host owns session creation: a command POSTs to the server from ",
      link("/docs/guides/serve-transport", "the transport guide"),
      ", then dispatches ",
      code("Chat.OpenedSession"),
      ", which selects the session and lets the subscription attach. ",
      code("Subscription.lift"),
      " keeps the frame stream alive across model changes and restarts it only when the session id changes.",
    ),
    codeBlock({ label: "model.ts", source: chatModel }),
    callout(
      "info",
      "Replay is idempotent",
      "Chat.update drops any frame with ",
      code("seq <= lastSeq"),
      " without changing state, so reconnect replays and duplicate deliveries are harmless by construction.",
    ),
    h2("render-the-chat", "2. Render semantic entries, run state, and the approval moment"),
    p(
      "The model gives the view its durable projection as data: ",
      code("entries"),
      " holds user rows plus assistant and tool rows projected from normalized model-response and tool-execution events; ",
      code("draft"),
      " holds the input, and ",
      code("run"),
      " reports ",
      code("Idle"),
      ", ",
      code("Running"),
      ", ",
      code("AwaitingApproval"),
      ", or ",
      code("Failed"),
      ". There is no ",
      code("Chat.Model.streaming"),
      " field: Chat never treats replayable events as provider-fragment authority. When ",
      code("run"),
      " is ",
      code("AwaitingApproval"),
      ", render approve and deny controls that dispatch ",
      code("Chat.ClickedApprove"),
      " and ",
      code("Chat.ClickedDeny"),
      ". The submodel already carries the token.",
    ),
    codeBlock({ label: "view.ts", source: chatView }),
    callout(
      "info",
      "Live previews are a separate observer",
      code("Runtime.previews"),
      " can expose bounded append frames for text and reasoning inside the Runtime process, but those frames are lossy, droppable, and absent from transport replay and Chat.Model. A host that chooses to bridge previews to a browser owns a separate route, model field, sequence-gap policy, and stale-preview cleanup policy.",
    ),
    p(
      "For richer rendering, ",
      code("Chat.conversationItems"),
      ", ",
      code("Chat.promptInputStatusOf"),
      ", and ",
      code("Chat.toolStatusOf"),
      " map the model to foldcn-aligned view data; that is what ",
      link(
        "https://github.com/In-Time-Tec/generalist/blob/main/examples/deep-research-agent/web/src/main.ts",
        "the deep-research web app",
      ),
      " renders with styled components. A generic waiting item may indicate that the run is active, but it must not fabricate assistant text before a semantic response event arrives.",
    ),
    h2("wire-the-websocket-resource", "3. Wire the WebSocket resource and run"),
    p(
      code("Connection.layerWebSocket"),
      " composes the transport client and needs a WebSocket constructor; in the browser that is ",
      code("Socket.layerWebSocketConstructorGlobal"),
      ". Provide it through the application's static ",
      code("resources"),
      ".",
    ),
    codeBlock({ label: "entry.ts", source: chatEntry }),
    h2("connection-states", "4. Handle reconnection states"),
    bullets(
      [
        "The transport client reconnects with bounded exponential backoff and re-attaches with the last seen ",
        code("seq"),
        ", so a dropped socket resumes where it left off.",
      ],
      [
        "Connection facts fold into the same action stream: ",
        code("model.connection"),
        " moves through ",
        code("connecting"),
        ", ",
        code("open"),
        ", ",
        code("reconnecting"),
        ", and ",
        code("disconnected"),
        ". Render it as a status badge.",
      ],
      [
        "Send failures never vanish: every command converts them into ",
        code("FailedAgentCommand"),
        ", which the update folds into a ",
        code("Failed"),
        " run state.",
      ],
    ),
    p(
      "The full model, action, output, and helper tables are in ",
      link("/docs/reference/foldkit", "the generalist/foldkit reference"),
      ". To build the server side of this page, start at ",
      link("/docs/start/research-agent", "the research-agent tutorial"),
      ".",
    ),
  ],
})
