import amazonBedrock from "virtual:source/src/snippets/guides/runtime/providers/amazon-bedrock.ts"
import combineProviders from "virtual:source/src/snippets/guides/runtime/providers/combine-providers.ts"
import deterministicLayer from "virtual:source/src/snippets/guides/runtime/providers/deterministic-layer.ts"
import deterministicLayerExpected from "virtual:source/src/snippets/guides/runtime/providers/deterministic-layer.expected.txt"
import geminiOpenaiCompat from "virtual:source/src/snippets/guides/runtime/providers/gemini-openai-compat.ts"
import layerFirst from "virtual:source/src/snippets/guides/runtime/providers/layer-first.ts"
import openaiOrDeterministic from "virtual:source/src/snippets/guides/runtime/providers/openai-or-deterministic.ts"
import openaiCompatible from "virtual:source/src/snippets/guides/runtime/providers/openai-compatible.ts"
import openrouter from "virtual:source/src/snippets/guides/runtime/providers/openrouter.ts"
import { callout, code, codeBlock, command, definePage, h2, link, p, table } from "../../../prose"
export const providers = definePage({
  path: "/docs/guides/providers",
  title: "How to provide model providers",
  navTitle: "Provide model providers",
  group: "Guides",
  description:
    "Provide a model layer directly to a run with layerModel, combine provider clients, and keep a deterministic layer for keyless environments.",
  content: [
    p(
      code("generalist"),
      " is provider-agnostic. The default wiring is two layers: a provider client layer (",
      code("layerConfig"),
      ") and a thin model layer over it (",
      code("layerModel"),
      "). Provide the model layer to a run with ",
      code("Effect.provide"),
      " — no registry, no selection strings. ",
      code("generalist/providers/*"),
      " leaves wrap the upstream ",
      code("@effect/ai-*"),
      " packages with failure classification, image-source handling, and tool-schema compilation baked in.",
    ),
    command("OpenAI profile", "bun add effect@4.0.0-rc.112 generalist@0.45.1 @effect/ai-openai@4.0.0-rc.112"),
    p(
      "Install only the peer for each provider leaf you import. Anthropic uses ",
      code("@effect/ai-anthropic@4.0.0-rc.112"),
      "; OpenAI, OpenAI Responses, and OpenAI embedding use ",
      code("@effect/ai-openai@4.0.0-rc.112"),
      "; OpenAI Chat Completions, compatible presets, and compatible embedding use ",
      code("@effect/ai-openai-compat@4.0.0-rc.112"),
      ". Amazon Bedrock uses ",
      code("@aws-sdk/client-bedrock-runtime@3.859.0"),
      ", ",
      code("@aws-sdk/credential-provider-node@3.859.0"),
      ", and ",
      code("@smithy/types@4.3.1"),
      " and is tested as a Node 22+ profile. The deterministic, model-catalog, and model-route leaves need no provider peer.",
    ),
    h2("provide-a-model", "1. Provide a model layer to a run"),
    p(
      "Every provider exports ",
      code("layerConfig(options)"),
      " for the client and ",
      code("layerModel({ model })"),
      " for one model over that client. The model layer also carries ",
      code("ProviderName"),
      " and ",
      code("ModelName"),
      " tags, so telemetry names the exact model. The client layer requires a host ",
      code("HttpClient"),
      " — compose ",
      code("FetchHttpClient.layer"),
      " explicitly, or provide a tracing, proxy, or test client instead. Credentials come from Effect ",
      code("Config"),
      ", never from string literals.",
    ),
    codeBlock({ label: "layer-first.ts", source: layerFirst }),
    p(
      "To change the model, provide a different model layer. To change the provider for that model, provide a different client layer under it. To give one child agent a different model, pass the model layer as the ",
      code("model"),
      " option of ",
      code("AgentTool.asTool"),
      " or ",
      code("Handoff.target"),
      " — children without one inherit the ambient model. See ",
      link("/docs/guides/multi-agent", "the multi-agent guide"),
      ".",
    ),
    h2("keep-ci-keyless", "2. Keep CI keyless with the deterministic model"),
    p(
      "The deterministic model layer always answers ",
      code("deterministic response"),
      " and needs no client or credentials, which makes it the model for CI evals and local development:",
    ),
    codeBlock({
      label: "deterministic-layer.ts",
      source: deterministicLayer,
      expectedOutput: deterministicLayerExpected,
    }),
    p(
      code("layerOrDeterministic"),
      " from the OpenAI leaf builds a registry that installs the deterministic fallback always and OpenAI only when its API-key config is present, for environments that select by configuration. Missing key data selects deterministic-only registration; invalid values and configuration-source failures remain typed failures.",
    ),
    codeBlock({ label: "openai-or-deterministic.ts", source: openaiOrDeterministic }),
    h2("dynamic-selection", "3. Select dynamically with ModelRegistry"),
    p(
      "When the model is genuinely runtime data — chosen per request from a database row or a user setting — use ",
      code("ModelRegistry"),
      ". A provider's ",
      code("layer(config)"),
      " constructor registers one ",
      code("{ provider, model, registrationKey? }"),
      " identity instead of providing a model directly, and ",
      code("ModelRegistry.withModel(selection, effect)"),
      " resolves that identity to its ",
      code("LanguageModel"),
      " for exactly that effect, failing with a typed ",
      code("LanguageModelNotRegistered"),
      " when the selection is missing.",
    ),
    codeBlock({ label: "openrouter.ts", source: openrouter }),
    callout(
      "warning",
      "The registry is not a model",
      "A provider registry layer provides ",
      code("ModelRegistry.ModelRegistry"),
      ", not ",
      code("Ai.LanguageModel"),
      ". Providing it where a run expects a language model fails with a missing-service error, so always pair it with ",
      code("ModelRegistry.withModel"),
      ". Prefer ",
      code("layerModel"),
      " whenever the model is known at construction.",
    ),
    h2("combine-several-providers", "4. Combine several providers"),
    p(
      "Model layers compose with plain ",
      code("Effect.provide"),
      " scoping — the closest provide wins, so no combination helper is needed. Registries are different: every provider registry layer installs its own fresh registry under the same service tag, so ",
      code("Layer.mergeAll"),
      " keeps only one provider's registrations. Combine registries with ",
      code("ModelRegistry.layerMerged"),
      "; on identical identity the later layer wins.",
    ),
    codeBlock({ label: "combine-providers.ts", source: combineProviders }),
    h2("openai-compatible", "5. Connect an OpenAI-compatible endpoint"),
    p(
      "Choose the adapter for the protocol the endpoint implements: ",
      code("OpenAIResponses.layer"),
      " posts to ",
      code("/responses"),
      ", while ",
      code("OpenAIChatCompletions.layer"),
      " posts to ",
      code("/chat/completions"),
      ". Both accept a custom ",
      code("provider"),
      ", ",
      code("model"),
      ", ",
      code("baseUrl"),
      ", optional API key, provider configuration, registration key, and metadata. The provider string becomes part of the exact registry selection; it does not need to name a built-in provider.",
    ),
    codeBlock({ label: "openai-compatible.ts", source: openaiCompatible }),
    h2("amazon-bedrock", "6. Register Amazon Bedrock"),
    p(
      code("AmazonBedrock.layer"),
      " accepts any Bedrock foundation-model ID, inference-profile ID, or ARN. Its client uses the AWS SDK credential chain, so environment credentials, shared profiles and roles, SSO or AWS CLI caches, credential processes, web identity, ECS, and IMDS work without copying credentials into registration data. Set ",
      code("region"),
      " and optionally ",
      code("profile"),
      "; bearer-token authentication is also available through ",
      code("AWS_BEARER_TOKEN_BEDROCK"),
      " or an explicitly redacted ",
      code("bearerToken"),
      ".",
    ),
    codeBlock({ label: "amazon-bedrock.ts", source: amazonBedrock }),
    h2("openai-compatible-presets", "7. Pick an OpenAI-compatible preset"),
    p(
      "OpenAICompatible are thin wrappers over ",
      code("OpenAIChatCompletions.layer"),
      " that fix the provider name and base URL. Each preset constructor returns a registry layer requiring a host HttpClient; compose FetchHttpClient.layer explicitly when selecting fetch.",
    ),
    table(
      ["Preset", "Provider", "Base URL"],
      [
        [[code("OpenAICompatible.layerGroq")], [code("groq")], [code("https://api.groq.com/openai/v1")]],
        [[code("OpenAICompatible.layerMistral")], [code("mistral")], [code("https://api.mistral.ai/v1")]],
        [[code("OpenAICompatible.layerXAI")], [code("xai")], [code("https://api.x.ai/v1")]],
        [[code("OpenAICompatible.layerDeepSeek")], [code("deepseek")], [code("https://api.deepseek.com/v1")]],
        [
          [code("OpenAICompatible.layerGoogleAIStudio")],
          [code("google")],
          [code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [
          [code("OpenAICompatible.layerAzureOpenAI")],
          [code("azure")],
          [code("https://{resource}.openai.azure.com/openai/v1")],
        ],
        [[code("OpenAICompatible.layerOllama")], [code("ollama")], [code("http://localhost:11434/v1")]],
      ],
    ),
    h2("recipe-gemini", "Recipe: Gemini via the OpenAI-compatible preset"),
    p(
      "Generalist has no first-party Google helper yet because the upstream Effect AI Google provider is not compatible with the pinned beta, but Google AI Studio speaks the OpenAI protocol. Register it with the ",
      code("layerGoogleAIStudio"),
      " preset and select ",
      code('{ provider: "google", model: "gemini-2.0-flash" }'),
      ".",
    ),
    codeBlock({ label: "gemini-openai-compat.ts", source: geminiOpenaiCompat }),
    p(
      "For context windows and pricing of models reached through presets, pass overrides to the offline ",
      code("ModelCatalog.layer"),
      ". The full export map is in ",
      link("/docs/reference/providers", "the provider-leaf reference"),
      ". To pin loop behavior without any provider at all, see ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
