import amazonBedrock from "virtual:source/src/snippets/guides/runtime/providers/amazon-bedrock.ts"
import combineProviders from "virtual:source/src/snippets/guides/runtime/providers/combine-providers.ts"
import deterministicRegistry from "virtual:source/src/snippets/guides/runtime/providers/deterministic-registry.ts"
import deterministicRegistryExpected from "virtual:source/src/snippets/guides/runtime/providers/deterministic-registry.expected.txt"
import geminiOpenaiCompat from "virtual:source/src/snippets/guides/runtime/providers/gemini-openai-compat.ts"
import openaiOrDeterministic from "virtual:source/src/snippets/guides/runtime/providers/openai-or-deterministic.ts"
import openaiCompatible from "virtual:source/src/snippets/guides/runtime/providers/openai-compatible.ts"
import openrouter from "virtual:source/src/snippets/guides/runtime/providers/openrouter.ts"
import { callout, code, codeBlock, command, definePage, h2, link, p, table } from "../../../prose"
export const providers = definePage({
  path: "/docs/guides/providers",
  title: "How to register real model providers",
  navTitle: "Register model providers",
  group: "Guides",
  description:
    "Bind provider and model pairs from exact tenetkit/ai/* leaves, combine registries, and keep a deterministic fallback for keyless environments.",
  content: [
    p(
      code("tenetkit"),
      " is provider-agnostic: ",
      code("ModelRegistry"),
      " maps a ",
      code("{ provider, model, registrationKey? }"),
      " selection to an Effect AI ",
      code("LanguageModel"),
      " layer and fails with a typed ",
      code("LanguageModelNotRegistered"),
      " when the selection is missing. ",
      code("tenetkit/ai/*"),
      " leaves add registration helpers over the upstream ",
      code("@effect/ai-*"),
      " packages.",
    ),
    command("OpenRouter profile", "bun add effect@4.0.0-rc.112 tenetkit@0.44.0 @effect/ai-openrouter@4.0.0-rc.112"),
    p(
      "Install only the peer for each provider leaf you import. Anthropic uses ",
      code("@effect/ai-anthropic@4.0.0-rc.112"),
      "; OpenAI, OpenAI Responses, and OpenAI embedding use ",
      code("@effect/ai-openai@4.0.0-rc.112"),
      "; OpenAI Chat Completions, compatible presets, and compatible embedding use ",
      code("@effect/ai-openai-compat@4.0.0-rc.112"),
      ". Amazon Bedrock uses ",
      code("@aws-sdk/client-bedrock-runtime@3.859.0"),
      ", ",
      code("@aws-sdk/credential-provider-node@3.859.0"),
      ", and ",
      code("@smithy/types@4.3.1"),
      " and is tested as a Node 22+ profile. The deterministic, model-catalog, and model-route leaves need no provider peer.",
    ),
    h2("register-one-provider", "1. Register a provider"),
    p(
      "Each provider module ships one ",
      code("layer(config)"),
      " constructor that composes the registration and upstream client while requiring a host ",
      code("HttpClient"),
      ". This lets applications provide tracing, proxy, test, or platform clients. Applications choosing the global fetch transport explicitly compose ",
      code("FetchHttpClient.layer"),
      ". Credentials come from Effect ",
      code("Config"),
      ", never from string literals. Wrap the run in ",
      code("ModelRegistry.withModel(selection, effect)"),
      ": that call looks up the registration and supplies its ",
      code("LanguageModel"),
      " layer for exactly that run.",
    ),
    codeBlock({ label: "openrouter.ts", source: openrouter }),
    callout(
      "warning",
      "The registry is not a model",
      "A provider layer provides ",
      code("ModelRegistry.ModelRegistry"),
      ", not ",
      code("Ai.LanguageModel"),
      ". Providing it where a run expects a language model fails with a missing-service error, so always pair it with ",
      code("ModelRegistry.withModel"),
      ".",
    ),
    h2("combine-several-providers", "2. Combine several providers"),
    p(
      "Every provider layer installs its own fresh registry under the same service tag, so ",
      code("Layer.mergeAll"),
      " keeps only one provider's registrations. Combine registries with ",
      code("ModelRegistry.layerMerged"),
      " instead; on identical identity the later layer wins.",
    ),
    codeBlock({ label: "combine-providers.ts", source: combineProviders }),
    h2("keep-ci-keyless", "3. Keep CI keyless with the deterministic registration"),
    p(
      "The deterministic registration is a local ",
      code("LanguageModel"),
      " that always answers ",
      code("deterministic response"),
      ". It runs with no credentials, which makes it the model for CI evals and local development.",
    ),
    codeBlock({
      label: "deterministic-registry.ts",
      source: deterministicRegistry,
      expectedOutput: deterministicRegistryExpected,
    }),
    p(
      code("layerOrDeterministic"),
      " installs the deterministic fallback always and OpenAI only when its API-key config is present. Missing key data selects deterministic-only registration; invalid values and configuration-source failures remain typed failures. The selection stays data, so each environment picks its own pair.",
    ),
    codeBlock({ label: "openai-or-deterministic.ts", source: openaiOrDeterministic }),
    p(
      "For a single-agent server that needs a plain ",
      code("LanguageModel"),
      " layer rather than a registry, the deep-research example builds the same fallback at the model-layer level; see ",
      link(
        "https://github.com/In-Time-Tec/tenetkit/blob/main/examples/deep-research-agent/server/src/model.ts",
        "layerOrDeterministic in examples/deep-research-agent",
      ),
      ".",
    ),
    h2("openai-compatible", "4. Connect an OpenAI-compatible endpoint"),
    p(
      "Choose the adapter for the protocol the endpoint implements: ",
      code("OpenAIResponses.layer"),
      " posts to ",
      code("/responses"),
      ", while ",
      code("OpenAIChatCompletions.layer"),
      " posts to ",
      code("/chat/completions"),
      ". Both accept a custom ",
      code("provider"),
      ", ",
      code("model"),
      ", ",
      code("baseUrl"),
      ", optional API key, provider configuration, registration key, and metadata. The provider string becomes part of the exact registry selection; it does not need to name a built-in provider.",
    ),
    codeBlock({ label: "openai-compatible.ts", source: openaiCompatible }),
    h2("amazon-bedrock", "5. Register Amazon Bedrock"),
    p(
      code("AmazonBedrock.layer"),
      " accepts any Bedrock foundation-model ID, inference-profile ID, or ARN. Its client uses the AWS SDK credential chain, so environment credentials, shared profiles and roles, SSO or AWS CLI caches, credential processes, web identity, ECS, and IMDS work without copying credentials into registration data. Set ",
      code("region"),
      " and optionally ",
      code("profile"),
      "; bearer-token authentication is also available through ",
      code("AWS_BEARER_TOKEN_BEDROCK"),
      " or an explicitly redacted ",
      code("bearerToken"),
      ".",
    ),
    codeBlock({ label: "amazon-bedrock.ts", source: amazonBedrock }),
    h2("openai-compatible-presets", "6. Pick an OpenAI-compatible preset"),
    p(
      "OpenAICompatible are thin wrappers over ",
      code("OpenAIChatCompletions.layer"),
      " that fix the provider name and base URL. Each preset constructor returns a registry layer requiring a host HttpClient; compose FetchHttpClient.layer explicitly when selecting fetch.",
    ),
    table(
      ["Preset", "Provider", "Base URL"],
      [
        [[code("OpenAICompatible.layerGroq")], [code("groq")], [code("https://api.groq.com/openai/v1")]],
        [[code("OpenAICompatible.layerMistral")], [code("mistral")], [code("https://api.mistral.ai/v1")]],
        [[code("OpenAICompatible.layerXAI")], [code("xai")], [code("https://api.x.ai/v1")]],
        [[code("OpenAICompatible.layerDeepSeek")], [code("deepseek")], [code("https://api.deepseek.com/v1")]],
        [
          [code("OpenAICompatible.layerGoogleAIStudio")],
          [code("google")],
          [code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [
          [code("OpenAICompatible.layerAzureOpenAI")],
          [code("azure")],
          [code("https://{resource}.openai.azure.com/openai/v1")],
        ],
        [[code("OpenAICompatible.layerOllama")], [code("ollama")], [code("http://localhost:11434/v1")]],
      ],
    ),
    h2("recipe-gemini", "Recipe: Gemini via the OpenAI-compatible preset"),
    p(
      "TenetKit has no first-party Google helper yet because the upstream Effect AI Google provider is not compatible with the pinned beta, but Google AI Studio speaks the OpenAI protocol. Register it with the ",
      code("layerGoogleAIStudio"),
      " preset and select ",
      code('{ provider: "google", model: "gemini-2.0-flash" }'),
      ".",
    ),
    codeBlock({ label: "gemini-openai-compat.ts", source: geminiOpenaiCompat }),
    p(
      "For context windows and pricing of models reached through presets, pass overrides to the offline ",
      code("ModelCatalog.layer"),
      ". The full export map is in ",
      link("/docs/reference/providers", "the provider-leaf reference"),
      ". To pin loop behavior without any provider at all, see ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
