/* oxlint-disable effecttsgo/strict-effect-provide -- this script is an application entry point. */
import { layer } from "@effect/platform-bun/BunServices"
import { Console, Effect, FileSystem, Schema } from "effect"
import { Command, Flag } from "effect/unstable/cli"
import { Certification } from "../packages/generalist/src/testing/report.js"
import { certificationReportPath } from "./runtime-driver-report.js"

class HostDocumentationFailed extends Schema.TaggedError<HostDocumentationFailed>()(
  "generalist/scripts/HostDocumentationFailed",
  { message: Schema.String },
) {}

const documentationPath = "docs/features/hosts.md"
const hostRows = [
  {
    host: "Node/Bun process",
    driver: "`Runtime.layerMemory`",
    tier: "stable",
    suite: "runtimeDriver:memory",
    notes: "not durable across restarts",
  },
  {
    host: "Node/Bun process",
    driver: "`Runtime.layerSqlite`",
    tier: "stable",
    suite: "runtimeDriver:sqlite",
    notes: "single writer",
  },
  {
    host: "Node/Bun + PostgreSQL",
    driver: "`generalist/pg`",
    tier: "stable",
    suite: "runtimeDriver:PostgreSQL",
    notes: "multi-writer with advisory locks",
  },
  {
    host: "Node/Bun + MySQL",
    driver: "`generalist/mysql`",
    tier: "stable",
    suite: "runtimeDriver:MySQL",
    notes: "",
  },
] as const

const unregisteredRows = [
  {
    host: "Cloudflare Worker + Durable Object",
    driver: "`generalist/unstable/cloudflare/*`",
    tier: "unstable",
    capabilities: "not registered",
    notes: "runtime-driver suite not registered; promote when all pass",
  },
  {
    host: "Rivet actor",
    driver: "`generalist/unstable/rivet`",
    tier: "unstable",
    capabilities: "not registered",
    notes: "runtime-driver suite not registered; `@rivetkit/effect` is beta",
  },
] as const

const table = (rows: ReadonlyArray<ReadonlyArray<string>>): string => {
  const widths = rows[0].map((_, column) => Math.max(...rows.map((row) => row[column].length)))
  const line = (row: ReadonlyArray<string>) =>
    `| ${row.map((cell, column) => cell.padEnd(widths[column])).join(" | ")} |`
  const separator = line(widths.map((width) => "-".repeat(width)))
  return [line(rows[0]), separator, ...rows.slice(1).map(line)].join("\n")
}

export const renderHosts = (report: Certification): string => {
  const suites = new Map(report.suites.map((suite) => [suite.name, suite]))
  const rows = hostRows.map((host) => {
    const suite = suites.get(host.suite)
    if (suite === undefined) {
      throw HostDocumentationFailed.make({ message: `${certificationReportPath} has no ${host.suite} result` })
    }
    return [host.host, host.driver, host.tier, suite.capabilities.join(", "), host.notes]
  })
  rows.push(
    ...unregisteredRows.map((host) => [host.host, host.driver, host.tier, host.capabilities, host.notes] as const),
  )
  return `# Runtime hosts

<!-- Generated by scripts/render-hosts.ts. Do not edit by hand. -->

The certification report records the capability names advertised by each runtime driver whose complete shared suite passed. Cloudflare and Rivet have host-specific tests, but do not register the shared runtime-driver suite, so this matrix does not present them as certified.

${table([["Host", "Driver", "Tier", "Capabilities passed", "Notes"], ...rows])}

## Report lifecycle

The committed [\`hosts-report.json\`](hosts-report.json) is the last passing evidence for each registered driver. \`bun run test\` refreshes a row only when that driver's complete runtime-driver suite ran and passed, then checks this generated page for drift. A failed suite fails the test run and does not replace prior passing evidence.

PostgreSQL and MySQL are skipped when their database URL is unset. A skip is represented by no result for that driver in the current run, not by a failure or an empty capability list; the reporter therefore preserves its committed result. CI provides both databases and refreshes both rows. Capability names come from the registered suite dynamically rather than from a list in the renderer.
`
}

const program = Effect.fn("RenderHosts.program")(function* (check: boolean) {
  const fileSystem = yield* FileSystem.FileSystem
  const report = yield* Schema.decodeEffect(Schema.fromJsonString(Certification))(
    yield* fileSystem.readFileString(certificationReportPath),
  )
  const rendered = renderHosts(report)
  if (!check) {
    yield* fileSystem.writeFileString(documentationPath, rendered)
    return
  }
  const current = yield* fileSystem.readFileString(documentationPath)
  if (current !== rendered) {
    return yield* HostDocumentationFailed.make({
      message: `${documentationPath} has drifted; run bun scripts/render-hosts.ts`,
    })
  }
  yield* Console.log(`${documentationPath} matches ${certificationReportPath}`)
})

const command = Command.make("render-hosts", { check: Flag.boolean("check") }, ({ check }) => program(check))

if (import.meta.main) {
  await Effect.runPromise(Command.run(command, { version: "1" }).pipe(Effect.provide(layer)))
}
