import { describe, expect, it } from "@effect/vitest"
import { Effect } from "effect"
import { ActiveModelResponse, ModelTelemetry } from "../src/index"
import { make as makeActiveModelResponse } from "../src/core/model/result/active-model-response-writer.js"

type FeatureEntry = readonly [subpath: string, load: () => Promise<object>, keys: ReadonlyArray<string>]

const featureEntries: ReadonlyArray<FeatureEntry> = [
  [
    "blob-store",
    () => import("../src/blob-store/index.js"),
    ["Blob", "BlobNotFound", "BlobStore", "BlobStoreError", "BlobTooLarge", "Put", "layer"],
  ],
  [
    "media",
    () => import("../src/media/index.js"),
    ["File", "MediaReadError", "MediaTypeUnsupported", "Ref", "fromPath", "part", "resolve"],
  ],
  [
    "runtime",
    () => import("../src/runtime/index.js"),
    [
      "Address",
      "AgentDirectory",
      "Approval",
      "ChildAdmission",
      "ChildReadiness",
      "ChildRuns",
      "ChildSettlement",
      "CodeMode",
      "Cursor",
      "Errors",
      "ExecutableManifest",
      "ExecutableRegistration",
      "ExecutableResolver",
      "ExecutionState",
      "FanOut",
      "Fork",
      "HostSession",
      "Inspection",
      "LocalScheduler",
      "Mailbox",
      "Message",
      "Messaging",
      "ModelPreview",
      "OperationResolution",
      "Recovery",
      "Run",
      "RunEvent",
      "RunExecutor",
      "RunStore",
      "RunTree",
      "RunWait",
      "Runtime",
      "SessionQueue",
      "SessionSender",
      "Steering",
      "TreePolicy",
    ],
  ],
  [
    "runtime/inspection",
    () => import("../src/runtime/inspection.js"),
    [
      "Budget",
      "Child",
      "Cursor",
      "Inspection",
      "InspectionCorrupt",
      "InspectionCursorInvalid",
      "InspectionLimitInvalid",
      "InspectionUnavailable",
      "Page",
      "PageInput",
      "PartitionInspection",
      "Run",
      "RunNotFound",
      "RunStatus",
      "Session",
      "SessionNotFound",
      "Usage",
      "Wait",
      "layer",
    ],
  ],
  [
    "instructions",
    () => import("../src/instructions/index.js"),
    [
      "Authorship",
      "Entry",
      "FileSystemStore",
      "Instructions",
      "Overview",
      "PackageCatalog",
      "Refinement",
      "Registration",
      "Snapshot",
      "State",
      "Store",
      "fromText",
      "layer",
      "layerTest",
      "load",
      "render",
    ],
  ],
  [
    "instructions/skills",
    () => import("../src/instructions/skills/index.js"),
    ["FileSystemCatalog", "GitHubCatalog", "HttpCatalog", "S3Catalog"],
  ],
  [
    "server",
    () => import("../src/server/index.js"),
    [
      "ClientAgentIdentity",
      "ClientApprovalSummary",
      "ClientBudget",
      "ClientConversation",
      "ClientConversationEntry",
      "ClientConversationUpdate",
      "ClientCursor",
      "ClientEvent",
      "ClientMessage",
      "ClientPreview",
      "ClientQueueEntry",
      "ClientRun",
      "ClientRunSummary",
      "ClientServerEvent",
      "ClientSession",
      "ClientSessionHistoryPage",
      "ClientSessionRunsPage",
      "ClientSessionSnapshot",
      "ClientUsage",
      "ClientWait",
      "Server",
    ],
  ],
  ["mcp", () => import("../src/unstable/mcp/index.js"), ["MCPClient", "OAuth"]],
  [
    "testing",
    () => import("../src/testing/index.js"),
    ["KernelProviderConformance", "TestModel", "Testing", "codeExecutorConformance"],
  ],
  [
    "repl",
    () => import("../src/repl/index.js"),
    [
      "Cell",
      "CellTool",
      "HostBindings",
      "KernelPool",
      "KernelProfile",
      "KernelResourceAuthority",
      "KernelSnapshotStore",
      "RemoteKernelProtocol",
      "TestKernel",
    ],
  ],
  [
    "repl/bun",
    () => import("../src/repl/bun/index.js"),
    ["BunKernelPool", "BunKernelSnapshotStore", "workerModule", "workerSupportModules"],
  ],
  ["ag-ui", () => import("../src/unstable/ag-ui/index.js"), ["AGUI", "Errors"]],
  ["a2a", () => import("../src/unstable/a2a/index.js"), ["A2A", "Content", "Errors", "Projection"]],
  ["foldkit", () => import("../src/unstable/foldkit/index.js"), ["Chat", "Connection"]],
  [
    "memory",
    () => import("../src/memory/index.js"),
    ["SemanticRecall", "Supermemory", "SupermemoryError", "VectorStore", "WorkingMemory", "layer", "layerSupermemory"],
  ],
  [
    "memo",
    () => import("../src/memo.js"),
    ["Dependencies", "MemoError", "Store", "layerDependencies", "layerMemory", "models", "pure"],
  ],
  ["tasks", () => import("../src/tasks/index.js"), ["Item", "Items", "Status", "Update", "layer", "update"]],
]

describe("generalist public surface", () => {
  it.effect("keeps the frozen root namespace", () =>
    Effect.gen(function* () {
      const module = yield* Effect.promise(() => import("../src/index.js"))
      expect(Object.keys(module).toSorted()).toEqual([
        "ActiveModelResponse",
        "Agent",
        "AgentEvent",
        "AgentManifest",
        "AgentProgram",
        "AgentTool",
        "Approvals",
        "BlobStore",
        "CodeExecutor",
        "Compaction",
        "ContextOverflow",
        "DurableDriver",
        "ExecutableManifest",
        "Gate",
        "Guardrail",
        "Handoff",
        "Hooks",
        "Instructions",
        "Media",
        "Memo",
        "Memory",
        "ModelMiddleware",
        "ModelRegistry",
        "ModelResilience",
        "ModelStreamTermination",
        "ModelTelemetry",
        "ModelToolCallValidation",
        "NestedOperation",
        "Permissions",
        "Pins",
        "Policy",
        "ProgramCapabilities",
        "ProgramHandlers",
        "ProgramManifest",
        "ProgramRunner",
        "RunBudget",
        "RunId",
        "Session",
        "SessionHistory",
        "SessionSync",
        "SkillCatalog",
        "Steering",
        "Tasks",
        "ToolAuthorization",
        "ToolContext",
        "ToolExecutor",
        "ToolManifest",
        "ToolOutput",
        "ToolPlacement",
        "Triggers",
        "Watcher",
        "withCacheBreakpoints",
      ])
    }),
  )

  it.effect("keeps exact feature namespace keys", () =>
    Effect.gen(function* () {
      for (const [subpath, load, keys] of featureEntries) {
        const module = yield* Effect.promise(load)
        expect(Object.keys(module).toSorted(), subpath).toEqual(keys)
      }
    }),
  )

  it("exports only the read-only active response tag", () => {
    const handle = makeActiveModelResponse()
    expect(ActiveModelResponse.ActiveModelResponse).toBeDefined()
    expect(Effect.isEffect(handle.snapshot)).toBe(true)
    expect("accept" in handle).toBe(false)
    expect(Object.keys(ActiveModelResponse).toSorted()).toEqual(["ActiveModelResponse"])
  })

  it("exports the model telemetry contract", () => {
    expect(Object.keys(ModelTelemetry).toSorted()).toEqual([
      "AttemptCompleted",
      "AttemptFailed",
      "AttemptFirstOutput",
      "AttemptStarted",
      "CallCompleted",
      "CallFailed",
      "CallPurpose",
      "CallStarted",
      "CompactionApplied",
      "CompactionCommit",
      "CompactionFailed",
      "CompactionKind",
      "CompactionSkipped",
      "CompactionStarted",
      "CompactionTrigger",
      "CurrentPurpose",
      "DeliveryBatch",
      "Event",
      "FailureCategory",
      "FailureClassification",
      "FailureDisposition",
      "FallbackScheduled",
      "FirstOutputKind",
      "InvocationLifecycle",
      "InvocationLifecycleFailed",
      "ModelInvocationCompleted",
      "ModelInvocationFailed",
      "ModelInvocationMethod",
      "ModelInvocationStarted",
      "ProviderUsage",
      "RetryReason",
      "RetryScheduled",
      "Sink",
      "SinkFailed",
      "classifyFailureCategory",
      "generateId",
      "isInvocationLifecycleFailed",
      "layerInvocationLifecycleNoop",
      "layerSinkNoop",
    ])
  })
})
