import { code, command, definePage, h2, lead, link, p, table } from "../../../prose"
export const skillsReference = definePage({
  path: "/docs/reference/skills",
  title: "generalist/instructions/skills",
  navTitle: "skills",
  group: "Reference",
  description:
    "Filesystem and manifest-backed HTTP, S3, and GitHub SKILL.md catalogs plus AGENTS.md/CLAUDE.md loading.",
  content: [
    lead(
      "generalist/instructions/skills implements the core SkillCatalog seam through filesystem and manifest-backed HTTP, S3, and GitHub adapters. generalist/instructions loads AGENTS.md/CLAUDE.md instruction files.",
    ),
    command("Install", "bun add effect@4.0.0-rc.112 generalist@0.44.0"),
    p(
      code("generalist/instructions/skills"),
      " and ",
      code("generalist/instructions"),
      " are import subpaths, not packages.",
    ),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("FileSystemCatalog"),
            ", ",
            code("HttpCatalog"),
            ", ",
            code("S3Catalog"),
            ", ",
            code("GitHubCatalog"),
          ],
        ],
        [[code("generalist/instructions")], [code("File"), ", ", code("Options"), ", and ", code("load")]],
      ],
    ),
    h2("file-system-catalog", "FileSystemCatalog.layer"),
    p(
      code("FileSystemCatalog.layer({ cwd, ...options })"),
      " builds a ",
      code("SkillCatalog.SkillCatalog"),
      " layer requiring ",
      code("FileSystem"),
      " and ",
      code("Path"),
      ", failing with ",
      code("SkillCatalogError"),
      ". Roots are scanned in order; later roots override earlier ones by skill name.",
    ),
    table(
      ["Option", "Default", "Notes"],
      [
        [
          [code("roots")],
          [code('[".agents/skills", ".claude/skills", ".pi/skills"]')],
          "Absolute or resolved against cwd",
        ],
        [[code("cwd")], [code('"."')], "Base directory for relative roots"],
        [[code("frontmatterMaxBytes")], [code("65536")], "Bytes read when parsing only the frontmatter header"],
      ],
    ),
    p(
      "Discovery finds every ",
      code("SKILL.md"),
      " under each root recursively. The required frontmatter name must match the immediate directory: a file at ",
      code("web/search/SKILL.md"),
      " declares ",
      code("name: search"),
      ". Bodies load lazily; listing skills reads only headers.",
    ),
    h2("hosted-catalogs", "Hosted catalogs"),
    p(
      code("HttpCatalog.make"),
      ", ",
      code("S3Catalog.make"),
      ", and ",
      code("GitHubCatalog.make"),
      " return composable ",
      code("SkillCatalog.Service"),
      " effects over the ambient Effect ",
      code("HttpClient"),
      " and ",
      code("Crypto"),
      ". Their matching ",
      code("layer"),
      " constructors provide one catalog directly. Shared hosted construction remains internal; custom transport policy is supplied through the ambient HttpClient.",
    ),
    table(
      ["Provider", "Contract"],
      [
        [[code("HttpCatalog")], "Same-origin paths relative to one versioned Generalist manifest URL"],
        [[code("S3Catalog")], "Virtual-hosted HTTPS manifest object; caller HttpClient owns signing"],
        [[code("GitHubCatalog")], "GitHub Contents API raw reads pinned to a 40/64-hex commit id"],
      ],
    ),
    p(
      "The manifest carries complete listing frontmatter, a safe relative ",
      code("skillPath"),
      ", and the lowercase SHA-256 of the full ",
      code("SKILL.md"),
      ". Metadata loads at catalog construction; bodies stay lazy and are verified on activation. The manifest is a Generalist adapter contract, not part of the Agent Skills standard.",
    ),
    h2("skill-md", "The SKILL.md contract"),
    p(
      "A document is YAML-like frontmatter between ",
      code("---"),
      " fences followed by the Markdown body. ",
      code("name"),
      " and ",
      code("description"),
      " are required; keys are matched ignoring case, hyphens, and underscores.",
    ),
    table(
      ["Key", "Type", "Notes"],
      [
        [[code("name")], "string", "Required standard name; must match the directory"],
        [[code("description")], "string", "Required standard description; 1-1024 characters"],
        [[code("when-to-use")], "string", "Optional usage hint"],
        [[code("allowed-tools")], "string", "Standard space-separated tool names"],
        [[code("disable-model-invocation")], "boolean", "Excluded from model-facing listings when true"],
        [[code("user-invocable")], "boolean", "Optional flag"],
        [[code("context-fork")], "boolean", "Optional flag"],
        [[code("agent")], "string", "Optional agent name"],
        [[code("model")], "string", "Optional model hint"],
        [[code("paths")], "string array", "Optional related paths"],
      ],
    ),
    h2("instruction-files", "Instruction files"),
    p(
      code('load(options?) from "generalist/instructions"'),
      " returns ",
      code("ReadonlyArray<InstructionFile>"),
      " (",
      code("{ path, content }"),
      "), requiring ",
      code("FileSystem"),
      " and ",
      code("Path"),
      ". It reads ",
      code("globalFiles"),
      " first, then walks from the filesystem root down to ",
      code("cwd"),
      ", taking the first matching filename per directory.",
    ),
    table(
      ["Option", "Default"],
      [
        [[code("filenames")], [code('["AGENTS.md", "CLAUDE.md"]')]],
        [[code("cwd")], [code('"."')]],
        [[code("globalFiles")], [code("[]")]],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/skills", "How to add skills"),
      " and ",
      link("/docs/guides/instructions", "How to compose instructions and instruction providers"),
      ".",
    ),
  ],
})
