import * as Prose from "../../prose"

export const corePoliciesReference = Prose.definePage({
  path: "/docs/reference/core-policies",
  title: "Policies and gating",
  navTitle: "Policies",
  group: "Reference",
  description: "TurnPolicy, Approvals, and Permissions: every decision union and layer constructor.",
  content: [
    Prose.lead(
      "Three namespaces of @batonfx/core gate what a run may do next: TurnPolicy decides follow-up turns, Approvals enforces needsApproval, and Permissions evaluates allow/deny/ask rules per tool call.",
    ),
    Prose.command("Install", "bun add effect@4.0.0-beta.93 @batonfx/core"),
    Prose.h2("turn-policy", "TurnPolicy"),
    Prose.p(
      "A policy is ",
      Prose.code("{ decide: (info: TurnInfo) => Effect<Decision> }"),
      ", consulted before each follow-up turn. ",
      Prose.code("TurnInfo"),
      " carries ",
      Prose.code("turn"),
      " (0-based count of completed model turns), ",
      Prose.code("history"),
      ", and ",
      Prose.code("pendingToolResults"),
      ".",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("decision.continue(overrides?)"), " / ", Prose.code("decision.stop")],
          [
            Prose.code("Decision"),
            " constructors; ",
            Prose.code("TurnOverrides"),
            " may set ",
            Prose.code("instructions"),
            ", ",
            Prose.code("model"),
            " (a LanguageModel layer), and ",
            Prose.code("activeTools"),
            " for the next turn",
          ],
        ],
        [[Prose.code("make(decide)")], "Policy from a decide function"],
        [[Prose.code("recurs(n)")], ["Continue for at most ", Prose.code("n"), " follow-up turns after the first"]],
        [[Prose.code("untilToolCall(name)")], "Continue while the named tool has not yet been called this run"],
        [
          [Prose.code("both(first, second)")],
          ["Both must continue; overrides merge with ", Prose.code("second"), " winning"],
        ],
        [[Prose.code("defaultPolicy")], [Prose.code("recurs(8)")]],
      ],
    ),
    Prose.h2("approvals", "Approvals"),
    Prose.p(
      "One of the four required run services and the enforcement point for ",
      Prose.code("Ai.Tool.needsApproval"),
      ", which ",
      Prose.code("effect/unstable/ai"),
      " declares but never enforces. The interface is ",
      Prose.code("check: (request: ToolExecutor.Request) => Effect<Decision>"),
      ".",
    ),
    Prose.table(
      ["Decision", "Fields", "Loop behavior"],
      [
        [[Prose.code("Approved")], "none", "The tool executes"],
        [
          [Prose.code("Denied")],
          [Prose.code("reason?")],
          ["The model receives a failed tool result with ", Prose.code("reason")],
        ],
        [
          [Prose.code("Pending")],
          [Prose.code("token")],
          ["The run suspends with ", Prose.code('AgentSuspended{ reason: "approval" }')],
        ],
      ],
    ),
    Prose.table(
      ["Layer", "Behavior"],
      [
        [[Prose.code("Approvals.autoApprove")], "Every check returns Approved — the default choice"],
        [[Prose.code("Approvals.denyAll")], "Every check returns Denied; useful in tests and lockdown"],
        [[Prose.code("Approvals.testLayer(implementation)")], "Layer from an explicit interface"],
      ],
    ),
    Prose.h2("permissions", "Permissions"),
    Prose.p(
      "An optional seam consulted before Approvals. The interface has two members: ",
      Prose.code("evaluate: (request: EvaluationRequest) => Effect<Decision, PermissionError>"),
      " and ",
      Prose.code("await: (pending: Pending) => Effect<Option<Answer>, PermissionError>"),
      ".",
    ),
    Prose.table(
      ["Type", "Members", "Notes"],
      [
        [[Prose.code("Level")], [Prose.code('"allow" | "deny" | "ask"')], "What a matched rule grants"],
        [
          [Prose.code("Rule")],
          [Prose.code("pattern"), ", ", Prose.code("level"), ", ", Prose.code("reason?")],
          [
            "Pattern is ",
            Prose.code("tool"),
            " or ",
            Prose.code("tool:params"),
            " with ",
            Prose.code("*"),
            " globs matched against projected param text",
          ],
        ],
        [
          [Prose.code("Ruleset")],
          [Prose.code("rules"), ", ", Prose.code("fallback?")],
          ["Last matching rule wins; fallback defaults to ", Prose.code('"ask"')],
        ],
        [
          [Prose.code("EvaluationRequest")],
          [
            Prose.code("tool"),
            ", ",
            Prose.code("params"),
            ", ",
            Prose.code("agentName"),
            ", ",
            Prose.code("turn"),
            ", ",
            Prose.code("toolCallId?"),
            ", ",
            Prose.code("sessionId?"),
          ],
          "Tool-call information given to policies",
        ],
        [
          [Prose.code("Decision")],
          [Prose.code("Allow | Deny{reason?} | Ask{token}")],
          "Resolved policy decision for one call",
        ],
        [
          [Prose.code("Answer")],
          [Prose.code("Approved | Denied{reason?} | Always")],
          [
            "Out-of-band answer to an ask; ",
            Prose.code("Always"),
            " additionally remembers an allow rule via ",
            Prose.code("RuleStore"),
          ],
        ],
        [
          [Prose.code("Pending")],
          [
            Prose.code("token"),
            ", ",
            Prose.code("tool"),
            ", ",
            Prose.code("params"),
            ", ",
            Prose.code("agentName"),
            ", ",
            Prose.code("turn"),
            ", ",
            Prose.code("toolCallId?"),
          ],
          "Ask surfaced to an approver",
        ],
      ],
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [[Prose.code("matches(pattern, tool, params)")], "Match one permission pattern against a tool call"],
        [
          [Prose.code("evaluate(ruleset, tool, params)")],
          ["Pure ruleset evaluation to a ", Prose.code("Level"), " with last-match semantics"],
        ],
        [
          [Prose.code("fromRuleset(ruleset)")],
          "Policy layer from a static ruleset; asks are never answered in-process",
        ],
        [[Prose.code("allowAll")], "Policy layer that allows every call"],
        [
          [Prose.code("interactive({ ruleset, onAsk })")],
          ["In-process policy whose asks are answered by ", Prose.code("onAsk")],
        ],
        [[Prose.code("ruleStoreMemory(initialRules?)")], "Non-durable in-memory remembered-rule store"],
        [[Prose.code("testLayer"), " / ", Prose.code("ruleStoreTestLayer")], "Layers from explicit interfaces"],
        [[Prose.code("PermissionError")], ["Tagged error with ", Prose.code("message")]],
      ],
    ),
    Prose.callout(
      "info",
      "Deny rules fail closed",
      "When a params projection is incomplete (non-text leaves), a matching deny-level tool pattern applies regardless of its params pattern.",
    ),
    Prose.p(
      "See ",
      Prose.link("/docs/guides/turn-policy", "How to control turn budgets"),
      ", ",
      Prose.link("/docs/guides/approvals", "How to require human approval for a tool"),
      ", and ",
      Prose.link("/docs/guides/permissions", "How to gate tools with permission rules"),
      ".",
    ),
  ],
})
