import * as Prose from "../../prose"

export const coreContextReference = Prose.definePage({
  path: "/docs/reference/core-context",
  title: "Context seams",
  navTitle: "Context seams",
  group: "Reference",
  description: "Instructions, SkillSource, Memory, Session, Compaction, Steering, and Handoff.",
  content: [
    Prose.lead(
      "Seven namespaces of @batonfx/core shape what the model sees and how a conversation persists. All are optional seams discovered per run; absent means default behavior.",
    ),
    Prose.command("Install", "bun add @batonfx/core"),
    Prose.h2("instructions", "Instructions"),
    Prose.p(
      "An ordered registry of ",
      Prose.code("ContextSource"),
      " values: ",
      Prose.code('{ id, cache: "baseline" | "dynamic", render }'),
      ". Baseline sources render once into the system message when an epoch opens; dynamic sources render incremental updates each turn.",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [[Prose.code("staticSource(id, text)")], "A static baseline source; empty text renders nothing"],
        [
          [Prose.code("openEpoch(instructions, context)")],
          ["Renders baseline sources and freezes dynamic sources into a ", Prose.code("ContextEpoch")],
        ],
        [[Prose.code("renderUpdate(epoch, context)")], "Renders dynamic sources for an incremental context update"],
        [
          [Prose.code("layer(sources)"), " / ", Prose.code("testLayer(implementation)")],
          "Explicit ordered registry; layer from an interface",
        ],
      ],
    ),
    Prose.h2("skill-source", "SkillSource"),
    Prose.p(
      "The skill registry seam: ",
      Prose.code("{ all, get(name) }"),
      " over ",
      Prose.code("Skill = { frontmatter, listing, body, tools }"),
      ". The loop lists skills within a token budget and loads bodies lazily through the built-in ",
      Prose.code("activate_skill"),
      " tool.",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("Frontmatter")],
          [
            Prose.code("name"),
            " and ",
            Prose.code("description"),
            " required; optional ",
            Prose.code("whenToUse"),
            ", ",
            Prose.code("allowedTools"),
            ", ",
            Prose.code("disableModelInvocation"),
            ", ",
            Prose.code("userInvocable"),
            ", ",
            Prose.code("contextFork"),
            ", ",
            Prose.code("agent"),
            ", ",
            Prose.code("model"),
            ", ",
            Prose.code("paths"),
          ],
        ],
        [
          [Prose.code("makeListing(frontmatter, descriptionCap?)")],
          ["One listing line; descriptions capped at ", Prose.code("DESCRIPTION_CAP"), " (1536) characters"],
        ],
        [
          [Prose.code("selectListings(skills, budgetTokens, recentlyUsed)")],
          [
            "Startup listings within a token budget; skills with ",
            Prose.code("disableModelInvocation: true"),
            " are excluded, least-recently-used drop first",
          ],
        ],
        [
          [Prose.code("fromSkills(skills)"), " / ", Prose.code("empty"), " / ", Prose.code("testLayer")],
          "In-memory source, empty source, layer from an interface",
        ],
        [[Prose.code("SkillSourceError")], [Prose.code("{ source, message, cause? }")]],
      ],
    ),
    Prose.h2("memory", "Memory"),
    Prose.p(
      "The recall/remember seam keyed by ",
      Prose.code("Key = { agent, subject }"),
      ". ",
      Prose.code("recall(input)"),
      " returns ",
      Prose.code("Item"),
      " values (",
      Prose.code("{ id, parts, metadata? }"),
      ") injected into context; ",
      Prose.code("remember(input)"),
      " receives the transcript with a ",
      Prose.code("terminal"),
      " flag after each turn.",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [[Prose.code("merge(first, second)")], "Concatenates recalls, fans out remembers"],
        [[Prose.code("noopLayer")], "Recalls nothing, remembers nothing"],
        [[Prose.code("testLayer(implementation)")], "Layer from an explicit interface"],
        [[Prose.code("MemoryError")], [Prose.code("{ message }")]],
      ],
    ),
    Prose.p("Implementations live in ", Prose.link("/docs/reference/memory", "@batonfx/memory"), "."),
    Prose.h2("session", "Session"),
    Prose.p(
      "An append-only entry log with a leaf pointer. ",
      Prose.code("Entry"),
      " is the closed union ",
      Prose.code("MessageEntry | CompactionEntry | BranchSummaryEntry"),
      "; the store interface is ",
      Prose.code("{ append, path, setLeaf, leaf }"),
      ".",
    ),
    Prose.table(
      ["Entry", "Fields beyond id/parentId/metadata", "Projection"],
      [
        [[Prose.code("MessageEntry")], [Prose.code("message: Ai.Prompt.Message")], "Included verbatim"],
        [
          [Prose.code("CompactionEntry")],
          [Prose.code("summary"), ", ", Prose.code("firstKeptEntryId")],
          [
            "Entries before ",
            Prose.code("firstKeptEntryId"),
            " are replaced by a ",
            Prose.code("<conversation-checkpoint>"),
            " user message",
          ],
        ],
        [
          [Prose.code("BranchSummaryEntry")],
          [Prose.code("summary")],
          ["Rendered as an ", Prose.code("<abandoned-branch-summary>"), " system message"],
        ],
      ],
    ),
    Prose.p(
      Prose.code("Session.buildContext(path)"),
      " purely projects a root-to-leaf path into an ",
      Prose.code("Ai.Prompt.Prompt"),
      ". ",
      Prose.code("Session.memoryLayer"),
      " is the Ref-backed non-durable store; ",
      Prose.code("testLayer"),
      " wraps an explicit interface. Failures are ",
      Prose.code("SessionStoreError{ message }"),
      ".",
    ),
    Prose.h2("compaction", "Compaction"),
    Prose.p(
      "The seam consulted when context approaches the window: ",
      Prose.code("maybeCompact(request) => Effect<Option<Result>, CompactionError, LanguageModel>"),
      ". ",
      Prose.code("Result"),
      " is ",
      Prose.code("MicrocompactResult"),
      " (tool outputs bounded in place) or ",
      Prose.code("SummarizeResult"),
      " (summary checkpoint plus ",
      Prose.code("firstKeptEntryId"),
      ").",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("defaultStrategy(options?)")],
          "Two-stage strategy: microcompact tool outputs first, then cut and summarize the head",
        ],
        [
          [Prose.code("layer(options?, strategy?)")],
          [
            "Service layer; ",
            Prose.code("DefaultOptions"),
            " are ",
            Prose.code("reserveTokens"),
            " (default 16384), ",
            Prose.code("keepRecentTokens"),
            " (default 20000), ",
            Prose.code("contextWindow"),
            ", ",
            Prose.code("summaryModel"),
            ", ",
            Prose.code("summaryPrompt"),
            " (default ",
            Prose.code("SUMMARY_TEMPLATE"),
            ")",
          ],
        ],
        [
          [Prose.code("truncate(maxTokens)")],
          ["Truncate-only implementation over an ", Prose.code("Ai.Tokenizer"), " when one is provided"],
        ],
        [
          [Prose.code("isContextOverflow(error)")],
          "Heuristic classifier for reactive compaction after a provider overflow error",
        ],
        [
          [Prose.code("make(strategy, options?)"), " / ", Prose.code("testLayer")],
          "Interface from a strategy; layer from an interface",
        ],
      ],
    ),
    Prose.h2("steering", "Steering"),
    Prose.p(
      "In-process queues for injecting prompts into a live run: ",
      Prose.code("steer"),
      " drains at model-turn boundaries mid-run, ",
      Prose.code("followUp"),
      " drains after the run would otherwise complete.",
    ),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("layer(options?)")],
          [
            "Two unbounded queues; ",
            Prose.code("steeringMode"),
            " defaults to ",
            Prose.code('"all"'),
            ", ",
            Prose.code("followUpMode"),
            " to ",
            Prose.code('"one-at-a-time"'),
          ],
        ],
        [
          [Prose.code("Interface")],
          [
            Prose.code("steer"),
            ", ",
            Prose.code("followUp"),
            ", ",
            Prose.code("takeSteering"),
            ", ",
            Prose.code("takeFollowUp"),
            " over ",
            Prose.code("Message = { prompt }"),
          ],
        ],
        [[Prose.code("testLayer(implementation)")], "Layer from an explicit interface"],
      ],
    ),
    Prose.h2("handoff", "Handoff"),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("transferTool(target, options?)")],
          ["Handled toolkit exposing ", Prose.code("transfer_to_<agent.name>"), " as a same-process handoff tool"],
        ],
        [
          [Prose.code("fanOut(children, options?)")],
          "Runs isolated child agents concurrently (default concurrency 4) and preserves input order",
        ],
        [
          [Prose.code("supervisor(options)")],
          "Builds a supervisor agent plus the handled toolkit of transfer tools for its specialists",
        ],
      ],
    ),
    Prose.p(
      "See ",
      Prose.link("/docs/guides/instructions", "How to compose instructions and context sources"),
      ", ",
      Prose.link("/docs/guides/skills", "How to add skills"),
      ", ",
      Prose.link("/docs/guides/memory", "How to add memory"),
      ", ",
      Prose.link("/docs/guides/compaction", "How to stay inside the context window"),
      ", ",
      Prose.link("/docs/guides/steering", "How to steer and interrupt a running agent"),
      ", ",
      Prose.link("/docs/guides/multi-agent", "How to coordinate multiple agents"),
      ", and ",
      Prose.link("/docs/learn/sessions-and-history", "Sessions, history, and persistence"),
      ".",
    ),
  ],
})
