import { code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const coreToolsReference = definePage({
  path: "/docs/reference/core-tools",
  title: "Tools and execution",
  navTitle: "Tools",
  group: "Reference",
  description: "ToolExecutor, ToolContext, ToolOutput and its store, and AgentTool for agents-as-tools.",
  content: [
    lead(
      "Four namespaces of @batonfx/core cover tool execution: ToolExecutor optionally overrides where calls run, ToolContext is the ambient per-call context, ToolOutput bounds large results, and AgentTool wraps an agent as a tool.",
    ),
    command("Install", "bun add @batonfx/core"),
    h2("tool-executor", "ToolExecutor"),
    p(
      "Optional override seam for durable hosts, client-executed tools, remote workers, MCP, sandboxing, and suspension. Ordinary in-process tools use the active Effect AI ",
      code("Toolkit"),
      " handlers directly, so no executor layer is required. When you do provide the service, its interface is a single function ",
      code("execute: (request: Request) => Effect<Outcome, FrameworkFailure | RemoteRetryMisconfigured, ToolContext>"),
      ". Direct executor consumers observe typed framework and retry errors; the Agent loop preserves framework failures and wraps RemoteRetryMisconfigured in AgentError with the typed cause retained.",
    ),
    table(
      ["Request field", "Type", "Notes"],
      [
        [[code("call")], [code("Ai.Response.ToolCallPart<string, unknown>")], "The model's tool call"],
        [[code("turn")], [code("number")], "0-based turn issuing the call"],
        [[code("agentName")], [code("string")], "Name of the running agent"],
        [[code("sessionId")], [code("string")], "Host-assigned run/session identity"],
      ],
    ),
    table(
      ["Outcome", "Fields", "Loop behavior"],
      [
        [
          [code("Success")],
          [code("result"), ", ", code("encodedResult")],
          "Re-fed to the model as a successful tool result",
        ],
        [
          [code("DomainFailure")],
          [code("failure"), ", ", code("encodedFailure")],
          "Re-fed as a schema-valid failed tool result; the run continues",
        ],
        [[code("Suspend")], [code("token")], ["The run fails with ", code('AgentSuspended{ reason: "tool-wait" }')]],
      ],
    ),
    table(
      ["Constructor", "Notes"],
      [
        [
          [code("ToolExecutor.layerToolkit(toolkit)")],
          [
            "Executes via a handled ",
            code("Ai.Toolkit.WithHandler"),
            ". Declared handler failures produce ",
            code("DomainFailure"),
            "; missing handlers fail with ",
            code("FrameworkFailure"),
          ],
        ],
        [[code("ToolExecutor.route({ tools?, matches?, execute })")], "Manual route for custom dispatch"],
        [[code("ToolExecutor.routeToolkit(toolkit)")], "Route that delegates to Effect AI toolkit handlers"],
        [[code("ToolExecutor.layerRouter(routes)")], "Layer that tries routes in order and fails unmatched names"],
        [[code("ToolExecutor.client({ toolkit, execute })")], "Route toolkit calls to a user/browser/desktop client"],
        [
          [code("ToolExecutor.remote({ toolkit, idempotent?, execute, ... })")],
          "Route toolkit calls to a remote worker; one attempt unless explicit idempotency and bounded retry are configured",
        ],
        [[code("ToolExecutor.mcp({ toolkit, execute })")], "Route toolkit calls through an MCP adapter"],
        [[code("ToolExecutor.sandbox({ toolkit, execute })")], "Route toolkit calls to a workspace or sandbox runtime"],
        [[code("ToolExecutor.layerTest(implementation)")], "Layer from an explicit interface"],
      ],
    ),
    p(
      "The placement route helpers reuse the original Effect AI tool definitions. The executor receives the original ",
      code("Tool"),
      " value, and successful placement results are decoded and encoded against that tool's ",
      code("success"),
      " schema before Baton re-feeds the result to the model. Placement domain failures are decoded and encoded against the tool's failure schema. Framework failures remain in the Effect error channel and use stage evidence; they are never emitted as tool-schema output.",
    ),
    p(
      "Migration: replace exhaustive ",
      code('outcome._tag === "Failure"'),
      " matches with ",
      code('outcome._tag === "DomainFailure"'),
      " and consume ",
      code("failure"),
      " plus ",
      code("encodedFailure"),
      ". Handle ",
      code("FrameworkFailure"),
      " with ",
      code('Effect.catchTag("@batonfx/core/FrameworkFailure", ...)'),
      ". Remote placement codecs replace message-only Failure with DomainFailure carrying the declared schema value.",
    ),
    p(
      "Remote routes execute once by default. Retrying requires ",
      code("idempotent: true"),
      ", a stable non-empty ",
      code("operationKey"),
      ", a non-negative finite integer ",
      code("maxRetries"),
      ", and a schedule typed to the executor's infrastructure failure. The remote endpoint must deduplicate the key. Client, MCP, sandbox, and custom routes remain one-shot.",
    ),
    h2("tool-context", "ToolContext"),
    p("Ambient context available to a tool handler for the current call."),
    table(
      ["Member", "Type", "Notes"],
      [
        [[code("signal")], [code("AbortSignal")], "Aborted when the run is interrupted"],
        [
          [code("emit")],
          [code("(progress: Progress) => Effect<void>")],
          [
            "Emits a ",
            code("ToolProgress"),
            " event; ",
            code("Progress"),
            " is ",
            code("{ toolCallId, message?, data? }"),
          ],
        ],
        [[code("sessionId")], [code("string")], "Host-assigned run/session identity"],
      ],
    ),
    p(
      code("ToolContext.layerDefault"),
      " provides a never-aborting signal, a no-op ",
      code("emit"),
      ", and sessionId ",
      code('"local"'),
      ". ",
      code("ToolContext.layerTest(implementation)"),
      " provides an explicit one.",
    ),
    h2("tool-output", "ToolOutput and ToolOutputStore"),
    p(
      "A bounded tool result is ",
      code("ToolOutput = { inline: unknown; outputPaths?: ReadonlyArray<string> }"),
      ". ",
      code("ToolOutputStore"),
      " is the optional seam that stores overflow out of context: ",
      code("put(toolCallId, content) => Effect<Option<string>, ToolOutputError>"),
      ".",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("ToolOutput.bound(result, { toolCallId, maxBytes })")],
          [
            "Returns the result unchanged when it fits, no store is present, or the store declines; otherwise replaces it with a truncated preview ",
            code("{ truncated, bytes, maxBytes, preview }"),
            " plus the spilled ",
            code("outputPaths"),
          ],
        ],
        [[code("ToolOutput.layerNoop")], ["Store that always declines (", code("Option.none"), ")"]],
        [[code("ToolOutput.layerMemory")], ["In-memory store issuing ", code("mem:tool-output-<n>"), " paths"]],
        [[code("ToolOutput.layerTest(implementation)")], "Layer from an explicit store interface"],
        [[code("ToolOutputError")], ["Tagged error with ", code("message")]],
      ],
    ),
    p(
      "The loop applies ",
      code("bound"),
      " to successful outcomes when ",
      code("RunOptions.toolOutputMaxBytes"),
      " is set.",
    ),
    h2("agent-tool", "AgentTool"),
    p(
      code("AgentTool.asTool(agent, options?)"),
      " returns a handled toolkit exposing the agent as one tool. The tool declares ",
      code("failure: Schema.String"),
      " and ",
      code('failureMode: "return"'),
      ", so child failures come back to the parent model as failed tool results. A child ",
      code("AgentSuspended"),
      " is not translated; it escapes as a defect.",
    ),
    table(
      ["Option", "Default"],
      [
        [[code("name")], [code("agent.name")]],
        [[code("description")], "none"],
        [[code("parameters")], [code("Schema.Struct({ prompt: Schema.String })")]],
        [[code("success")], [code("Schema.String")]],
        [[code("toPrompt")], [code("(params) => params.prompt")]],
        [[code("fromResult")], [code("(result) => result.text")]],
      ],
    ),
    p(
      "For handler wiring and spill behavior in practice, see ",
      link("/docs/guides/define-tools", "How to define tools and toolkits"),
      ". For agents-as-tools composition, see ",
      link("/docs/guides/multi-agent", "How to coordinate multiple agents"),
      ".",
    ),
  ],
})
