import { code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const coreToolsReference = definePage({
  path: "/docs/reference/core-tools",
  title: "Tools and execution",
  navTitle: "Tools",
  group: "Reference",
  description: "ToolExecutor, ToolContext, ToolOutput and its store, and AgentTool for agents-as-tools.",
  content: [
    lead(
      "Four namespaces of @batonfx/core cover tool execution: ToolExecutor runs calls, ToolContext is the ambient per-call context, ToolOutput bounds large results, and AgentTool wraps an agent as a tool.",
    ),
    command("Install", "bun add @batonfx/core"),
    h2("tool-executor", "ToolExecutor"),
    p(
      "One of the four required run services. The interface is a single function ",
      code("execute: (request: Request) => Effect<Outcome, AgentError, ToolContext>"),
      ".",
    ),
    table(
      ["Request field", "Type", "Notes"],
      [
        [[code("call")], [code("Ai.Response.ToolCallPart<string, unknown>")], "The model's tool call"],
        [[code("turn")], [code("number")], "0-based turn issuing the call"],
        [[code("agentName")], [code("string")], "Name of the running agent"],
        [[code("sessionId")], [code("string")], "Host-assigned run/session identity"],
      ],
    ),
    table(
      ["Outcome", "Fields", "Loop behavior"],
      [
        [
          [code("Success")],
          [code("result"), ", ", code("encodedResult")],
          "Re-fed to the model as a successful tool result",
        ],
        [[code("Failure")], [code("message")], "Re-fed to the model as a failed tool result; the run continues"],
        [[code("Suspend")], [code("token")], ["The run fails with ", code('AgentSuspended{ reason: "tool-wait" }')]],
      ],
    ),
    table(
      ["Constructor", "Notes"],
      [
        [
          [code("ToolExecutor.fromToolkit(toolkit)")],
          [
            "Executes via a handled ",
            code("Ai.Toolkit.WithHandler"),
            ". Unregistered names produce ",
            code("Failure"),
            "; a handler that dies with ",
            code("AgentSuspended"),
            " produces ",
            code("Suspend"),
            " with its token",
          ],
        ],
        [[code("ToolExecutor.testLayer(implementation)")], "Layer from an explicit interface"],
      ],
    ),
    h2("tool-context", "ToolContext"),
    p("Ambient context available to a tool handler for the current call."),
    table(
      ["Member", "Type", "Notes"],
      [
        [[code("signal")], [code("AbortSignal")], "Aborted when the run is interrupted"],
        [
          [code("emit")],
          [code("(progress: Progress) => Effect<void>")],
          [
            "Emits a ",
            code("ToolProgress"),
            " event; ",
            code("Progress"),
            " is ",
            code("{ toolCallId, message?, data? }"),
          ],
        ],
        [[code("sessionId")], [code("string")], "Host-assigned run/session identity"],
      ],
    ),
    p(
      code("ToolContext.layerDefault"),
      " provides a never-aborting signal, a no-op ",
      code("emit"),
      ", and sessionId ",
      code('"local"'),
      ". ",
      code("ToolContext.testLayer(implementation)"),
      " provides an explicit one.",
    ),
    h2("tool-output", "ToolOutput and ToolOutputStore"),
    p(
      "A bounded tool result is ",
      code("ToolOutput = { inline: unknown; outputPaths?: ReadonlyArray<string> }"),
      ". ",
      code("ToolOutputStore"),
      " is the optional seam that stores overflow out of context: ",
      code("put(toolCallId, content) => Effect<Option<string>, ToolOutputError>"),
      ".",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("ToolOutput.bound(result, { toolCallId, maxBytes })")],
          [
            "Returns the result unchanged when it fits, no store is present, or the store declines; otherwise replaces it with a truncated preview ",
            code("{ truncated, bytes, maxBytes, preview }"),
            " plus the spilled ",
            code("outputPaths"),
          ],
        ],
        [[code("ToolOutput.layerNoop")], ["Store that always declines (", code("Option.none"), ")"]],
        [[code("ToolOutput.layerMemory")], ["In-memory store issuing ", code("mem:tool-output-<n>"), " paths"]],
        [[code("ToolOutput.testLayer(implementation)")], "Layer from an explicit store interface"],
        [[code("ToolOutputError")], ["Tagged error with ", code("message")]],
      ],
    ),
    p(
      "The loop applies ",
      code("bound"),
      " to successful outcomes when ",
      code("RunOptions.toolOutputMaxBytes"),
      " is set.",
    ),
    h2("agent-tool", "AgentTool"),
    p(
      code("AgentTool.asTool(agent, options?)"),
      " returns a handled toolkit exposing the agent as one tool. The tool declares ",
      code("failure: Schema.String"),
      " and ",
      code('failureMode: "return"'),
      ", so child failures come back to the parent model as failed tool results. A child ",
      code("AgentSuspended"),
      " is not translated; it escapes as a defect.",
    ),
    table(
      ["Option", "Default"],
      [
        [[code("name")], [code("agent.name")]],
        [[code("description")], "none"],
        [[code("parameters")], [code("Schema.Struct({ prompt: Schema.String })")]],
        [[code("success")], [code("Schema.String")]],
        [[code("toPrompt")], [code("(params) => params.prompt")]],
        [[code("fromResult")], [code("(result) => result.text")]],
      ],
    ),
    p(
      "For handler wiring and spill behavior in practice, see ",
      link("/docs/guides/define-tools", "How to define tools and toolkits"),
      ". For agents-as-tools composition, see ",
      link("/docs/guides/multi-agent", "How to coordinate multiple agents"),
      ".",
    ),
  ],
})
