import { code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const coreContextReference = definePage({
  path: "/docs/reference/core-context",
  title: "Context seams",
  navTitle: "Context seams",
  group: "Reference",
  description: "Instructions, SkillSource, Memory, Session, Compaction, Steering, and Handoff.",
  content: [
    lead(
      "Seven namespaces of @batonfx/core shape what the model sees and how a conversation persists. All are optional seams discovered per run; absent means default behavior.",
    ),
    command("Install", "bun add @batonfx/core"),
    h2("instructions", "Instructions"),
    p(
      "An ordered registry of ",
      code("ContextSource"),
      " values: ",
      code('{ id, cache: "baseline" | "dynamic", render }'),
      ". Baseline sources render once into the system message when an epoch opens; dynamic sources render incremental updates each turn.",
    ),
    table(
      ["Export", "Notes"],
      [
        [[code("staticSource(id, text)")], "A static baseline source; empty text renders nothing"],
        [
          [code("openEpoch(instructions, context)")],
          ["Renders baseline sources and freezes dynamic sources into a ", code("ContextEpoch")],
        ],
        [[code("renderUpdate(epoch, context)")], "Renders dynamic sources for an incremental context update"],
        [
          [code("layer(sources)"), " / ", code("testLayer(implementation)")],
          "Explicit ordered registry; layer from an interface",
        ],
      ],
    ),
    h2("skill-source", "SkillSource"),
    p(
      "The skill registry seam: ",
      code("{ all, get(name) }"),
      " over ",
      code("Skill = { frontmatter, listing, body, tools }"),
      ". The loop lists skills within a token budget and loads bodies lazily through the built-in ",
      code("activate_skill"),
      " tool.",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("Frontmatter")],
          [
            code("name"),
            " and ",
            code("description"),
            " required; optional ",
            code("whenToUse"),
            ", ",
            code("allowedTools"),
            ", ",
            code("disableModelInvocation"),
            ", ",
            code("userInvocable"),
            ", ",
            code("contextFork"),
            ", ",
            code("agent"),
            ", ",
            code("model"),
            ", ",
            code("paths"),
          ],
        ],
        [
          [code("makeListing(frontmatter, descriptionCap?)")],
          ["One listing line; descriptions capped at ", code("DESCRIPTION_CAP"), " (1536) characters"],
        ],
        [
          [code("selectListings(skills, budgetTokens, recentlyUsed)")],
          [
            "Startup listings within a token budget; skills with ",
            code("disableModelInvocation: true"),
            " are excluded, least-recently-used drop first",
          ],
        ],
        [
          [code("fromSkills(skills)"), " / ", code("empty"), " / ", code("testLayer")],
          "In-memory source, empty source, layer from an interface",
        ],
        [[code("SkillSourceError")], [code("{ source, message, cause? }")]],
      ],
    ),
    h2("memory", "Memory"),
    p(
      "The recall/remember seam keyed by ",
      code("Key = { agent, subject }"),
      ". ",
      code("recall(input)"),
      " returns ",
      code("Item"),
      " values (",
      code("{ id, parts, metadata? }"),
      ") injected into context; ",
      code("remember(input)"),
      " receives the transcript with a ",
      code("terminal"),
      " flag after each turn.",
    ),
    table(
      ["Export", "Notes"],
      [
        [[code("merge(first, second)")], "Concatenates recalls, fans out remembers"],
        [[code("noopLayer")], "Recalls nothing, remembers nothing"],
        [[code("testLayer(implementation)")], "Layer from an explicit interface"],
        [[code("MemoryError")], [code("{ message }")]],
      ],
    ),
    p("Implementations live in ", link("/docs/reference/memory", "@batonfx/memory"), "."),
    h2("session", "Session"),
    p(
      "An append-only entry log with a leaf pointer. ",
      code("Entry"),
      " is the closed union ",
      code("MessageEntry | CompactionEntry | BranchSummaryEntry"),
      "; the store interface is ",
      code("{ append, path, setLeaf, leaf }"),
      ".",
    ),
    table(
      ["Entry", "Fields beyond id/parentId/metadata", "Projection"],
      [
        [[code("MessageEntry")], [code("message: Ai.Prompt.Message")], "Included verbatim"],
        [
          [code("CompactionEntry")],
          [code("summary"), ", ", code("firstKeptEntryId")],
          [
            "Entries before ",
            code("firstKeptEntryId"),
            " are replaced by a ",
            code("<conversation-checkpoint>"),
            " user message",
          ],
        ],
        [
          [code("BranchSummaryEntry")],
          [code("summary")],
          ["Rendered as an ", code("<abandoned-branch-summary>"), " system message"],
        ],
      ],
    ),
    p(
      code("Session.buildContext(path)"),
      " purely projects a root-to-leaf path into an ",
      code("Ai.Prompt.Prompt"),
      ". ",
      code("Session.memoryLayer"),
      " is the Ref-backed non-durable store; ",
      code("testLayer"),
      " wraps an explicit interface. Failures are ",
      code("SessionStoreError{ message }"),
      ".",
    ),
    h2("compaction", "Compaction"),
    p(
      "The seam consulted when context approaches the window: ",
      code("maybeCompact(request) => Effect<Option<Result>, CompactionError, LanguageModel>"),
      ". ",
      code("Result"),
      " is ",
      code("MicrocompactResult"),
      " (tool outputs bounded in place) or ",
      code("SummarizeResult"),
      " (summary checkpoint plus ",
      code("firstKeptEntryId"),
      ").",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("defaultStrategy(options?)")],
          "Two-stage strategy: microcompact tool outputs first, then cut and summarize the head",
        ],
        [
          [code("layer(options?, strategy?)")],
          [
            "Service layer; ",
            code("DefaultOptions"),
            " are ",
            code("reserveTokens"),
            " (default 16384), ",
            code("keepRecentTokens"),
            " (default 20000), ",
            code("contextWindow"),
            ", ",
            code("summaryModel"),
            ", ",
            code("summaryPrompt"),
            " (default ",
            code("SUMMARY_TEMPLATE"),
            ")",
          ],
        ],
        [
          [code("truncate(maxTokens)")],
          ["Truncate-only implementation over an ", code("Ai.Tokenizer"), " when one is provided"],
        ],
        [
          [code("isContextOverflow(error)")],
          "Heuristic classifier for reactive compaction after a provider overflow error",
        ],
        [
          [code("make(strategy, options?)"), " / ", code("testLayer")],
          "Interface from a strategy; layer from an interface",
        ],
      ],
    ),
    h2("steering", "Steering"),
    p(
      "In-process queues for injecting prompts into a live run: ",
      code("steer"),
      " drains at model-turn boundaries mid-run, ",
      code("followUp"),
      " drains after the run would otherwise complete.",
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("layer(options?)")],
          [
            "Two unbounded queues; ",
            code("steeringMode"),
            " defaults to ",
            code('"all"'),
            ", ",
            code("followUpMode"),
            " to ",
            code('"one-at-a-time"'),
          ],
        ],
        [
          [code("Interface")],
          [
            code("steer"),
            ", ",
            code("followUp"),
            ", ",
            code("takeSteering"),
            ", ",
            code("takeFollowUp"),
            " over ",
            code("Message = { prompt }"),
          ],
        ],
        [[code("testLayer(implementation)")], "Layer from an explicit interface"],
      ],
    ),
    h2("handoff", "Handoff"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("transferTool(target, options?)")],
          ["Handled toolkit exposing ", code("transfer_to_<agent.name>"), " as a same-process handoff tool"],
        ],
        [
          [code("fanOut(children, options?)")],
          "Runs isolated child agents concurrently (default concurrency 4) and preserves input order",
        ],
        [
          [code("supervisor(options)")],
          "Builds a supervisor agent plus the handled toolkit of transfer tools for its specialists",
        ],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/instructions", "How to compose instructions and context sources"),
      ", ",
      link("/docs/guides/skills", "How to add skills"),
      ", ",
      link("/docs/guides/memory", "How to add memory"),
      ", ",
      link("/docs/guides/compaction", "How to stay inside the context window"),
      ", ",
      link("/docs/guides/steering", "How to steer and interrupt a running agent"),
      ", ",
      link("/docs/guides/multi-agent", "How to coordinate multiple agents"),
      ", and ",
      link("/docs/learn/sessions-and-history", "Sessions, history, and persistence"),
      ".",
    ),
  ],
})
