import { callout, code, command, definePage, h2, h3, lead, link, p, table } from "../../prose"
export const coreEventsReference = definePage({
  path: "/docs/reference/core-events",
  title: "AgentEvent and errors",
  navTitle: "AgentEvent",
  group: "Reference",
  description: "The closed ten-member Event union and the four error classes, with fields and emission conditions.",
  content: [
    lead(
      "AgentEvent declares the closed union of loop events every run streams, plus the four error classes a run can fail with.",
    ),
    command("Install", "bun add @batonfx/core"),
    h2("event-union", "The Event union"),
    p(
      code("AgentEvent.Event"),
      " has exactly ten members. Every member carries an optional ",
      code("metadata"),
      " escape-hatch record; ",
      code("turn"),
      " is 0-based throughout.",
    ),
    table(
      ["Event", "Fields", "Emitted when", "Notes"],
      [
        [[code("TurnStarted")], [code("turn")], "A model turn starts", "Turn 0 always runs"],
        [
          [code("ModelPart")],
          [code("turn"), ", ", code("part")],
          "The model streams a part",
          ["A raw ", code("Ai.Response.StreamPart"), " passed through unchanged"],
        ],
        [
          [code("ToolExecutionStarted")],
          [code("turn"), ", ", code("call")],
          "A tool call is about to execute via the ToolExecutor service",
          [code("call"), " is the ", code("Ai.Response.ToolCallPart")],
        ],
        [
          [code("ToolProgress")],
          [code("turn"), ", ", code("toolCallId"), ", ", code("message?"), ", ", code("data?")],
          ["A running tool emits progress through ", code("ToolContext.emit")],
          "In-flight; zero or more per call",
        ],
        [
          [code("ToolExecutionCompleted")],
          [code("turn"), ", ", code("call"), ", ", code("result")],
          "A tool call finishes",
          [code("result"), " is the tool-result part re-fed to the model"],
        ],
        [
          [code("ApprovalRequested")],
          [code("turn"), ", ", code("call")],
          ["Before consulting Approvals for a ", code("needsApproval"), " tool"],
          "Precedes Approved, Denied, or suspension",
        ],
        [
          [code("SteeringDrained")],
          [code("turn"), ", ", code('queue: "steering" | "followUp"'), ", ", code("count")],
          "Queued steering or follow-up input is drained into the next prompt",
          "Observational; never enters the transcript",
        ],
        [
          [code("TurnCompleted")],
          [code("turn"), ", ", code("transcript"), ", ", code("usage?"), ", ", code("finishReason?")],
          "A model turn completes, after that turn's tool executions",
          [
            code("transcript"),
            " is the full chat history at this point, the export point for hosts that persist conversation state durably",
          ],
        ],
        [
          [code("StructuredOutput")],
          [code("turn"), ", ", code("value"), ", ", code("content")],
          "The terminal structured turn produces a schema-validated value",
          ["Only on ", code("streamObject"), "/", code("generateObject"), " runs"],
        ],
        [
          [code("Completed")],
          [code("turns"), ", ", code("text"), ", ", code("transcript"), ", ", code("usage?")],
          "Terminal event: the run finished without suspension",
          "Always the last event of a successful run",
        ],
      ],
    ),
    h3("add-usage", "addUsage"),
    p(
      code("AgentEvent.addUsage(left, right)"),
      " returns the fieldwise sum of two ",
      code("Ai.Response.Usage"),
      " values, preserving ",
      code("undefined"),
      " when neither side reports a field.",
    ),
    h2("error-classes", "Error classes"),
    p("All four are Schema tagged error classes with frozen tags under ", code("@batonfx/core/"), "."),
    table(
      ["Error", "Fields", "Raised when"],
      [
        [
          [code("AgentError")],
          [code("message"), ", ", code("turn"), ", ", code("cause?")],
          "The loop fails; turn is the 0-based turn that failed",
        ],
        [
          [code("TurnLimitExceeded")],
          [code("turn"), ", ", code("pending: Array<{ tool_call_id, tool_name }>")],
          "The turn policy declines another turn while tool results are still pending",
        ],
        [
          [code("MiddlewareViolation")],
          [code("turn"), ", ", code("detail")],
          "A ModelMiddleware hook violates the loop contract, e.g. drops a tool-call part",
        ],
        [
          [code("AgentSuspended")],
          [
            code("token"),
            ", ",
            code('reason: "tool-wait" | "approval"'),
            ", ",
            code("tool_call_id"),
            ", ",
            code("tool_name"),
            ", ",
            code("tool_params"),
          ],
          [
            "A tool outcome was ",
            code("Suspend"),
            " or an approval decision was ",
            code("Pending"),
            "; the run did not finish",
          ],
        ],
      ],
    ),
    callout(
      "info",
      "AgentSuspended is a contract, not a failure",
      "The host resolves the token out-of-band and re-enters via ",
      code("RunOptions.resume"),
      " with the pending call. The field shape deliberately mirrors a tool call so durable hosts can persist it as one.",
    ),
    p(
      "For the loop that emits these events, see ",
      link("/docs/learn/agent-loop", "The agent loop"),
      ". For the suspension contract, see ",
      link("/docs/learn/suspension", "Suspension as a typed error"),
      " and ",
      link("/docs/guides/approvals", "How to require human approval for a tool"),
      ".",
    ),
  ],
})
