import { callout, code, command, definePage, h2, h3, lead, link, p, table } from "../../prose"
export const foldkitReference = definePage({
  path: "/docs/reference/foldkit",
  title: "@batonfx/foldkit",
  navTitle: "foldkit",
  group: "Reference",
  description: "The AgentConnection service and the headless Chat submodel for FoldKit apps.",
  content: [
    lead(
      "@batonfx/foldkit adapts the transport protocol to FoldKit's Elm architecture: Connection owns the WebSocket, Chat is a headless submodel that folds wire frames into renderable state.",
    ),
    command("Install", "bun add foldkit@0.122.0 @batonfx/transport @batonfx/foldkit"),
    p(
      "Published on npm at 0.4.0. Depends on ",
      code("@batonfx/transport"),
      "; peer dependencies are ",
      code("effect >=4.0.0-beta.88 <4.0.1"),
      " and ",
      code("foldkit >=0.122.0 <1"),
      ".",
    ),
    h2("exports", "Exports map"),
    table(["Subpath", "Contents"], [[[code(".")], ["Namespaces ", code("Chat"), " and ", code("Connection")]]]),
    h2("connection", "Connection"),
    p(
      "The ",
      code("AgentConnection"),
      " service acquires ",
      code("session({ sessionId, afterSeq? })"),
      " in the caller's Scope. The returned ",
      code("SessionConnection"),
      " owns that session's frame stream and command writes. Compatibility methods ",
      code("frames({ sessionId, afterSeq? })"),
      " and ",
      code("send(frame)"),
      " remain available; send routes only to the active connection matching the frame's session id and fails with ",
      code("SendFailed{ reason }"),
      " when ownership is missing or mismatched.",
    ),
    table(
      ["Incoming member", "Meaning"],
      [
        [[code("Wire.LooseServerFrameType")], "Any of the six server frames"],
        [[code("ConnectionOpened")], "The socket opened"],
        [[code("ConnectionLost")], "The socket is reconnecting or closed"],
        [[code("ConnectionFailed")], [code("{ reason }"), ": the frame stream failed"]],
      ],
    ),
    table(
      ["Export", "Notes"],
      [
        [
          [code("layerWebSocket({ url })")],
          [
            "Built on the transport's reconnecting client; requires ",
            code("Socket.WebSocketConstructor"),
            ". Reattaches with the last delivered ",
            code("seq"),
            " after reconnects",
          ],
        ],
        [
          [code("layerTest(implementation)")],
          "Layer from an explicit interface; legacy frames/send-only test implementations remain supported",
        ],
      ],
    ),
    callout(
      "info",
      "Custom connection provider migration",
      "Callers of frames and send require no changes. Custom providers typed as AgentConnection.Interface or built with AgentConnection.of must implement scoped session acquisition; layerTest can temporarily adapt a frames/send-only implementation.",
    ),
    h2("chat-model", "Chat.Model"),
    table(
      ["Field", "Type", "Notes"],
      [
        [[code("sessionId")], [code("string | null")], "Session bound by OpenedSession"],
        [[code("connection")], [code('"disconnected" | "connecting" | "open" | "reconnecting"')], "Socket state"],
        [[code("lastSeq")], [code("number")], "Last applied frame seq; duplicate frames are ignored"],
        [[code("run")], [code("RunState")], "Current run lifecycle"],
        [[code("entries")], [code("ReadonlyArray<ChatEntry>")], "Settled conversation entries"],
        [
          [code("streaming")],
          [code("{ turn, text, reasoning } | null")],
          "In-flight assistant text, flushed to an entry on TurnCompleted",
        ],
        [[code("draft")], [code("string")], "Prompt input value"],
      ],
    ),
    p(code("Chat.initialModel(sessionId?)"), " builds the empty model."),
    h3("run-state", "RunState"),
    table(
      ["State", "Fields"],
      [
        [[code("Idle")], "none"],
        [[code("Running")], [code("turn")]],
        [[code("AwaitingApproval")], [code("token"), ", ", code("toolName"), ", ", code("params")]],
        [[code("Failed")], [code("message")]],
      ],
    ),
    h3("chat-entry", "ChatEntry"),
    table(
      ["Entry", "Fields"],
      [
        [[code("UserEntry")], [code("text")]],
        [[code("AssistantEntry")], [code("text"), ", ", code("reasoning: string | null")]],
        [
          [code("ToolEntry")],
          [
            code("callId"),
            ", ",
            code("name"),
            ", ",
            code("params"),
            ", ",
            code('phase: "called" | "executing"'),
            ", ",
            code("outcome: Pending | Completed{ isFailure, result }"),
            ", ",
            code("progress: Array<string>"),
          ],
        ],
      ],
    ),
    h2("chat-actions", "Chat.Action"),
    p(
      "Route these through your app's action wrapper into ",
      code("Chat.update(model, action)"),
      ", which returns ",
      code("[Model, Array<ChatCommand>, Option<Output>]"),
      ".",
    ),
    table(
      ["Action", "Fields", "Meaning"],
      [
        [
          [code("ReceivedAgent")],
          [code("incoming: Connection.Incoming")],
          "A wire frame or connection status; the fold that drives everything else",
        ],
        [[code("OpenedSession")], [code("sessionId")], "Bind the session and reset the model"],
        [[code("ChangedDraft")], [code("text")], "Update the prompt draft"],
        [
          [code("SubmittedMessage")],
          "none",
          ["Append a UserEntry and dispatch the ", code("SendUserMessage"), " command"],
        ],
        [[code("ClickedCancel")], "none", ["Dispatch the ", code("CancelRun"), " command"]],
        [
          [code("ClickedApprove")],
          "none",
          ["Resolve the pending approval as Approved (only in ", code("AwaitingApproval"), ")"],
        ],
        [[code("ClickedDeny")], [code("reason: string | null")], "Resolve the pending approval as Denied"],
        [
          [code("SentUserMessage"), " / ", code("ResolvedApproval"), " / ", code("CancelledRun")],
          "none",
          "Command completions; no model change",
        ],
        [[code("FailedAgentCommand")], [code("reason")], ["Command failure; sets ", code("run"), " to Failed"]],
      ],
    ),
    p(
      code("Output"),
      " surfaces run milestones to the host app: ",
      code("RunCompleted{ text }"),
      ", ",
      code("ApprovalRequired"),
      ", ",
      code("RunFailed{ message }"),
      ".",
    ),
    h2("commands-subscriptions", "Commands and subscriptions"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("SendUserMessage"), " / ", code("ResolveApproval"), " / ", code("CancelRun")],
          ["FoldKit commands over ", code("AgentConnection.send"), "; failures become ", code("FailedAgentCommand")],
        ],
        [
          [code("subscriptions")],
          [
            "Keyed on ",
            code("sessionId"),
            "; acquires a scoped ",
            code("SessionConnection"),
            " and streams its frames ",
            " from ",
            code("model.lastSeq"),
            " and wraps each value in ",
            code("ReceivedAgent"),
            ". Lift with ",
            code("Subscription.lift"),
          ],
        ],
      ],
    ),
    h2("view-helpers", "View helpers"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("conversationItems(model)")],
          [
            "Projects the model into a keyed, aligned ",
            code("ConversationItem"),
            " list: entries, the streaming item, a waiting placeholder, the approval card, and the failure item",
          ],
        ],
        [
          [code("promptInputStatusOf(run)")],
          [code('"idle" | "submitted" | "streaming" | "error"'), " for prompt inputs"],
        ],
        [
          [code("toolStatusOf(entry)")],
          [code('"input-streaming" | "input-available" | "output-available" | "output-error"'), " for tool cards"],
        ],
      ],
    ),
    callout(
      "info",
      "Tool-wait suspensions are not resolvable here",
      "The adapter resolves approval suspensions only; a ",
      code("tool-wait"),
      " suspension folds to a Failed run state, since resolving it requires a host-side executor.",
    ),
    p(
      "See ",
      link("/docs/guides/foldkit-chat", "How to build a chat UI with FoldKit"),
      " and ",
      link("/docs/guides/serve-transport", "How to serve an agent over SSE and WebSocket"),
      ".",
    ),
  ],
})
