import { code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const memoryReference = definePage({
  path: "/docs/reference/memory",
  title: "tenetkit/memory",
  navTitle: "memory",
  group: "Reference",
  description: "WorkingMemory, SemanticRecall, the VectorStore seam, and the combined layer.",
  content: [
    lead(
      "tenetkit/memory implements the core Memory seam twice (a recency window with optional summarization, and embedding-based semantic recall) plus the VectorStore seam they share.",
    ),
    command("Install", "bun add tenetkit tenetkit/memory"),
    p("Published on npm at 0.14.0. Requires ", code("tenetkit"), "."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("WorkingMemory"),
            ", ",
            code("SemanticRecall"),
            ", ",
            code("VectorStore"),
            ", plus ",
            code("layerCombined"),
          ],
        ],
      ],
    ),
    h2("working-memory", "WorkingMemory"),
    p(
      code("WorkingMemory.layer(options?)"),
      " provides ",
      code("Memory.Memory"),
      " backed by an in-process store per ",
      code("Memory.Key"),
      ". It keeps the most recent user/assistant text messages verbatim; overflow beyond the window is optionally folded into a rolling summary. Recall returns the summary (wrapped in ",
      code("<working-memory-summary>"),
      " tags) followed by the recent items.",
    ),
    table(
      ["Option", "Default", "Notes"],
      [
        [[code("maxMessages")], [code("20")], "Recency window size"],
        [
          [code("summarize")],
          "disabled",
          [
            "Enables overflow summarization and requires ",
            code("WorkingMemory.SummaryModel"),
            ", normally composed through ",
            code("WorkingMemory.layerSummaryModel"),
          ],
        ],
        [[code("summarize.prompt")], "built-in summary prompt", "Instruction for folding overflow into the summary"],
      ],
    ),
    h2("semantic-recall", "SemanticRecall"),
    p(
      code("SemanticRecall.layer(options?)"),
      " provides ",
      code("Memory.Memory"),
      " and requires ",
      code("VectorStore"),
      " and ",
      code("Ai.EmbeddingModel"),
      ". Recall embeds the run's user text and queries the store; remember fires only on terminal runs, embedding the final user/assistant exchange as one document.",
    ),
    table(
      ["Option", "Default", "Notes"],
      [
        [[code("limit")], [code("5")], "Maximum matches returned per recall"],
        [[code("minScore")], "none", "Minimum cosine score to include a match"],
      ],
    ),
    p("Match metadata carries the source document metadata plus ", code("score"), "."),
    h2("vector-store", "VectorStore"),
    p(
      "The storage seam: ",
      code("{ upsert(documents), query(query) }"),
      " failing with ",
      code("VectorStoreError"),
      ". Documents are scoped by ",
      code("Memory.Key"),
      "; queries never cross keys.",
    ),
    table(
      ["Type", "Shape"],
      [
        [[code("Document")], [code("{ id, key, text, metadata? }")]],
        [[code("Embedded")], [code("Document"), " plus ", code("{ embedding: ReadonlyArray<number> }")]],
        [[code("Match")], [code("{ document: Embedded, score: number }")]],
        [[code("Query")], [code("{ key, embedding, limit, minScore? }")]],
      ],
    ),
    p(
      code("VectorStore.layerMemory"),
      " is the in-process implementation using cosine similarity; it rejects non-finite vectors and mismatched dimensions. ",
      code("layerTest(implementation)"),
      " wraps an explicit interface; a Postgres/pgvector store implements the same two functions.",
    ),
    h2("combined", "layerCombined"),
    p(
      code("layerCombined({ working?, semantic? })"),
      " merges both implementations with ",
      code("Memory.merge"),
      ": recalls concatenate (working first), remembers fan out. It carries SemanticRecall's requirements (",
      code("VectorStore"),
      " and ",
      code("Ai.EmbeddingModel"),
      "). Enabling ",
      code("working.summarize"),
      " also requires ",
      code("WorkingMemory.SummaryModel"),
      ".",
    ),
    p(
      "Embedding layers live in ",
      link("/docs/reference/providers", "tenetkit/ai"),
      ". See ",
      link("/docs/guides/memory", "How to add memory"),
      ".",
    ),
  ],
})
