import * as Prose from "../../prose"

export const providersReference = Prose.definePage({
  path: "/docs/reference/providers",
  title: "@batonfx/providers",
  navTitle: "providers",
  group: "Reference",
  description: "Provider registrations, deterministic fallback, OpenAI-compatible presets, catalog, and embeddings.",
  content: [
    Prose.lead(
      "@batonfx/providers binds real model providers to the ModelRegistry: registration helpers per provider, a deterministic model for tests, seven OpenAI-compatible presets, a static model catalog, and embedding layers.",
    ),
    Prose.command("Install", "bun add @batonfx/core @batonfx/providers"),
    Prose.p("Published on npm. Requires ", Prose.code("@batonfx/core"), " and the pinned effect version."),
    Prose.h2("exports", "Exports map"),
    Prose.table(
      ["Subpath", "Contents"],
      [
        [
          [Prose.code(".")],
          [
            "Namespaces ",
            Prose.code("Anthropic"),
            ", ",
            Prose.code("Catalog"),
            ", ",
            Prose.code("Deterministic"),
            ", ",
            Prose.code("Embedding"),
            ", ",
            Prose.code("OpenAi"),
            ", ",
            Prose.code("OpenAiCompatible"),
            ", ",
            Prose.code("OpenRouter"),
            ", ",
            Prose.code("Presets"),
          ],
        ],
        [
          [Prose.code("./openai")],
          [Prose.code("openAi"), ", ", Prose.code("withOpenAi"), ", ", Prose.code("openAiClientLayerConfig")],
        ],
        [
          [Prose.code("./anthropic")],
          [Prose.code("anthropic"), ", ", Prose.code("withAnthropic"), ", ", Prose.code("anthropicClientLayerConfig")],
        ],
        [
          [Prose.code("./openrouter")],
          [
            Prose.code("openRouter"),
            ", ",
            Prose.code("withOpenRouter"),
            ", ",
            Prose.code("openRouterClientLayerConfig"),
          ],
        ],
        [
          [Prose.code("./openai-compat")],
          [
            Prose.code("openAiCompatible"),
            ", ",
            Prose.code("withOpenAiCompatible"),
            ", ",
            Prose.code("openAiCompatibleClientLayerConfig"),
          ],
        ],
        [
          [Prose.code("./deterministic")],
          [
            Prose.code("deterministicModel"),
            ", ",
            Prose.code("withDeterministic"),
            ", ",
            Prose.code("withOpenAiOrDeterministic"),
          ],
        ],
        [[Prose.code("./presets")], "The seven OpenAI-compatible presets"],
        [
          [Prose.code("./embedding")],
          [Prose.code("withOpenAiEmbedding"), ", ", Prose.code("withOpenAiCompatibleEmbedding")],
        ],
        [
          [Prose.code("./catalog")],
          [Prose.code("ModelCatalog"), " service, ", Prose.code("bundled"), " metadata, layers"],
        ],
      ],
    ),
    Prose.h2("registrations", "Provider registrations"),
    Prose.p(
      "Each provider module exports two shapes. The lowercase helper (",
      Prose.code("openAi"),
      ", ",
      Prose.code("anthropic"),
      ", ",
      Prose.code("openRouter"),
      ", ",
      Prose.code("openAiCompatible"),
      ") builds a ",
      Prose.code("ModelRegistry.Registration"),
      " effect that still needs the provider client in context. The ",
      Prose.code("with*"),
      " helper (",
      Prose.code("withOpenAi"),
      ", ",
      Prose.code("withAnthropic"),
      ", ",
      Prose.code("withOpenRouter"),
      ", ",
      Prose.code("withOpenAiCompatible"),
      ") takes ",
      Prose.code("apiKey"),
      " and ",
      Prose.code("clientConfig"),
      " and returns a self-contained ",
      Prose.code("ModelRegistry.Service"),
      " layer.",
    ),
    Prose.callout(
      "warning",
      "Registry layers require ModelRegistry.provide",
      "All ",
      Prose.code("with*"),
      " helpers return registry layers, not LanguageModel layers. Wrap the run in ",
      Prose.code("ModelRegistry.provide({ provider, model }, effect)"),
      " to supply the actual model per run.",
    ),
    Prose.h2("deterministic", "Deterministic"),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("deterministicModel(input?)")],
          [
            "Registration for a scripted model that always answers ",
            Prose.code('"deterministic response"'),
            "; provider and model both default to ",
            Prose.code('"deterministic"'),
          ],
        ],
        [[Prose.code("withDeterministic(input?)")], "Registry layer containing only the deterministic registration"],
        [
          [Prose.code("withOpenAiOrDeterministic(options)")],
          [
            "Registry layer with the deterministic fallback (",
            Prose.code("fallbackModel"),
            " required) plus the OpenAI registration when its config resolves; a missing API key falls back silently",
          ],
        ],
      ],
    ),
    Prose.h2("presets", "Presets"),
    Prose.p(
      "Each preset pairs a registration effect with a ",
      Prose.code("with*"),
      " registry layer over the OpenAI-compatible client, pinned to the provider's base URL. ",
      Prose.code("PresetInput"),
      " takes ",
      Prose.code("model"),
      ", optional ",
      Prose.code("apiKey"),
      ", ",
      Prose.code("clientConfig"),
      ", ",
      Prose.code("config"),
      ", ",
      Prose.code("registrationKey"),
      ", and ",
      Prose.code("metadata"),
      ".",
    ),
    Prose.table(
      ["Preset", "Provider name", "Base URL"],
      [
        [
          [Prose.code("groq"), " / ", Prose.code("withGroq")],
          [Prose.code("groq")],
          [Prose.code("https://api.groq.com/openai/v1")],
        ],
        [
          [Prose.code("mistral"), " / ", Prose.code("withMistral")],
          [Prose.code("mistral")],
          [Prose.code("https://api.mistral.ai/v1")],
        ],
        [[Prose.code("xai"), " / ", Prose.code("withXai")], [Prose.code("xai")], [Prose.code("https://api.x.ai/v1")]],
        [
          [Prose.code("deepseek"), " / ", Prose.code("withDeepseek")],
          [Prose.code("deepseek")],
          [Prose.code("https://api.deepseek.com/v1")],
        ],
        [
          [Prose.code("googleAiStudio"), " / ", Prose.code("withGoogleAiStudio")],
          [Prose.code("google")],
          [Prose.code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [
          [Prose.code("azureOpenAi"), " / ", Prose.code("withAzureOpenAi")],
          [Prose.code("azure")],
          [Prose.code("https://<resource>.openai.azure.com/openai/v1"), " — takes a required ", Prose.code("resource")],
        ],
        [
          [Prose.code("ollama"), " / ", Prose.code("withOllama")],
          [Prose.code("ollama")],
          [Prose.code("http://localhost:11434/v1")],
        ],
      ],
    ),
    Prose.h2("catalog", "Catalog"),
    Prose.p(
      Prose.code("ModelCatalog"),
      " is a static-metadata service: ",
      Prose.code("lookup(selection)"),
      ", ",
      Prose.code("require(selection)"),
      " (fails with ",
      Prose.code("ModelMetadataNotFound"),
      "), and ",
      Prose.code("all"),
      ". ",
      Prose.code("ModelMetadata"),
      " carries ",
      Prose.code("provider"),
      ", ",
      Prose.code("model"),
      ", ",
      Prose.code("contextWindow"),
      ", ",
      Prose.code("maxOutput"),
      ", optional ",
      Prose.code("pricing"),
      " and ",
      Prose.code("modalities"),
      ". ",
      Prose.code("bundled"),
      " is a hand-maintained snapshot of six entries; ",
      Prose.code("layer(overrides?)"),
      " merges overrides over it, ",
      Prose.code("testLayer(entries)"),
      " uses exactly the given entries.",
    ),
    Prose.h2("embedding", "Embedding"),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("withOpenAiEmbedding({ model, apiKey, clientConfig?, config? })")],
          [Prose.code("Ai.EmbeddingModel"), " layer over the OpenAI client"],
        ],
        [
          [Prose.code("withOpenAiCompatibleEmbedding({ model, baseUrl, apiKey?, clientConfig?, config? })")],
          ["The same over any OpenAI-compatible endpoint at ", Prose.code("baseUrl")],
        ],
      ],
    ),
    Prose.p(
      "See ",
      Prose.link("/docs/guides/providers", "How to register real model providers"),
      " and ",
      Prose.link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
