import { callout, code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const providersReference = definePage({
  path: "/docs/reference/providers",
  title: "tenetkit/ai",
  navTitle: "providers",
  group: "Reference",
  description: "Provider registrations, deterministic fallback, OpenAI-compatible presets, catalog, and embeddings.",
  content: [
    lead(
      "tenetkit/ai binds OpenAI, Anthropic, OpenRouter, Amazon Bedrock, and OpenAI-compatible endpoints to the ModelRegistry. It also provides a deterministic model for tests, seven Chat Completions presets, a static model catalog, and embedding layers.",
    ),
    command("Install", "bun add tenetkit tenetkit/ai"),
    p("Published on npm. Requires ", code("tenetkit"), " and the pinned effect version."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("AmazonBedrock"),
            ", ",
            code("Anthropic"),
            ", ",
            code("Catalog"),
            ", ",
            code("Deterministic"),
            ", ",
            code("Embedding"),
            ", ",
            code("OpenAi"),
            ", ",
            code("OpenAiAccountAuth"),
            ", ",
            code("OpenAiAccountAuthHttp"),
            ", ",
            code("OpenAiChatCompletions"),
            ", ",
            code("OpenAiResponses"),
            ", ",
            code("OpenRouter"),
            ", ",
            code("Presets"),
          ],
        ],
        [
          [code("./openai")],
          [
            code("layer"),
            ", ",
            code("layerAccount"),
            ", ",
            code("credentialsFromAccountAuth"),
            ", ",
            code("layerConfig"),
          ],
        ],
        [
          [code("./openai-account-auth")],
          ["OpenAI account OAuth protocol, token documents, lifecycle services, and host/storage seams"],
        ],
        [[code("./openai-account-auth-http")], "Standard OpenAI account authorization HTTP layer"],
        [[code("./anthropic")], [code("layer"), ", ", code("layerConfig")]],
        [[code("./amazon-bedrock")], [code("layer"), ", client, credentials, and request configuration"]],
        [[code("./openrouter")], [code("layer"), ", ", code("layerConfig")]],
        [[code("./openai-responses")], [code("layer"), ", ", code("layerConfig"), ", ", code("decodeConfig")]],
        [[code("./openai-chat-completions")], [code("layer"), ", ", code("layerConfig"), ", ", code("decodeConfig")]],
        [[code("./deterministic")], [code("layer"), ", ", code("layerOpenAi")]],
        [[code("./presets")], "The seven OpenAI-compatible presets"],
        [[code("./embedding")], ["OpenAI and compatible embedding layers"]],
        [[code("./catalog")], [code("ModelCatalog"), " service, ", code("bundled"), " metadata, layers"]],
      ],
    ),
    h2("registrations", "Provider registrations"),
    p(
      "HTTP provider ",
      code("layer"),
      " takes ",
      code("apiKey"),
      " and ",
      code("clientConfig"),
      " and returns an integrated ",
      code("ModelRegistry.ModelRegistry"),
      " layer requiring ",
      code("HttpClient.HttpClient"),
      ". Callers that select the global fetch transport explicitly compose ",
      code("FetchHttpClient.layer"),
      ".",
    ),
    p(
      "OpenAI, Anthropic, and OpenRouter registrations include provider-specific context-overflow classification. Unknown OpenAI-compatible endpoints classify no failures unless ",
      code("classifyFailure"),
      " is explicitly supplied, such as ",
      code("OpenAi.classifyFailure"),
      " for an endpoint known to preserve OpenAI failure semantics.",
    ),
    h2("openai-protocols", "OpenAI protocol adapters"),
    table(
      ["Export", "Default provider", "Endpoint"],
      [
        [[code("OpenAi.layer")], [code("openai")], [code("/responses"), " on the OpenAI API"]],
        [
          [code("OpenAiResponses.layer")],
          [code("openai-responses")],
          [code("/responses"), " on a configurable ", code("baseUrl")],
        ],
        [
          [code("OpenAiChatCompletions.layer")],
          [code("openai-chat-completions")],
          [code("/chat/completions"), " on a configurable ", code("baseUrl")],
        ],
      ],
    ),
    p(
      "The compatible adapters accept an optional custom ",
      code("provider"),
      " identity, arbitrary model string, provider config, API key, client config, base URL, registration key, metadata, and failure classifier. Unknown endpoints intentionally have no context-overflow classifier unless the caller supplies one.",
    ),
    p(
      code("OpenAiResponses.decodeConfig"),
      " validates persisted Responses options against the OpenAI schema. ",
      code("OpenAiChatCompletions.decodeConfig"),
      " accepts arbitrary JSON options for provider extensions while rejecting a nested ",
      code("model"),
      " override; the registry selection remains the model authority.",
    ),
    h2("amazon-bedrock", "Amazon Bedrock"),
    p(
      code("AmazonBedrock.layer({ model, config?, client? })"),
      " registers ",
      code('provider: "amazon-bedrock"'),
      " for any foundation-model ID, inference-profile ID, or ARN. ",
      code("client"),
      " accepts region, endpoint, profile, refreshable credentials, redacted bearer token, authentication mode, request handler, and an optional coalesced credential-recovery effect. The default region is ",
      code("us-east-1"),
      ".",
    ),
    p(
      "Converse and ConverseStream preserve text, reasoning, tool calls, structured output, cache usage, request identity, stop reason, latency, trace, and additional response fields. Mid-stream service, throttling, validation, and model-stream exceptions fail with typed retry-aware AI reasons. Malformed lifecycle sequences fail as invalid output, while unknown future AWS union members are ignored without weakening validation of known events.",
    ),
    callout(
      "info",
      "The host owns HTTP",
      "Supply a traced, proxied, test, or platform HttpClient, or explicitly provide FetchHttpClient.layer when the global fetch transport is intentional.",
    ),
    callout(
      "warning",
      "Registry layers require ModelRegistry.operate",
      "Provider constructors return registry layers, not LanguageModel layers. Wrap the run in ",
      code("ModelRegistry.operate({ provider, model }, effect)"),
      " to supply the actual model per run.",
    ),
    h2("deterministic", "Deterministic"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("layer(input?)")],
          [
            "Registry layer for a scripted model that always answers ",
            code('"deterministic response"'),
            "; provider and model both default to ",
            code('"deterministic"'),
          ],
        ],
        [
          [code("layerOpenAi(options)")],
          [
            "Registry layer with the deterministic fallback (",
            code("fallbackModel"),
            " required) plus the OpenAI registration when its API-key config is present; only missing data falls back, while invalid or failing config remains a typed failure",
          ],
        ],
      ],
    ),
    h2("presets", "Presets"),
    p(
      "Each preset is a registry layer over the OpenAI-compatible client, pinned to the provider's base URL. ",
      code("PresetInput"),
      " takes ",
      code("model"),
      ", optional ",
      code("apiKey"),
      ", ",
      code("clientConfig"),
      ", ",
      code("config"),
      ", ",
      code("registrationKey"),
      ", ",
      code("metadata"),
      ", and an optional ",
      code("classifyFailure"),
      ". Presets classify no failures unless callers supply that classifier. Every preset layer requires HttpClient; callers choosing fetch explicitly compose FetchHttpClient.layer.",
    ),
    table(
      ["Preset", "Provider name", "Base URL"],
      [
        [[code("layerGroq")], [code("groq")], [code("https://api.groq.com/openai/v1")]],
        [[code("layerMistral")], [code("mistral")], [code("https://api.mistral.ai/v1")]],
        [[code("layerXai")], [code("xai")], [code("https://api.x.ai/v1")]],
        [[code("layerDeepseek")], [code("deepseek")], [code("https://api.deepseek.com/v1")]],
        [
          [code("layerGoogleAiStudio")],
          [code("google")],
          [code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [
          [code("layerAzureOpenAi")],
          [code("azure")],
          [code("https://<resource>.openai.azure.com/openai/v1"), ": takes a required ", code("resource")],
        ],
        [[code("layerOllama")], [code("ollama")], [code("http://localhost:11434/v1")]],
      ],
    ),
    h2("catalog", "Catalog"),
    p(
      code("ModelCatalog"),
      " is a static-metadata service: ",
      code("lookup(selection)"),
      ", ",
      code("require(selection)"),
      " (fails with ",
      code("ModelMetadataNotFound"),
      "), and ",
      code("all"),
      ". ",
      code("ModelMetadata"),
      " carries ",
      code("provider"),
      ", ",
      code("model"),
      ", ",
      code("contextWindow"),
      ", ",
      code("maxOutput"),
      ", optional ",
      code("pricing"),
      " and ",
      code("modalities"),
      ". ",
      code("bundled"),
      " is a hand-maintained snapshot of six entries; ",
      code("layer(overrides?)"),
      " merges overrides over it, ",
      code("layerTest(entries)"),
      " uses exactly the given entries.",
    ),
    h2("embedding", "Embedding"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("layer({ model, apiKey, clientConfig?, config? })")],
          [code("Ai.EmbeddingModel"), " layer over the OpenAI client requiring ", code("HttpClient")],
        ],
        [
          [code("layerCompatible({ model, baseUrl, apiKey?, clientConfig?, config? })")],
          ["The same over any OpenAI-compatible endpoint at ", code("baseUrl"), ", requiring ", code("HttpClient")],
        ],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/providers", "How to register real model providers"),
      " and ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
