import { callout, code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const providersReference = definePage({
  path: "/docs/reference/providers",
  title: "@batonfx/providers",
  navTitle: "providers",
  group: "Reference",
  description: "Provider registrations, deterministic fallback, OpenAI-compatible presets, catalog, and embeddings.",
  content: [
    lead(
      "@batonfx/providers binds real model providers to the ModelRegistry: registration helpers per provider, a deterministic model for tests, seven OpenAI-compatible presets, a static model catalog, and embedding layers.",
    ),
    command("Install", "bun add @batonfx/core @batonfx/providers"),
    p("Published on npm. Requires ", code("@batonfx/core"), " and the pinned effect version."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("Anthropic"),
            ", ",
            code("Catalog"),
            ", ",
            code("Deterministic"),
            ", ",
            code("Embedding"),
            ", ",
            code("OpenAi"),
            ", ",
            code("OpenAiCompatible"),
            ", ",
            code("OpenRouter"),
            ", ",
            code("Presets"),
          ],
        ],
        [
          [code("./openai")],
          [
            code("openAi"),
            ", ",
            code("withOpenAi"),
            ", ",
            code("withOpenAiFetch"),
            ", ",
            code("openAiClientLayerConfig"),
          ],
        ],
        [
          [code("./anthropic")],
          [
            code("anthropic"),
            ", ",
            code("withAnthropic"),
            ", ",
            code("withAnthropicFetch"),
            ", ",
            code("anthropicClientLayerConfig"),
          ],
        ],
        [
          [code("./openrouter")],
          [
            code("openRouter"),
            ", ",
            code("withOpenRouter"),
            ", ",
            code("withOpenRouterFetch"),
            ", ",
            code("openRouterClientLayerConfig"),
          ],
        ],
        [
          [code("./openai-compat")],
          [
            code("openAiCompatible"),
            ", ",
            code("withOpenAiCompatible"),
            ", ",
            code("withOpenAiCompatibleFetch"),
            ", ",
            code("openAiCompatibleClientLayerConfig"),
          ],
        ],
        [
          [code("./deterministic")],
          [
            code("deterministicModel"),
            ", ",
            code("withDeterministic"),
            ", ",
            code("withOpenAiOrDeterministic"),
            ", ",
            code("withOpenAiOrDeterministicFetch"),
          ],
        ],
        [[code("./presets")], "The seven OpenAI-compatible presets"],
        [
          [code("./embedding")],
          ["OpenAI and compatible embedding layers, each with a matching ", code("*Fetch"), " convenience"],
        ],
        [[code("./catalog")], [code("ModelCatalog"), " service, ", code("bundled"), " metadata, layers"]],
      ],
    ),
    h2("registrations", "Provider registrations"),
    p(
      "Each provider module exports two shapes. The lowercase helper (",
      code("openAi"),
      ", ",
      code("anthropic"),
      ", ",
      code("openRouter"),
      ", ",
      code("openAiCompatible"),
      ") builds a ",
      code("ModelRegistry.Registration"),
      " effect that still needs the provider client in context. The ",
      code("with*"),
      " helper (",
      code("withOpenAi"),
      ", ",
      code("withAnthropic"),
      ", ",
      code("withOpenRouter"),
      ", ",
      code("withOpenAiCompatible"),
      ") takes ",
      code("apiKey"),
      " and ",
      code("clientConfig"),
      " and returns an integrated ",
      code("ModelRegistry.Service"),
      " layer requiring ",
      code("HttpClient.HttpClient"),
      ". Each matching ",
      code("with*Fetch"),
      " convenience explicitly provides ",
      code("FetchHttpClient.layer"),
      ".",
    ),
    callout(
      "info",
      "The host owns HTTP",
      "Use the base ",
      code("with*"),
      " layer when your application supplies a traced, proxied, test, or platform HttpClient. Use ",
      code("with*Fetch"),
      " only when selecting the global fetch transport is intentional.",
    ),
    callout(
      "warning",
      "Migration from implicit fetch",
      "When upgrading, replace an existing ",
      code("withX(options)"),
      " call with ",
      code("withXFetch(options)"),
      " to retain its previous fetch-backed behavior. Keep the base name only when supplying a host HttpClient.",
    ),
    callout(
      "warning",
      "Registry layers require ModelRegistry.provide",
      "All ",
      code("with*"),
      " helpers return registry layers, not LanguageModel layers. Wrap the run in ",
      code("ModelRegistry.provide({ provider, model }, effect)"),
      " to supply the actual model per run.",
    ),
    h2("deterministic", "Deterministic"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("deterministicModel(input?)")],
          [
            "Registration for a scripted model that always answers ",
            code('"deterministic response"'),
            "; provider and model both default to ",
            code('"deterministic"'),
          ],
        ],
        [[code("withDeterministic(input?)")], "Registry layer containing only the deterministic registration"],
        [
          [code("withOpenAiOrDeterministic(options)")],
          [
            "Registry layer with the deterministic fallback (",
            code("fallbackModel"),
            " required) plus the OpenAI registration when its config resolves; a missing API key falls back silently",
          ],
        ],
        [
          [code("withOpenAiOrDeterministicFetch(options)")],
          ["The same fallback registry with ", code("FetchHttpClient.layer"), " explicitly provided"],
        ],
      ],
    ),
    h2("presets", "Presets"),
    p(
      "Each preset pairs a registration effect with a ",
      code("with*"),
      " registry layer over the OpenAI-compatible client, pinned to the provider's base URL. ",
      code("PresetInput"),
      " takes ",
      code("model"),
      ", optional ",
      code("apiKey"),
      ", ",
      code("clientConfig"),
      ", ",
      code("config"),
      ", ",
      code("registrationKey"),
      ", and ",
      code("metadata"),
      ". Base registration and layer names require HttpClient; append ",
      code("Fetch"),
      " to either name for the explicit fetch-backed convenience.",
    ),
    table(
      ["Preset", "Provider name", "Base URL"],
      [
        [[code("groq"), " / ", code("withGroq")], [code("groq")], [code("https://api.groq.com/openai/v1")]],
        [[code("mistral"), " / ", code("withMistral")], [code("mistral")], [code("https://api.mistral.ai/v1")]],
        [[code("xai"), " / ", code("withXai")], [code("xai")], [code("https://api.x.ai/v1")]],
        [[code("deepseek"), " / ", code("withDeepseek")], [code("deepseek")], [code("https://api.deepseek.com/v1")]],
        [
          [code("googleAiStudio"), " / ", code("withGoogleAiStudio")],
          [code("google")],
          [code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [
          [code("azureOpenAi"), " / ", code("withAzureOpenAi")],
          [code("azure")],
          [code("https://<resource>.openai.azure.com/openai/v1"), ": takes a required ", code("resource")],
        ],
        [[code("ollama"), " / ", code("withOllama")], [code("ollama")], [code("http://localhost:11434/v1")]],
      ],
    ),
    h2("catalog", "Catalog"),
    p(
      code("ModelCatalog"),
      " is a static-metadata service: ",
      code("lookup(selection)"),
      ", ",
      code("require(selection)"),
      " (fails with ",
      code("ModelMetadataNotFound"),
      "), and ",
      code("all"),
      ". ",
      code("ModelMetadata"),
      " carries ",
      code("provider"),
      ", ",
      code("model"),
      ", ",
      code("contextWindow"),
      ", ",
      code("maxOutput"),
      ", optional ",
      code("pricing"),
      " and ",
      code("modalities"),
      ". ",
      code("bundled"),
      " is a hand-maintained snapshot of six entries; ",
      code("layer(overrides?)"),
      " merges overrides over it, ",
      code("testLayer(entries)"),
      " uses exactly the given entries.",
    ),
    h2("embedding", "Embedding"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("withOpenAiEmbedding({ model, apiKey, clientConfig?, config? })")],
          [code("Ai.EmbeddingModel"), " layer over the OpenAI client requiring ", code("HttpClient")],
        ],
        [
          [code("withOpenAiCompatibleEmbedding({ model, baseUrl, apiKey?, clientConfig?, config? })")],
          ["The same over any OpenAI-compatible endpoint at ", code("baseUrl"), ", requiring ", code("HttpClient")],
        ],
        [[code("withOpenAiEmbeddingFetch(...)")], ["OpenAI embeddings with fetch explicitly provided"]],
        [
          [code("withOpenAiCompatibleEmbeddingFetch(...)")],
          ["OpenAI-compatible embeddings with fetch explicitly provided"],
        ],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/providers", "How to register real model providers"),
      " and ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
