import * as Prose from "../../prose"

export const skillsReference = Prose.definePage({
  path: "/docs/reference/skills",
  title: "@batonfx/skills",
  navTitle: "skills",
  group: "Reference",
  description: "SkillLoader for filesystem SKILL.md discovery and InstructionFiles for AGENTS.md/CLAUDE.md loading.",
  content: [
    Prose.lead(
      "@batonfx/skills implements the core SkillSource seam from the filesystem: SkillLoader discovers SKILL.md files, and InstructionFiles loads AGENTS.md/CLAUDE.md instruction files.",
    ),
    Prose.command("Install", "bun add @batonfx/core @batonfx/skills"),
    Prose.p("Published on npm at 0.1.1. Requires ", Prose.code("@batonfx/core"), "."),
    Prose.h2("exports", "Exports map"),
    Prose.table(
      ["Subpath", "Contents"],
      [[[Prose.code(".")], ["Namespaces ", Prose.code("SkillLoader"), " and ", Prose.code("InstructionFiles")]]],
    ),
    Prose.h2("skill-loader", "SkillLoader.layer"),
    Prose.p(
      Prose.code("SkillLoader.layer(options?)"),
      " builds a ",
      Prose.code("SkillSource.SkillSource"),
      " layer requiring ",
      Prose.code("FileSystem"),
      " and ",
      Prose.code("Path"),
      ", failing with ",
      Prose.code("SkillSourceError"),
      ". Roots are scanned in order; later roots override earlier ones by skill name.",
    ),
    Prose.table(
      ["Option", "Default", "Notes"],
      [
        [
          [Prose.code("roots")],
          [Prose.code('[".agents/skills", ".claude/skills", ".pi/skills"]')],
          "Absolute or resolved against cwd",
        ],
        [[Prose.code("cwd")], [Prose.code('"."')], "Base directory for relative roots"],
        [
          [Prose.code("descriptionCap")],
          [Prose.code("SkillSource.DESCRIPTION_CAP"), " (1536)"],
          "Per-entry listing description cap in characters",
        ],
        [
          [Prose.code("frontmatterMaxBytes")],
          [Prose.code("65536")],
          "Bytes read when parsing only the frontmatter header",
        ],
      ],
    ),
    Prose.p(
      "Discovery finds every ",
      Prose.code("SKILL.md"),
      " under each root recursively. Skill names namespace by directory: a file at ",
      Prose.code("web/search/SKILL.md"),
      " becomes ",
      Prose.code("web:search"),
      " unless the frontmatter sets an explicit ",
      Prose.code("name"),
      " containing a colon. Bodies load lazily; listing skills reads only headers.",
    ),
    Prose.h2("skill-md", "The SKILL.md contract"),
    Prose.p(
      "A document is YAML-like frontmatter between ",
      Prose.code("---"),
      " fences followed by the Markdown body. ",
      Prose.code("description"),
      " is required; keys are matched ignoring case, hyphens, and underscores.",
    ),
    Prose.table(
      ["Key", "Type", "Notes"],
      [
        [[Prose.code("name")], "string", "Overrides the directory-derived name"],
        [[Prose.code("description")], "string", "Required; shown in the startup listing"],
        [[Prose.code("when-to-use")], "string", "Optional usage hint"],
        [[Prose.code("allowed-tools")], "string array", "Inline or dash-list form"],
        [[Prose.code("disable-model-invocation")], "boolean", "Excluded from model-facing listings when true"],
        [[Prose.code("user-invocable")], "boolean", "Optional flag"],
        [[Prose.code("context-fork")], "boolean", "Optional flag"],
        [[Prose.code("agent")], "string", "Optional agent binding"],
        [[Prose.code("model")], "string", "Optional model hint"],
        [[Prose.code("paths")], "string array", "Optional related paths"],
      ],
    ),
    Prose.h2("instruction-files", "InstructionFiles.loadInstructionFiles"),
    Prose.p(
      Prose.code("loadInstructionFiles(options?)"),
      " returns ",
      Prose.code("ReadonlyArray<InstructionFile>"),
      " (",
      Prose.code("{ path, content }"),
      "), requiring ",
      Prose.code("FileSystem"),
      " and ",
      Prose.code("Path"),
      ". It reads ",
      Prose.code("globalFiles"),
      " first, then walks from the filesystem root down to ",
      Prose.code("cwd"),
      ", taking the first matching filename per directory.",
    ),
    Prose.table(
      ["Option", "Default"],
      [
        [[Prose.code("filenames")], [Prose.code('["AGENTS.md", "CLAUDE.md"]')]],
        [[Prose.code("cwd")], [Prose.code('"."')]],
        [[Prose.code("globalFiles")], [Prose.code("[]")]],
      ],
    ),
    Prose.p(
      "See ",
      Prose.link("/docs/guides/skills", "How to add skills"),
      " and ",
      Prose.link("/docs/guides/instructions", "How to compose instructions and context sources"),
      ".",
    ),
  ],
})
