import { code, command, definePage, h2, lead, link, p, table } from "../../prose"
export const skillsReference = definePage({
  path: "/docs/reference/skills",
  title: "@batonfx/skills",
  navTitle: "skills",
  group: "Reference",
  description: "SkillLoader for filesystem SKILL.md discovery and InstructionFiles for AGENTS.md/CLAUDE.md loading.",
  content: [
    lead(
      "@batonfx/skills implements the core SkillSource seam from the filesystem: SkillLoader discovers SKILL.md files, and InstructionFiles loads AGENTS.md/CLAUDE.md instruction files.",
    ),
    command("Install", "bun add @batonfx/core @batonfx/skills"),
    p("Published on npm at 0.1.1. Requires ", code("@batonfx/core"), "."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [[[code(".")], ["Namespaces ", code("SkillLoader"), " and ", code("InstructionFiles")]]],
    ),
    h2("skill-loader", "SkillLoader.layer"),
    p(
      code("SkillLoader.layer(options?)"),
      " builds a ",
      code("SkillSource.SkillSource"),
      " layer requiring ",
      code("FileSystem"),
      " and ",
      code("Path"),
      ", failing with ",
      code("SkillSourceError"),
      ". Roots are scanned in order; later roots override earlier ones by skill name.",
    ),
    table(
      ["Option", "Default", "Notes"],
      [
        [
          [code("roots")],
          [code('[".agents/skills", ".claude/skills", ".pi/skills"]')],
          "Absolute or resolved against cwd",
        ],
        [[code("cwd")], [code('"."')], "Base directory for relative roots"],
        [
          [code("descriptionCap")],
          [code("SkillSource.DESCRIPTION_CAP"), " (1536)"],
          "Per-entry listing description cap in characters",
        ],
        [[code("frontmatterMaxBytes")], [code("65536")], "Bytes read when parsing only the frontmatter header"],
      ],
    ),
    p(
      "Discovery finds every ",
      code("SKILL.md"),
      " under each root recursively. Skill names namespace by directory: a file at ",
      code("web/search/SKILL.md"),
      " becomes ",
      code("web:search"),
      " unless the frontmatter sets an explicit ",
      code("name"),
      " containing a colon. Bodies load lazily; listing skills reads only headers.",
    ),
    h2("skill-md", "The SKILL.md contract"),
    p(
      "A document is YAML-like frontmatter between ",
      code("---"),
      " fences followed by the Markdown body. ",
      code("description"),
      " is required; keys are matched ignoring case, hyphens, and underscores.",
    ),
    table(
      ["Key", "Type", "Notes"],
      [
        [[code("name")], "string", "Overrides the directory-derived name"],
        [[code("description")], "string", "Required; shown in the startup listing"],
        [[code("when-to-use")], "string", "Optional usage hint"],
        [[code("allowed-tools")], "string array", "Inline or dash-list form"],
        [[code("disable-model-invocation")], "boolean", "Excluded from model-facing listings when true"],
        [[code("user-invocable")], "boolean", "Optional flag"],
        [[code("context-fork")], "boolean", "Optional flag"],
        [[code("agent")], "string", "Optional agent binding"],
        [[code("model")], "string", "Optional model hint"],
        [[code("paths")], "string array", "Optional related paths"],
      ],
    ),
    h2("instruction-files", "InstructionFiles.loadInstructionFiles"),
    p(
      code("loadInstructionFiles(options?)"),
      " returns ",
      code("ReadonlyArray<InstructionFile>"),
      " (",
      code("{ path, content }"),
      "), requiring ",
      code("FileSystem"),
      " and ",
      code("Path"),
      ". It reads ",
      code("globalFiles"),
      " first, then walks from the filesystem root down to ",
      code("cwd"),
      ", taking the first matching filename per directory.",
    ),
    table(
      ["Option", "Default"],
      [
        [[code("filenames")], [code('["AGENTS.md", "CLAUDE.md"]')]],
        [[code("cwd")], [code('"."')]],
        [[code("globalFiles")], [code("[]")]],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/skills", "How to add skills"),
      " and ",
      link("/docs/guides/instructions", "How to compose instructions and context sources"),
      ".",
    ),
  ],
})
