import * as Prose from "../../prose"

export const transportReference = Prose.definePage({
  path: "/docs/reference/transport",
  title: "@batonfx/transport",
  navTitle: "transport",
  group: "Reference",
  description: "The Wire frame protocol, SessionRegistry, SSE and WebSocket handlers, and the reconnecting client.",
  content: [
    Prose.lead(
      "@batonfx/transport serves agent runs over SSE and WebSocket: a schema-defined wire protocol, an in-memory session registry with replay, server handlers, and a reconnecting client.",
    ),
    Prose.command("Install", "bun add @batonfx/core @batonfx/transport"),
    Prose.p("Published on npm at 0.1.1. Requires ", Prose.code("@batonfx/core"), "."),
    Prose.h2("exports", "Exports map"),
    Prose.table(
      ["Subpath", "Contents"],
      [
        [
          [Prose.code(".")],
          [
            "Namespaces ",
            Prose.code("Client"),
            ", ",
            Prose.code("Errors"),
            ", ",
            Prose.code("SessionRegistry"),
            ", ",
            Prose.code("Sse"),
            ", ",
            Prose.code("Wire"),
            ", ",
            Prose.code("Ws"),
          ],
        ],
        [[Prose.code("./wire")], "Frame schemas and types"],
        [
          [Prose.code("./session-registry")],
          [Prose.code("SessionRegistry"), " service and ", Prose.code("layerMemory")],
        ],
        [[Prose.code("./sse")], ["SSE response helper ", Prose.code("respond")]],
        [[Prose.code("./ws")], ["WebSocket handler ", Prose.code("handle")]],
        [
          [Prose.code("./client")],
          [Prose.code("AgentClient"), ", ", Prose.code("layerWebSocket"), ", ", Prose.code("sseFrames")],
        ],
        [[Prose.code("./errors")], [Prose.code("TransportError")]],
      ],
    ),
    Prose.h2("client-frames", "Wire.ClientFrame"),
    Prose.p("Client-to-server control frames; a union of four."),
    Prose.table(
      ["Frame", "Fields", "Effect on the session"],
      [
        [
          [Prose.code("Attach")],
          [Prose.code("sessionId"), ", ", Prose.code("afterSeq?")],
          ["Subscribe to the frame stream, replaying frames with ", Prose.code("seq > afterSeq")],
        ],
        [
          [Prose.code("SendMessage")],
          [Prose.code("sessionId"), ", ", Prose.code("prompt")],
          "Start a run with the prompt",
        ],
        [
          [Prose.code("ResolveApproval")],
          [Prose.code("sessionId"), ", ", Prose.code("token"), ", ", Prose.code("decision")],
          "Resolve a pending approval suspension and resume the run",
        ],
        [[Prose.code("Cancel")], [Prose.code("sessionId")], "Interrupt the running fiber"],
      ],
    ),
    Prose.h2("server-frames", "Wire.ServerFrame"),
    Prose.p(
      "Server-to-client frames; a union of six. Every frame carries ",
      Prose.code("seq"),
      ", monotonic per session — it is the replay cursor a client hands back as ",
      Prose.code("afterSeq"),
      " when reattaching.",
    ),
    Prose.table(
      ["Frame", "Fields", "Meaning"],
      [
        [
          [Prose.code("Event")],
          [Prose.code("seq"), ", ", Prose.code("event")],
          ["One loop event (", Prose.code("Wire.EventType"), ")"],
        ],
        [
          [Prose.code("Failed")],
          [Prose.code("seq"), ", ", Prose.code("error: RunFailure")],
          [
            "The run failed terminally; ",
            Prose.code("RunFailure"),
            " is ",
            Prose.code("AgentError | TurnLimitExceeded | MiddlewareViolation"),
          ],
        ],
        [
          [Prose.code("Suspended")],
          [Prose.code("seq"), ", ", Prose.code("suspension: AgentSuspended")],
          "The run parked on an approval or tool wait",
        ],
        [[Prose.code("Ended")], [Prose.code("seq")], "The current run finished; the session stays open"],
        [
          [Prose.code("Snapshot")],
          [Prose.code("seq"), ", ", Prose.code("transcript: Ai.Prompt.Prompt")],
          "Full persisted transcript, sent instead of replay when a cursor is older than the ring buffer",
        ],
        [
          [Prose.code("SessionStatus")],
          [Prose.code("seq"), ", ", Prose.code("status")],
          "Lifecycle transition, tabulated below",
        ],
      ],
    ),
    Prose.h3("session-status", "Wire.SessionStatus"),
    Prose.table(
      ["Status", "Fields"],
      [
        [[Prose.code("Idle")], "none"],
        [[Prose.code("Running")], [Prose.code("turn")]],
        [[Prose.code("Suspended")], [Prose.code("suspension: AgentSuspended")]],
        [[Prose.code("Failed")], [Prose.code("error: RunFailure")]],
      ],
    ),
    Prose.h3("client-approval", "Wire.ClientApproval"),
    Prose.table(
      ["Decision", "Fields"],
      [
        [[Prose.code("Approved")], "none"],
        [[Prose.code("Denied")], [Prose.code("reason?")]],
      ],
    ),
    Prose.h3("event-codecs", "EventSchema, LooseEventSchema, and transcript stripping"),
    Prose.bullets(
      [
        Prose.code("Wire.EventSchema(toolkit)"),
        " types tool-call and tool-result parts against the toolkit's schemas — the server-side codec.",
      ],
      [
        Prose.code("Wire.LooseEventSchema"),
        " accepts any tool name with unknown params — the browser-side codec behind ",
        Prose.code("LooseServerFrame"),
        ".",
      ],
      [
        Prose.code("Wire.EventType"),
        " makes ",
        Prose.code("transcript"),
        " optional on ",
        Prose.code("TurnCompleted"),
        " and ",
        Prose.code("Completed"),
        " so registries can strip transcripts on the wire (",
        Prose.code("stripTranscripts"),
        ").",
      ],
    ),
    Prose.h2("session-registry", "SessionRegistry"),
    Prose.p("The service owning sessions and their frame streams."),
    Prose.table(
      ["Member", "Signature", "Notes"],
      [
        [
          [Prose.code("open")],
          [Prose.code("({ sessionId?, chatId?, system? }) => Effect<SessionInfo, SessionError>")],
          "Idempotent; creates or ensures the persisted chat",
        ],
        [
          [Prose.code("send")],
          [Prose.code("(sessionId, prompt) => Effect<void, SessionError | SessionBusy>")],
          ["Fails ", Prose.code("SessionBusy"), " while a run is active or suspended"],
        ],
        [
          [Prose.code("resolveApproval")],
          [Prose.code("(sessionId, token, decision) => Effect<void, SessionError | SessionBusy>")],
          "Validates the token against the stored suspension, then resumes",
        ],
        [
          [Prose.code("attach")],
          [Prose.code("(sessionId, afterSeq?) => Stream<LooseServerFrameType, SessionError | SubscriberLagged>")],
          "Replays buffered frames past the cursor, then live frames; a stale cursor gets a Snapshot instead",
        ],
        [
          [Prose.code("interrupt")],
          [Prose.code("(sessionId) => Effect<void, SessionError>")],
          "Stops the running fiber and finalizes the run as Failed",
        ],
        [
          [Prose.code("info")],
          [Prose.code("(sessionId) => Effect<SessionInfo, SessionError>")],
          [Prose.code("SessionInfo"), " is ", Prose.code("{ sessionId, chatId, status, lastSeq, idleSince }")],
        ],
      ],
    ),
    Prose.p(
      Prose.code("layerMemory({ agent, ... })"),
      " requires ",
      Prose.code("Agent.RunServices"),
      " and ",
      Prose.code("Ai.Chat.Persistence"),
      " and runs each send as ",
      Prose.code("Agent.stream"),
      " with ",
      Prose.code("persistence: { chatId }"),
      ".",
    ),
    Prose.table(
      ["Option", "Default"],
      [
        [[Prose.code("ringBufferCapacity")], [Prose.code("1024"), " frames kept for replay"]],
        [
          [Prose.code("subscriberQueueCapacity")],
          [Prose.code("128"), " — slower subscribers fail with ", Prose.code("SubscriberLagged")],
        ],
        [[Prose.code("idleTimeout")], [Prose.code('"15 minutes"'), " before idle sessions are evicted"]],
        [[Prose.code("stripTranscripts")], [Prose.code("false")]],
      ],
    ),
    Prose.p(
      "Errors: ",
      Prose.code("SessionError{ message }"),
      ", ",
      Prose.code("SessionBusy{ sessionId }"),
      ", ",
      Prose.code("SubscriberLagged{ sessionId, lastDeliveredSeq }"),
      ".",
    ),
    Prose.h2("sse", "Sse"),
    Prose.p(
      Prose.code("Sse.respond(toolkit)({ sessionId, request, keepAlive? })"),
      " returns a ",
      Prose.code("text/event-stream"),
      " response over ",
      Prose.code("SessionRegistry.attach"),
      ". The replay cursor comes from the ",
      Prose.code("Last-Event-ID"),
      " header or the ",
      Prose.code("after_seq"),
      " query parameter; each SSE event's id is the frame ",
      Prose.code("seq"),
      ". Keep-alive comments tick every 15 seconds by default. ",
      Prose.code("Sse.streamSuccess(toolkit)"),
      " is the matching HttpApi schema; ",
      Prose.code("Sse.lastEventId(headers)"),
      " parses the cursor.",
    ),
    Prose.h2("ws", "Ws"),
    Prose.p(
      Prose.code("Ws.handle(toolkit)"),
      " is a one-session-per-socket WebSocket handler: it decodes ",
      Prose.code("ClientFrame"),
      " JSON text frames, dispatches to the registry, and writes encoded ",
      Prose.code("ServerFrame"),
      "s. Close codes: 4000 when a subscriber lags, 1003 for malformed or binary frames, 1011 for session errors and busy sessions.",
    ),
    Prose.h2("client", "Client"),
    Prose.table(
      ["Export", "Notes"],
      [
        [
          [Prose.code("AgentClient.connect({ url, sessionId })")],
          [
            "Scoped ",
            Prose.code("Connection"),
            ": ",
            Prose.code("{ frames, send, status }"),
            " with ",
            Prose.code("ConnectionStatus"),
            " one of Connecting, Open, Reconnecting, Closed",
          ],
        ],
        [
          [Prose.code("layerWebSocket")],
          [
            "Reconnecting WebSocket client (capped exponential backoff); on each open it re-sends ",
            Prose.code("Attach"),
            " with the last delivered ",
            Prose.code("seq"),
            " so no frames are missed. Requires ",
            Prose.code("Socket.WebSocketConstructor"),
          ],
        ],
        [[Prose.code("sseFrames({ url, afterSeq? })")], ["One-shot SSE frame stream over ", Prose.code("HttpClient")]],
      ],
    ),
    Prose.p(
      "See ",
      Prose.link("/docs/guides/serve-transport", "How to serve an agent over SSE and WebSocket"),
      " and ",
      Prose.link("/docs/guides/approvals", "How to require human approval for a tool"),
      "; the browser adapter is ",
      Prose.link("/docs/reference/foldkit", "@batonfx/foldkit"),
      ".",
    ),
  ],
})
