import { bullets, code, command, definePage, h2, h3, lead, link, p, table } from "../../prose"
export const transportReference = definePage({
  path: "/docs/reference/transport",
  title: "@batonfx/transport",
  navTitle: "transport",
  group: "Reference",
  description: "The Wire frame protocol, SessionRegistry, SSE and WebSocket handlers, and the reconnecting client.",
  content: [
    lead(
      "@batonfx/transport serves agent runs over SSE and WebSocket: a schema-defined wire protocol, an in-memory session registry with replay, server handlers, and a reconnecting client.",
    ),
    command("Install", "bun add @batonfx/core @batonfx/transport"),
    p("Published on npm at 0.4.0. Requires ", code("@batonfx/core"), "."),
    h2("exports", "Exports map"),
    table(
      ["Subpath", "Contents"],
      [
        [
          [code(".")],
          [
            "Namespaces ",
            code("Client"),
            ", ",
            code("Errors"),
            ", ",
            code("SessionRegistry"),
            ", ",
            code("Sse"),
            ", ",
            code("Wire"),
            ", ",
            code("Ws"),
          ],
        ],
        [[code("./wire")], "Frame schemas and types"],
        [[code("./session-registry")], [code("SessionRegistry"), " service and ", code("layerMemory")]],
        [[code("./sse")], ["SSE response helper ", code("respond")]],
        [[code("./ws")], ["WebSocket handler ", code("handle")]],
        [[code("./client")], [code("AgentClient"), ", ", code("layerWebSocket"), ", ", code("sseFrames")]],
        [[code("./errors")], [code("TransportError"), ", ", code("NotAttached"), ", ", code("SessionMismatch")]],
      ],
    ),
    h2("client-frames", "Wire.ClientFrame"),
    p("Client-to-server control frames; a union of four."),
    table(
      ["Frame", "Fields", "Effect on the session"],
      [
        [
          [code("Attach")],
          [code("sessionId"), ", ", code("afterSeq?")],
          ["Subscribe to the frame stream, replaying frames with ", code("seq > afterSeq")],
        ],
        [[code("SendMessage")], [code("sessionId"), ", ", code("prompt")], "Start a run with the prompt"],
        [
          [code("ResolveApproval")],
          [code("sessionId"), ", ", code("token"), ", ", code("decision")],
          "Resolve a pending approval suspension and resume the run",
        ],
        [[code("Cancel")], [code("sessionId")], "Interrupt the running fiber"],
      ],
    ),
    h2("server-frames", "Wire.ServerFrame"),
    p(
      "Server-to-client frames; a union of six. Every frame carries ",
      code("seq"),
      ", monotonic per session; it is the replay cursor a client hands back as ",
      code("afterSeq"),
      " when reattaching.",
    ),
    table(
      ["Frame", "Fields", "Meaning"],
      [
        [[code("Event")], [code("seq"), ", ", code("event")], ["One loop event (", code("Wire.EventType"), ")"]],
        [
          [code("Failed")],
          [code("seq"), ", ", code("error: RunFailure")],
          [
            "The run failed terminally; ",
            code("RunFailure"),
            " is ",
            code(
              "AgentError | TurnPolicyError | TurnPolicyStopped | TurnLimitExceeded | MiddlewareViolation | FrameworkFailure",
            ),
          ],
        ],
        [
          [code("Suspended")],
          [code("seq"), ", ", code("suspension: AgentSuspended")],
          "The run parked on an approval or tool wait",
        ],
        [[code("Ended")], [code("seq")], "The current run finished; the session stays open"],
        [
          [code("Snapshot")],
          [code("seq"), ", ", code("transcript: Ai.Prompt.Prompt")],
          "Full persisted transcript, sent instead of replay when a cursor is older than the ring buffer",
        ],
        [[code("SessionStatus")], [code("seq"), ", ", code("status")], "Lifecycle transition, tabulated below"],
      ],
    ),
    h3("session-status", "Wire.SessionStatus"),
    table(
      ["Status", "Fields"],
      [
        [[code("Idle")], "none"],
        [[code("Running")], [code("turn")]],
        [[code("Suspended")], [code("suspension: AgentSuspended")]],
        [[code("Failed")], [code("error: RunFailure")]],
      ],
    ),
    h3("client-approval", "Wire.ClientApproval"),
    table(
      ["Decision", "Fields"],
      [
        [[code("Approved")], "none"],
        [[code("Denied")], [code("reason?")]],
      ],
    ),
    h3("event-codecs", "EventSchema, LooseEventSchema, and transcript stripping"),
    bullets(
      [
        code("Wire.EventSchema(toolkit)"),
        " types tool-call and tool-result parts against the toolkit's schemas, the server-side codec.",
      ],
      [
        code("Wire.LooseEventSchema"),
        " accepts any tool name with unknown params, the browser-side codec behind ",
        code("LooseServerFrame"),
        ".",
      ],
      [
        code("Wire.EventType"),
        " makes ",
        code("transcript"),
        " optional on ",
        code("TurnCompleted"),
        " and ",
        code("Completed"),
        " so registries can strip transcripts on the wire (",
        code("stripTranscripts"),
        ").",
      ],
    ),
    h2("session-registry", "SessionRegistry"),
    p("The service owning sessions and their frame streams."),
    table(
      ["Member", "Signature", "Notes"],
      [
        [
          [code("open")],
          [code("({ sessionId?, chatId?, system? }) => Effect<SessionInfo, SessionError>")],
          "Idempotent; creates or ensures the persisted chat",
        ],
        [
          [code("send")],
          [code("(sessionId, prompt) => Effect<void, SessionError | SessionBusy | SessionQueueFull>")],
          [
            "Rejects a concurrent message by default; with enqueue mode it appends to the bounded per-session FIFO queue",
          ],
        ],
        [
          [code("resolveApproval")],
          [code("(sessionId, token, decision) => Effect<void, SessionError | SessionBusy>")],
          "Validates the token against the stored suspension, then resumes",
        ],
        [
          [code("attach")],
          [code("(sessionId, afterSeq?) => Stream<LooseServerFrameType, SessionError | SubscriberLagged>")],
          "Replays buffered frames past the cursor, then live frames; a stale cursor gets a Snapshot instead",
        ],
        [
          [code("interrupt")],
          [code("(sessionId) => Effect<void, SessionError>")],
          "Stops the running fiber and finalizes the run as Failed",
        ],
        [
          [code("info")],
          [code("(sessionId) => Effect<SessionInfo, SessionError>")],
          [code("SessionInfo"), " is ", code("{ sessionId, chatId, status, lastSeq, idleSince, pendingMessages }")],
        ],
      ],
    ),
    p(
      code("layerMemory({ agent, ... })"),
      " requires ",
      code("Agent.Requirements<typeof agent>"),
      " and ",
      code("Ai.Chat.Persistence"),
      " and runs each send as ",
      code("Agent.stream"),
      " with ",
      code("persistence: { chatId }"),
      ".",
    ),
    table(
      ["Option", "Default"],
      [
        [[code("ringBufferCapacity")], [code("1024"), " frames kept for replay"]],
        [[code("subscriberQueueCapacity")], [code("128"), ": slower subscribers fail with ", code("SubscriberLagged")]],
        [[code("idleTimeout")], [code('"15 minutes"'), " before idle sessions are evicted"]],
        [[code("stripTranscripts")], [code("false")]],
        [[code("onConcurrentMessage")], [code('"reject"'), "; set to ", code('"enqueue"'), " for FIFO queueing"]],
        [[code("pendingMessageCapacity")], [code("128"), " queued messages per session"]],
        [[code("maxConcurrentRuns")], ["unbounded; set a positive number for a registry-wide run cap"]],
      ],
    ),
    p(
      "Errors: ",
      code("SessionError{ message }"),
      ", ",
      code("SessionBusy{ sessionId }"),
      ", ",
      code("SessionQueueFull{ sessionId, capacity }"),
      ", ",
      code("SubscriberLagged{ sessionId, lastDeliveredSeq }"),
      ".",
    ),
    h2("sse", "Sse"),
    p(
      code("Sse.respond(capability)({ sessionId, request, keepAlive? })"),
      " returns a ",
      code("text/event-stream"),
      " response over ",
      code("SessionRegistry.attach"),
      ". The replay cursor comes from the ",
      code("Last-Event-ID"),
      " header or the ",
      code("after_seq"),
      " query parameter; each SSE event's id is the frame ",
      code("seq"),
      ". Keep-alive comments tick every 15 seconds by default. ",
      code("Sse.streamSuccess(capability)"),
      " is the matching HttpApi schema; ",
      code("Sse.lastEventId(headers)"),
      " parses the cursor.",
    ),
    p(
      "Pass a toolkit directly for the source-compatible fixed path, or select ",
      code('{ capability: "fixed", toolkit }'),
      " explicitly. Agents that activate skills or discover tools at runtime use ",
      code('{ capability: "runtime-dynamic" }'),
      " for both the SSE response schema and responder. Dynamic frames retain strict common event/frame validation while tool names are strings and tool params/results are unknown.",
    ),
    h2("ws", "Ws"),
    p(
      code("Ws.handle(capability)"),
      " is a one-session-per-socket WebSocket handler: it decodes ",
      code("ClientFrame"),
      " JSON text frames, dispatches to the registry, and writes encoded ",
      code("ServerFrame"),
      "s. The first Attach binds immutable session authority; same-session reattach is idempotent, while commands before attach or for another session close with code 1008. Other close codes: 4000 when a subscriber lags, 1003 for malformed or binary frames, 1011 for session errors and busy sessions, and 1013 when an enqueue-mode session queue is full.",
    ),
    p(
      "The WebSocket capability is selected once when the handler is built. A direct toolkit remains fixed shorthand; runtime-discovered tool events require ",
      code('{ capability: "runtime-dynamic" }'),
      ". Loose delivery is display data and does not grant tool execution authority.",
    ),
    h2("client", "Client"),
    table(
      ["Export", "Notes"],
      [
        [
          [code("AgentClient.connect({ url, sessionId })")],
          [
            "Scoped ",
            code("Connection"),
            ": ",
            code("{ frames, send, status, exhausted }"),
            " with ",
            code("ConnectionStatus"),
            " one of Connecting, Connected, Disconnected(error), Retrying(attempt)",
          ],
        ],
        [
          [code("layerWebSocket")],
          [
            "Bounded WebSocket client with configurable frame/status buffers and finite reconnect Schedule; on each open it re-sends ",
            code("Attach"),
            " with the last delivered ",
            code("seq"),
            " so no frames are missed. Requires ",
            code("Socket.WebSocketConstructor"),
          ],
        ],
        [[code("sseFrames({ url, afterSeq? })")], ["One-shot SSE frame stream over ", code("HttpClient")]],
      ],
    ),
    p(
      "See ",
      link("/docs/guides/serve-transport", "How to serve an agent over SSE and WebSocket"),
      " and ",
      link("/docs/guides/approvals", "How to require human approval for a tool"),
      "; the browser adapter is ",
      link("/docs/reference/foldkit", "@batonfx/foldkit"),
      ".",
    ),
  ],
})
