import { code, definePage, h2, lead, link, p, pills, table } from "../../prose"
export const versioningReference = definePage({
  path: "/docs/reference/versioning",
  title: "Versioning and releases",
  navTitle: "Versioning",
  group: "Reference",
  description: "The published 0.1.1 set, the @experimental policy, effect compatibility, and the release train.",
  content: [
    lead(
      "All seven @batonfx packages publish to npm as a coordinated train at the same version. The current version is 0.1.1.",
    ),
    h2("published-set", "Published packages"),
    table(
      ["Package", "Version", "Subpath exports"],
      [
        [[code("@batonfx/core")], [code("0.1.1")], [code(".")]],
        [
          [code("@batonfx/providers")],
          [code("0.1.1")],
          [
            code("."),
            ", ",
            code("./catalog"),
            ", ",
            code("./openai"),
            ", ",
            code("./anthropic"),
            ", ",
            code("./openrouter"),
            ", ",
            code("./openai-compat"),
            ", ",
            code("./deterministic"),
            ", ",
            code("./presets"),
            ", ",
            code("./embedding"),
          ],
        ],
        [[code("@batonfx/mcp")], [code("0.1.1")], [code("."), ", ", code("./baton")]],
        [[code("@batonfx/skills")], [code("0.1.1")], [code(".")]],
        [[code("@batonfx/memory")], [code("0.1.1")], [code(".")]],
        [
          [code("@batonfx/transport")],
          [code("0.1.1")],
          [
            code("."),
            ", ",
            code("./client"),
            ", ",
            code("./errors"),
            ", ",
            code("./sse"),
            ", ",
            code("./ws"),
            ", ",
            code("./wire"),
            ", ",
            code("./session-registry"),
          ],
        ],
        [[code("@batonfx/foldkit")], [code("0.1.1")], [code(".")]],
      ],
    ),
    p("Packages export Bun-friendly TypeScript source paths; the 0.1.x docs and examples intentionally target Bun."),
    h2("experimental-policy", "The @experimental policy"),
    p(
      "Every public export carries ",
      code("@experimental"),
      " while ",
      code("effect/unstable/ai"),
      " is itself unstable. The stable tier for 0.1.x is conceptual: the ",
      code("AgentEvent"),
      " union, the frozen error tags, ",
      code("Agent"),
      ", ",
      code("ToolExecutor"),
      ", ",
      code("Approvals"),
      ", and ",
      code("TurnPolicy"),
      " form the small stable core. Everything else may move before 1.0.0, which waits for Effect 4 GA.",
    ),
    h2("effect-compat", "Effect compatibility"),
    table(
      ["Batonfx", "effect", "Notes"],
      [
        [
          [code("0.1.x")],
          [code("4.0.0-beta.93")],
          "The tested catalog version; each 0.x minor declares its tested beta",
        ],
      ],
    ),
    p(
      code("@batonfx/foldkit"),
      " additionally pins its peers: ",
      code("effect >=4.0.0-beta.88 <4.0.1"),
      " and ",
      code("foldkit >=0.122.0 <1"),
      ".",
    ),
    h2("release-train", "The release train"),
    p("Every release publishes all packages at the same version in dependency order:"),
    pills(["core", "skills", "memory", "providers", "mcp", "transport", "foldkit"]),
    p(
      "The publish workflow is manual: it accepts an explicit version, rewrites ",
      code("workspace:*"),
      " and ",
      code("catalog:"),
      " protocols out of package manifests, dry-runs ",
      code("bun publish --access public"),
      " for every package, and only publishes and tags when the dry-run flag is off.",
    ),
    p("For install commands and the package matrix, see ", link("/docs/start/installation", "Installation"), "."),
  ],
})
