import * as Prose from "../../prose"

export const versioningReference = Prose.definePage({
  path: "/docs/reference/versioning",
  title: "Versioning and releases",
  navTitle: "Versioning",
  group: "Reference",
  description: "The published 0.1.1 set, the @experimental policy, effect compatibility, and the release train.",
  content: [
    Prose.lead(
      "All seven @batonfx packages publish to npm as a coordinated train at the same version. The current version is 0.1.1.",
    ),
    Prose.h2("published-set", "Published packages"),
    Prose.table(
      ["Package", "Version", "Subpath exports"],
      [
        [[Prose.code("@batonfx/core")], [Prose.code("0.1.1")], [Prose.code(".")]],
        [
          [Prose.code("@batonfx/providers")],
          [Prose.code("0.1.1")],
          [
            Prose.code("."),
            ", ",
            Prose.code("./catalog"),
            ", ",
            Prose.code("./openai"),
            ", ",
            Prose.code("./anthropic"),
            ", ",
            Prose.code("./openrouter"),
            ", ",
            Prose.code("./openai-compat"),
            ", ",
            Prose.code("./deterministic"),
            ", ",
            Prose.code("./presets"),
            ", ",
            Prose.code("./embedding"),
          ],
        ],
        [[Prose.code("@batonfx/mcp")], [Prose.code("0.1.1")], [Prose.code("."), ", ", Prose.code("./baton")]],
        [[Prose.code("@batonfx/skills")], [Prose.code("0.1.1")], [Prose.code(".")]],
        [[Prose.code("@batonfx/memory")], [Prose.code("0.1.1")], [Prose.code(".")]],
        [
          [Prose.code("@batonfx/transport")],
          [Prose.code("0.1.1")],
          [
            Prose.code("."),
            ", ",
            Prose.code("./client"),
            ", ",
            Prose.code("./errors"),
            ", ",
            Prose.code("./sse"),
            ", ",
            Prose.code("./ws"),
            ", ",
            Prose.code("./wire"),
            ", ",
            Prose.code("./session-registry"),
          ],
        ],
        [[Prose.code("@batonfx/foldkit")], [Prose.code("0.1.1")], [Prose.code(".")]],
      ],
    ),
    Prose.p(
      "Packages export Bun-friendly TypeScript source paths; the 0.1.x docs and examples intentionally target Bun.",
    ),
    Prose.h2("experimental-policy", "The @experimental policy"),
    Prose.p(
      "Every public export carries ",
      Prose.code("@experimental"),
      " while ",
      Prose.code("effect/unstable/ai"),
      " is itself unstable. The stable tier for 0.1.x is conceptual: the ",
      Prose.code("AgentEvent"),
      " union, the frozen error tags, ",
      Prose.code("Agent"),
      ", ",
      Prose.code("ToolExecutor"),
      ", ",
      Prose.code("Approvals"),
      ", and ",
      Prose.code("TurnPolicy"),
      " form the small stable core. Everything else may move before 1.0.0, which waits for Effect 4 GA.",
    ),
    Prose.h2("effect-compat", "Effect compatibility"),
    Prose.table(
      ["Batonfx", "effect", "Notes"],
      [
        [
          [Prose.code("0.1.x")],
          [Prose.code("4.0.0-beta.93")],
          "The tested catalog version; each 0.x minor declares its tested beta",
        ],
      ],
    ),
    Prose.p(
      Prose.code("@batonfx/foldkit"),
      " additionally pins its peers: ",
      Prose.code("effect >=4.0.0-beta.88 <4.0.1"),
      " and ",
      Prose.code("foldkit >=0.122.0 <1"),
      ".",
    ),
    Prose.h2("release-train", "The release train"),
    Prose.p("Every release publishes all packages at the same version in dependency order:"),
    Prose.pills(["core", "skills", "memory", "providers", "mcp", "transport", "foldkit"]),
    Prose.p(
      "The publish workflow is manual: it accepts an explicit version, rewrites ",
      Prose.code("workspace:*"),
      " and ",
      Prose.code("catalog:"),
      " protocols out of package manifests, dry-runs ",
      Prose.code("bun publish --access public"),
      " for every package, and only publishes and tags when the dry-run flag is off. After publish, a scratch Bun consumer installs each package, imports its documented exports, and runs ",
      Prose.code("bun tsc --noEmit"),
      ".",
    ),
    Prose.p(
      "For install commands and the package matrix, see ",
      Prose.link("/docs/start/installation", "Installation"),
      ".",
    ),
  ],
})
