import denyInTheLoop from "virtual:source/src/snippets/guides/agent/permissions/deny-in-the-loop.ts"
import denyInTheLoopExpected from "virtual:source/src/snippets/guides/agent/permissions/deny-in-the-loop.expected.txt"
import evaluateRuleset from "virtual:source/src/snippets/guides/agent/permissions/evaluate-ruleset.ts"
import evaluateRulesetExpected from "virtual:source/src/snippets/guides/agent/permissions/evaluate-ruleset.expected.txt"
import interactiveAsks from "virtual:source/src/snippets/guides/agent/permissions/interactive-asks.ts"
import { bullets, callout, code, codeBlock, definePage, h2, link, p } from "../../../prose"
export const permissions = definePage({
  path: "/docs/guides/permissions",
  title: "How to gate tools with permission rules",
  navTitle: "Permissions",
  group: "Guides",
  description:
    "Write allow, deny, and ask rulesets, resolve asks with Approvals, and remember decisions with a RuleStore.",
  content: [
    p(
      "The ",
      code("Permissions"),
      " service is host policy for tool calls: before every call, the loop asks it to ",
      code("allow"),
      ", ",
      code("deny"),
      ", or ",
      code("ask"),
      ". Allow continues into the normal approval path, deny fails the run with a typed authorization framework error, and ask enters the approval resolution flow. Permissions runs before ",
      link("/docs/guides/approvals", "Approvals"),
      "; there is one resolution vocabulary and one resume path.",
    ),
    h2("write-a-ruleset", "1. Write an ordered ruleset"),
    p(
      "A rule is a glob pattern plus a level. Plain patterns match the tool name; a ",
      code("tool:params"),
      " pattern also matches against the call's parameter text. Later rules win, and ",
      code("fallback"),
      " covers everything unmatched (it defaults to ",
      code('"ask"'),
      "). ",
      code("Permissions.evaluate"),
      " and ",
      code("Permissions.matches"),
      " let you test a ruleset as a pure function:",
    ),
    codeBlock({ label: "evaluate-ruleset.ts", source: evaluateRuleset, expectedOutput: evaluateRulesetExpected }),
    callout(
      "warning",
      "Deny rules fail closed",
      "When a call's params cannot be fully projected to text, a matching deny-level tool pattern still denies. Prefer deny rules for anything destructive.",
    ),
    h2("provide-the-layer", "2. Provide the layer and watch a denial"),
    p(
      code("Permissions.layerRuleset"),
      " turns the ruleset into a static policy layer. A denied call never reaches the executor: the host receives your ",
      code("reason"),
      " in a typed ",
      code("FrameworkFailure"),
      ", which the host handles without inventing a value outside the tool's declared failure schema:",
    ),
    codeBlock({ label: "deny-in-the-loop.ts", source: denyInTheLoop, expectedOutput: denyInTheLoopExpected }),
    h2("answer-asks", "3. Resolve asks interactively"),
    p(
      "For an in-process host, such as a CLI or a test harness, ",
      code("Approvals.resolve"),
      " receives every ask-level decision and answers ",
      code("Approved"),
      ", ",
      code("Denied"),
      ", or ",
      code("Pending"),
      ". An ",
      code("Approved"),
      " resolution can carry an explicit ",
      code("remember"),
      " rule. The authorizer writes that rule through ",
      code("RuleStore"),
      " before executing the call:",
    ),
    codeBlock({ label: "interactive-asks.ts", source: interactiveAsks }),
    p(
      code("Permissions.layerRuleStoreMemory"),
      " keeps remembered rules for the process lifetime; durable hosts implement ",
      code("RuleStore.remember"),
      " over their own storage.",
    ),
    h2("suspend-on-ask", "4. Let asks suspend for out-of-process hosts"),
    p(
      "If ",
      code("Approvals.resolve"),
      " returns ",
      code("Pending"),
      ", an ask-level call suspends the run with ",
      code("AgentSuspended"),
      " and a ",
      code("permission:"),
      "-prefixed token. Handle it exactly like an approval suspension: store the token, decide out-of-band, re-enter with ",
      code("RunOptions.resume"),
      ". ",
      link("/docs/learn/suspension", "Suspension as a typed error"),
      " covers the re-entry contract.",
    ),
    h2("next-steps", "Next steps"),
    bullets(
      [
        "Add the human approval gate behind allow-level calls: ",
        link("/docs/guides/approvals", "How to require human approval for a tool"),
        ".",
      ],
      ["See every policy service on the run: ", link("/docs/learn/seams-as-services", "Seams as services"), "."],
    ),
  ],
})
