import chatEntry from "../../snippets/guides/foldkit-chat/entry.ts?raw"
import chatModel from "../../snippets/guides/foldkit-chat/model.ts?raw"
import chatView from "../../snippets/guides/foldkit-chat/view.ts?raw"
import * as Prose from "../../prose"

export const foldkitChat = Prose.definePage({
  path: "/docs/guides/foldkit-chat",
  title: "How to build a chat UI with FoldKit",
  navTitle: "Build a FoldKit chat UI",
  group: "Guides",
  description:
    "Embed the headless Chat submodel in a FoldKit application, stream frames over AgentConnection, and render approvals and streaming text.",
  content: [
    Prose.p(
      Prose.code("@batonfx/foldkit"),
      " adapts transport frames into FoldKit's Elm architecture. ",
      Prose.code("Connection.AgentConnection"),
      " is a long-lived resource that streams decoded server frames and connection facts; ",
      Prose.code("Chat"),
      " is a headless submodel with a pure ",
      Prose.code("update"),
      " that projects those frames into display state. It ships no styled components — rendering stays yours.",
    ),
    Prose.command("Terminal", "bun add @batonfx/foldkit @batonfx/transport foldkit"),
    Prose.h2("embed-the-chat-model", "1. Open a session and embed the chat model"),
    Prose.p(
      "Embed ",
      Prose.code("Chat.Model"),
      " in the application model and route every ",
      Prose.code("Chat.Message"),
      " through one wrapper message. The host owns session creation: a command POSTs to the server from ",
      Prose.link("/docs/guides/serve-transport", "the transport guide"),
      ", then dispatches ",
      Prose.code("Chat.OpenedSession"),
      ", which selects the session and lets the subscription attach. ",
      Prose.code("Subscription.lift"),
      " keeps the frame stream alive across model changes and restarts it only when the session id changes.",
    ),
    Prose.codeBlock({ label: "model.ts", source: chatModel }),
    Prose.callout(
      "info",
      "Replay is idempotent",
      "Chat.update drops any frame with ",
      Prose.code("seq <= lastSeq"),
      " without changing state, so reconnect replays and duplicate deliveries are harmless by construction.",
    ),
    Prose.h2("render-the-chat", "2. Render entries, streaming text, and the approval moment"),
    Prose.p(
      "The model gives the view everything as data: ",
      Prose.code("entries"),
      " (user, assistant, and tool rows), ",
      Prose.code("streaming"),
      " for in-flight assistant text, ",
      Prose.code("draft"),
      " for the input, and ",
      Prose.code("run"),
      " for the run state. When ",
      Prose.code("run"),
      " is ",
      Prose.code("AwaitingApproval"),
      ", render approve and deny controls that dispatch ",
      Prose.code("Chat.ClickedApprove"),
      " and ",
      Prose.code("Chat.ClickedDeny"),
      " — the submodel already carries the token.",
    ),
    Prose.codeBlock({ label: "view.ts", source: chatView }),
    Prose.p(
      "For richer rendering, ",
      Prose.code("Chat.conversationItems"),
      ", ",
      Prose.code("Chat.promptInputStatusOf"),
      ", and ",
      Prose.code("Chat.toolStatusOf"),
      " map the model to foldcn-aligned view data — that is what ",
      Prose.link(
        "https://github.com/In-Time-Tec/batonfx/blob/main/examples/deep-research-agent/web/src/main.ts",
        "the deep-research web app",
      ),
      " renders with styled components.",
    ),
    Prose.h2("wire-the-websocket-resource", "3. Wire the WebSocket resource and run"),
    Prose.p(
      Prose.code("Connection.layerWebSocket"),
      " composes the transport client and needs a WebSocket constructor — in the browser that is ",
      Prose.code("Socket.layerWebSocketConstructorGlobal"),
      ". Provide it through the application's static ",
      Prose.code("resources"),
      ".",
    ),
    Prose.codeBlock({ label: "entry.ts", source: chatEntry }),
    Prose.h2("connection-states", "4. Handle reconnection states"),
    Prose.bullets(
      [
        "The transport client reconnects with bounded exponential backoff and re-attaches with the last seen ",
        Prose.code("seq"),
        ", so a dropped socket resumes where it left off.",
      ],
      [
        "Connection facts fold into the same message stream: ",
        Prose.code("model.connection"),
        " moves through ",
        Prose.code("connecting"),
        ", ",
        Prose.code("open"),
        ", ",
        Prose.code("reconnecting"),
        ", and ",
        Prose.code("disconnected"),
        " — render it as a status badge.",
      ],
      [
        "Send failures never vanish: every command converts them into ",
        Prose.code("FailedAgentCommand"),
        ", which the update folds into a ",
        Prose.code("Failed"),
        " run state.",
      ],
    ),
    Prose.p(
      "The full model, message, and helper tables are in ",
      Prose.link("/docs/reference/foldkit", "the @batonfx/foldkit reference"),
      ". To build the server side of this page, start at ",
      Prose.link("/docs/start/research-agent", "the research-agent tutorial"),
      ".",
    ),
  ],
})
