import denyInTheLoop from "../../snippets/guides/permissions/deny-in-the-loop.ts?raw"
import denyInTheLoopExpected from "../../snippets/guides/permissions/deny-in-the-loop.expected.txt?raw"
import evaluateRuleset from "../../snippets/guides/permissions/evaluate-ruleset.ts?raw"
import evaluateRulesetExpected from "../../snippets/guides/permissions/evaluate-ruleset.expected.txt?raw"
import interactiveAsks from "../../snippets/guides/permissions/interactive-asks.ts?raw"
import * as Prose from "../../prose"

export const permissions = Prose.definePage({
  path: "/docs/guides/permissions",
  title: "How to gate tools with permission rules",
  navTitle: "Permissions",
  group: "Guides",
  description:
    "Write allow, deny, and ask rulesets, provide Permissions.fromRuleset or interactive, and remember decisions with a RuleStore.",
  content: [
    Prose.p(
      "The ",
      Prose.code("Permissions"),
      " service is host policy for tool calls: before every call, the loop asks it to ",
      Prose.code("allow"),
      ", ",
      Prose.code("deny"),
      ", or ",
      Prose.code("ask"),
      ". Allow continues into the normal approval path, deny becomes a failed tool result the model sees, and ask waits for an answer (or suspends exactly like an approval). Permissions runs before ",
      Prose.link("/docs/guides/approvals", "Approvals"),
      "; there is one wait vocabulary and one resume path.",
    ),
    Prose.h2("write-a-ruleset", "1. Write an ordered ruleset"),
    Prose.p(
      "A rule is a glob pattern plus a level. Plain patterns match the tool name; a ",
      Prose.code("tool:params"),
      " pattern also matches against the call's parameter text. Later rules win, and ",
      Prose.code("fallback"),
      " covers everything unmatched (it defaults to ",
      Prose.code('"ask"'),
      "). ",
      Prose.code("Permissions.evaluate"),
      " and ",
      Prose.code("Permissions.matches"),
      " let you test a ruleset as a pure function:",
    ),
    Prose.codeBlock({ label: "evaluate-ruleset.ts", source: evaluateRuleset, expectedOutput: evaluateRulesetExpected }),
    Prose.callout(
      "warning",
      "Deny rules fail closed",
      "When a call's params cannot be fully projected to text, a matching deny-level tool pattern still denies. Prefer deny rules for anything destructive.",
    ),
    Prose.h2("provide-the-layer", "2. Provide the layer and watch a denial"),
    Prose.p(
      Prose.code("Permissions.fromRuleset"),
      " turns the ruleset into a static policy layer. A denied call never reaches the executor: the model receives your ",
      Prose.code("reason"),
      " as a failed tool result and answers accordingly:",
    ),
    Prose.codeBlock({ label: "deny-in-the-loop.ts", source: denyInTheLoop, expectedOutput: denyInTheLoopExpected }),
    Prose.h2("answer-asks", "3. Answer asks interactively"),
    Prose.p(
      "For an in-process host, such as a CLI or a test harness, ",
      Prose.code("Permissions.interactive"),
      " routes every ask-level decision to your ",
      Prose.code("onAsk"),
      " callback, which answers ",
      Prose.code("Approved"),
      ", ",
      Prose.code("Denied"),
      ", or ",
      Prose.code("Always"),
      ". ",
      Prose.code("Always"),
      " executes the call and, when a ",
      Prose.code("RuleStore"),
      " is present, remembers an allow rule for that tool:",
    ),
    Prose.codeBlock({ label: "interactive-asks.ts", source: interactiveAsks }),
    Prose.p(
      Prose.code("Permissions.ruleStoreMemory"),
      " keeps remembered rules for the process lifetime; durable hosts implement ",
      Prose.code("RuleStore.remember"),
      " over their own storage.",
    ),
    Prose.h2("suspend-on-ask", "4. Let asks suspend for out-of-process hosts"),
    Prose.p(
      "If ",
      Prose.code("await"),
      " returns ",
      Prose.code("Option.none()"),
      " (the ",
      Prose.code("fromRuleset"),
      " default), an ask-level call suspends the run with ",
      Prose.code("AgentSuspended"),
      " and a ",
      Prose.code("permission:"),
      "-prefixed token. Handle it exactly like an approval suspension: store the token, decide out-of-band, re-enter with ",
      Prose.code("RunOptions.resume"),
      ". ",
      Prose.link("/docs/learn/suspension", "Suspension as a typed error"),
      " covers the re-entry contract.",
    ),
    Prose.h2("next-steps", "Next steps"),
    Prose.bullets(
      [
        "Add the human approval gate behind allow-level calls: ",
        Prose.link("/docs/guides/approvals", "How to require human approval for a tool"),
        ".",
      ],
      ["See every policy service on the run: ", Prose.link("/docs/learn/seams-as-services", "Seams as services"), "."],
    ),
  ],
})
