import combineProviders from "../../snippets/guides/providers/combine-providers.ts?raw"
import deterministicRegistry from "../../snippets/guides/providers/deterministic-registry.ts?raw"
import deterministicRegistryExpected from "../../snippets/guides/providers/deterministic-registry.expected.txt?raw"
import geminiOpenaiCompat from "../../snippets/guides/providers/gemini-openai-compat.ts?raw"
import openaiOrDeterministic from "../../snippets/guides/providers/openai-or-deterministic.ts?raw"
import withOpenrouter from "../../snippets/guides/providers/with-openrouter.ts?raw"
import { callout, code, codeBlock, command, definePage, h2, link, p, table } from "../../prose"
export const providers = definePage({
  path: "/docs/guides/providers",
  title: "How to register real model providers",
  navTitle: "Register model providers",
  group: "Guides",
  description:
    "Bind provider and model pairs to language-model layers with @batonfx/providers, combine registries, and keep a deterministic fallback for keyless environments.",
  content: [
    p(
      code("@batonfx/core"),
      " is provider-agnostic: ",
      code("ModelRegistry"),
      " maps a ",
      code("{ provider, model, registrationKey? }"),
      " selection to an Effect AI ",
      code("LanguageModel"),
      " layer and fails with a typed ",
      code("LanguageModelNotRegistered"),
      " when the selection is missing. ",
      code("@batonfx/providers"),
      " adds registration helpers over the upstream ",
      code("@effect/ai-*"),
      " packages.",
    ),
    command("Terminal", "bun add @batonfx/core @batonfx/providers"),
    h2("register-one-provider", "1. Register a provider"),
    p(
      "Each provider module ships a ",
      code("with*"),
      " layer that composes the registration and upstream client layer while requiring a host ",
      code("HttpClient"),
      ". This lets applications provide tracing, proxy, test, or platform clients. The matching explicitly named ",
      code("with*Fetch"),
      " convenience additionally provides ",
      code("FetchHttpClient.layer"),
      ". Credentials come from Effect ",
      code("Config"),
      ", never from string literals. Wrap the run in ",
      code("ModelRegistry.operate(selection, effect)"),
      ": that call looks up the registration and supplies its ",
      code("LanguageModel"),
      " layer for exactly that run.",
    ),
    codeBlock({ label: "with-openrouter.ts", source: withOpenrouter }),
    callout(
      "warning",
      "The registry is not a model",
      "A ",
      code("with*"),
      " layer provides ",
      code("ModelRegistry.ModelRegistry"),
      ", not ",
      code("Ai.LanguageModel"),
      ". Providing it where a run expects a language model fails with a missing-service error, so always pair it with ",
      code("ModelRegistry.operate"),
      ".",
    ),
    h2("combine-several-providers", "2. Combine several providers"),
    p(
      "Every ",
      code("with*"),
      " layer installs its own fresh registry under the same service tag, so ",
      code("Layer.mergeAll"),
      " keeps only one provider's registrations. Combine registries with ",
      code("ModelRegistry.layerCombined"),
      " instead; on identical identity the later layer wins.",
    ),
    codeBlock({ label: "combine-providers.ts", source: combineProviders }),
    h2("keep-ci-keyless", "3. Keep CI keyless with the deterministic registration"),
    p(
      "The deterministic registration is a local ",
      code("LanguageModel"),
      " that always answers ",
      code("deterministic response"),
      ". It runs with no credentials, which makes it the model for CI evals and local development.",
    ),
    codeBlock({
      label: "deterministic-registry.ts",
      source: deterministicRegistry,
      expectedOutput: deterministicRegistryExpected,
    }),
    p(
      code("Deterministic.withOpenAiOrDeterministicFetch"),
      " installs the deterministic fallback always and OpenAI only when its API-key config is present. Missing key data selects deterministic-only registration; invalid values and configuration-source failures remain typed failures. The selection stays data, so each environment picks its own pair.",
    ),
    codeBlock({ label: "openai-or-deterministic.ts", source: openaiOrDeterministic }),
    p(
      "For a single-agent server that needs a plain ",
      code("LanguageModel"),
      " layer rather than a registry, the deep-research example builds the same fallback at the model-layer level; see ",
      link(
        "https://github.com/In-Time-Tec/batonfx/blob/main/examples/deep-research-agent/server/src/model.ts",
        "withOpenRouterOrDeterministic in examples/deep-research-agent",
      ),
      ".",
    ),
    h2("openai-compatible-presets", "4. Pick an OpenAI-compatible preset"),
    p(
      "Presets are thin wrappers over ",
      code("OpenAiCompatible.openAiCompatible"),
      " that fix the provider name and base URL. Each has a matching ",
      code("with*"),
      " layer form requiring a host HttpClient plus explicitly named ",
      code("*Fetch"),
      " and ",
      code("with*Fetch"),
      " conveniences.",
    ),
    table(
      ["Preset", "Provider", "Base URL"],
      [
        [[code("Presets.groq")], [code("groq")], [code("https://api.groq.com/openai/v1")]],
        [[code("Presets.mistral")], [code("mistral")], [code("https://api.mistral.ai/v1")]],
        [[code("Presets.xai")], [code("xai")], [code("https://api.x.ai/v1")]],
        [[code("Presets.deepseek")], [code("deepseek")], [code("https://api.deepseek.com/v1")]],
        [
          [code("Presets.googleAiStudio")],
          [code("google")],
          [code("https://generativelanguage.googleapis.com/v1beta/openai/")],
        ],
        [[code("Presets.azureOpenAi")], [code("azure")], [code("https://{resource}.openai.azure.com/openai/v1")]],
        [[code("Presets.ollama")], [code("ollama")], [code("http://localhost:11434/v1")]],
      ],
    ),
    h2("recipe-gemini", "Recipe: Gemini via the OpenAI-compatible preset"),
    p(
      "Baton has no first-party Google helper yet because the upstream Effect AI Google provider is not compatible with the pinned beta, but Google AI Studio speaks the OpenAI protocol. Register it with the ",
      code("googleAiStudio"),
      " preset and select ",
      code('{ provider: "google", model: "gemini-2.0-flash" }'),
      ".",
    ),
    codeBlock({ label: "gemini-openai-compat.ts", source: geminiOpenaiCompat }),
    p(
      "For context windows and pricing of models reached through presets, pass overrides to the offline ",
      code("Catalog.layer"),
      ". The full export map is in ",
      link("/docs/reference/providers", "the @batonfx/providers reference"),
      ". To pin loop behavior without any provider at all, see ",
      link("/docs/guides/testing-evals", "How to test agents and run evals in CI"),
      ".",
    ),
  ],
})
