import approvalResume from "../../snippets/guides/serve-transport/approval-resume.ts?raw"
import approvalResumeExpected from "../../snippets/guides/serve-transport/approval-resume.expected.txt?raw"
import curlSession from "../../snippets/guides/serve-transport/curl-session.sh?raw"
import httpRoutes from "../../snippets/guides/serve-transport/http-routes.ts?raw"
import sessionFrames from "../../snippets/guides/serve-transport/session-frames.ts?raw"
import sessionFramesExpected from "../../snippets/guides/serve-transport/session-frames.expected.txt?raw"
import * as Prose from "../../prose"

export const serveTransport = Prose.definePage({
  path: "/docs/guides/serve-transport",
  title: "How to serve an agent over SSE and WebSocket",
  navTitle: "Serve over SSE and WebSocket",
  group: "Guides",
  description:
    "Turn Agent.stream into replayable wire frames with SessionRegistry, and expose them through Sse.respond and Ws.handle.",
  content: [
    Prose.p(
      Prose.code("@batonfx/transport"),
      " turns ",
      Prose.code("Agent.stream"),
      " into session-sequenced server frames that chat clients can replay. ",
      Prose.code("SessionRegistry"),
      " owns the sessions; ",
      Prose.code("Sse.respond"),
      " and ",
      Prose.code("Ws.handle"),
      " are thin adapters over that one seam, so a durable host can replace the registry without touching the routes.",
    ),
    Prose.command("Terminal", "bun add @batonfx/transport"),
    Prose.h2("run-sessions-in-memory", "1. Run sessions in memory"),
    Prose.p(
      Prose.code("SessionRegistry.layerMemory({ agent })"),
      " needs the four run layers plus ",
      Prose.code("Ai.Chat.Persistence"),
      " for chat history. ",
      Prose.code("open"),
      " creates a session, ",
      Prose.code("send"),
      " starts a run, and ",
      Prose.code("attach(sessionId, afterSeq?)"),
      " replays ring-buffered frames past the cursor before streaming live ones.",
    ),
    Prose.codeBlock({ label: "session-frames.ts", source: sessionFrames, expectedOutput: sessionFramesExpected }),
    Prose.bullets(
      [
        Prose.code("seq"),
        " numbers server frames, not agent events. It is 0-based and monotonic per session, and it is the same value SSE clients use as their resume cursor.",
      ],
      [
        "Terminal outcomes are data frames: ",
        Prose.code("Suspended"),
        ", ",
        Prose.code("Failed"),
        ", and exactly one ",
        Prose.code("Ended"),
        " per logical run. ",
        Prose.code("Ended"),
        " does not close the session; clients stay attached for the next ",
        Prose.code("send"),
        ".",
      ],
      [
        "A second ",
        Prose.code("send"),
        " while the session is ",
        Prose.code("Running"),
        " or ",
        Prose.code("Suspended"),
        " fails with ",
        Prose.code("SessionBusy"),
        ".",
      ],
      [
        "If the cursor predates the ring buffer floor, the attachment gets a ",
        Prose.code("Snapshot"),
        " frame carrying the persisted transcript instead of a partial replay.",
      ],
    ),
    Prose.h2("resolve-approvals-over-the-wire", "2. Resolve approvals over the wire"),
    Prose.p(
      "When a run suspends for approval, the registry publishes a ",
      Prose.code("Suspended"),
      " frame carrying the token (",
      Prose.link("/docs/learn/suspension", "Suspension as a typed error"),
      "). ",
      Prose.code("resolveApproval"),
      " re-enters the run with a one-shot approvals override for exactly the suspended call: ",
      Prose.code("Approved"),
      " executes the tool, ",
      Prose.code("Denied"),
      " feeds the model the same failed tool result as a core denial.",
    ),
    Prose.codeBlock({ label: "approval-resume.ts", source: approvalResume, expectedOutput: approvalResumeExpected }),
    Prose.p(
      "Over WebSocket the same operation is the ",
      Prose.code("ResolveApproval"),
      " client frame; ",
      Prose.code("Ws.handle"),
      " dispatches ",
      Prose.code("Attach"),
      ", ",
      Prose.code("SendMessage"),
      ", ",
      Prose.code("ResolveApproval"),
      ", and ",
      Prose.code("Cancel"),
      " to the matching registry methods.",
    ),
    Prose.h2("serve-the-routes", "3. Serve the routes"),
    Prose.p(
      "SSE is downstream-only, so hosts pair the event stream with ordinary command routes. This router mirrors ",
      Prose.link(
        "https://github.com/In-Time-Tec/batonfx/blob/main/examples/deep-research-agent/server/src/index.ts",
        "examples/deep-research-agent",
      ),
      ": WebSocket at ",
      Prose.code("/ws"),
      ", SSE at ",
      Prose.code("/sessions/:id/events"),
      ", and POST commands beside them.",
    ),
    Prose.codeBlock({ label: "http-routes.ts", source: httpRoutes }),
    Prose.p(
      "Launch ",
      Prose.code("serverLayer"),
      " with your platform's HTTP server. The example uses ",
      Prose.code("Layer.launch(serverLayer)"),
      " over ",
      Prose.code("BunHttpServer.layer({ port: 4000 })"),
      " from ",
      Prose.code("@effect/platform-bun"),
      ". Then drive a session from the terminal:",
    ),
    Prose.codeBlock({ label: "Terminal", language: "bash", source: curlSession }),
    Prose.h2("cursors-and-backpressure", "4. Cursors and backpressure"),
    Prose.bullets(
      [
        Prose.code("Sse.respond"),
        " reads the resume cursor from ",
        Prose.code("Last-Event-ID"),
        ", falling back to ",
        Prose.code("?after_seq="),
        "; each SSE event's ",
        Prose.code("id"),
        " is the frame ",
        Prose.code("seq"),
        ", so browser reconnects resume for free.",
      ],
      [
        "Each subscriber gets a bounded queue. A lagging subscriber fails with ",
        Prose.code("SubscriberLagged"),
        " (over WebSocket the socket closes with code ",
        Prose.code("4000"),
        ") while the run and other subscribers continue.",
      ],
      [
        Prose.code("stripTranscripts"),
        " removes transcripts from ",
        Prose.code("TurnCompleted"),
        " and ",
        Prose.code("Completed"),
        " frames; clients recover full history through ",
        Prose.code("Snapshot"),
        ".",
      ],
      [
        Prose.code("layerMemory"),
        " evicts idle sessions after ",
        Prose.code("idleTimeout"),
        " (default 15 minutes); persisted chat history survives as long as the provided persistence does.",
      ],
    ),
    Prose.p(
      "The frame-by-frame wire contract is in ",
      Prose.link("/docs/reference/transport", "the @batonfx/transport reference"),
      ". To consume these frames in a browser app, continue with ",
      Prose.link("/docs/guides/foldkit-chat", "How to build a chat UI with FoldKit"),
      ", or build the whole stack in ",
      Prose.link("/docs/start/research-agent", "the research-agent tutorial"),
      ".",
    ),
  ],
})
