import approvalResume from "../../snippets/guides/serve-transport/approval-resume.ts?raw"
import approvalResumeExpected from "../../snippets/guides/serve-transport/approval-resume.expected.txt?raw"
import curlSession from "../../snippets/guides/serve-transport/curl-session.sh?raw"
import httpRoutes from "../../snippets/guides/serve-transport/http-routes.ts?raw"
import sessionFrames from "../../snippets/guides/serve-transport/session-frames.ts?raw"
import sessionFramesExpected from "../../snippets/guides/serve-transport/session-frames.expected.txt?raw"
import { bullets, code, codeBlock, command, definePage, h2, link, p } from "../../prose"
export const serveTransport = definePage({
  path: "/docs/guides/serve-transport",
  title: "How to serve an agent over SSE and WebSocket",
  navTitle: "Serve over SSE and WebSocket",
  group: "Guides",
  description:
    "Turn Agent.stream into replayable wire frames with SessionRegistry, and expose them through Sse.respond and Ws.handle.",
  content: [
    p(
      code("@batonfx/transport"),
      " turns ",
      code("Agent.stream"),
      " into session-sequenced server frames that chat clients can replay. ",
      code("SessionRegistry"),
      " owns the sessions; ",
      code("Sse.respond"),
      " and ",
      code("Ws.handle"),
      " are thin adapters over that one seam, so a durable host can replace the registry without touching the routes.",
    ),
    command("Terminal", "bun add @batonfx/transport"),
    h2("run-sessions-in-memory", "1. Run sessions in memory"),
    p(
      code("SessionRegistry.layerMemory({ agent })"),
      " needs the four run layers plus ",
      code("Ai.Chat.Persistence"),
      " for chat history. ",
      code("open"),
      " creates a session, ",
      code("send"),
      " starts a run, and ",
      code("attach(sessionId, afterSeq?)"),
      " replays ring-buffered frames past the cursor before streaming live ones.",
    ),
    codeBlock({ label: "session-frames.ts", source: sessionFrames, expectedOutput: sessionFramesExpected }),
    bullets(
      [
        code("seq"),
        " numbers server frames, not agent events. It is 0-based and monotonic per session, and it is the same value SSE clients use as their resume cursor.",
      ],
      [
        "Terminal outcomes are data frames: ",
        code("Suspended"),
        ", ",
        code("Failed"),
        ", and exactly one ",
        code("Ended"),
        " per logical run. ",
        code("Ended"),
        " does not close the session; clients stay attached for the next ",
        code("send"),
        ".",
      ],
      [
        "A second ",
        code("send"),
        " while the session is ",
        code("Running"),
        " or ",
        code("Suspended"),
        " fails with ",
        code("SessionBusy"),
        " by default. Configure ",
        code('onConcurrentMessage: "enqueue"'),
        " to accept it into the bounded per-session FIFO queue; a full queue fails with ",
        code("SessionQueueFull"),
        ". Approval resolution always takes priority over queued messages.",
      ],
      [
        "If the cursor predates the ring buffer floor, the attachment gets a ",
        code("Snapshot"),
        " frame carrying the persisted transcript instead of a partial replay.",
      ],
    ),
    h2("resolve-approvals-over-the-wire", "2. Resolve approvals over the wire"),
    p(
      "When a run suspends for approval, the registry publishes a ",
      code("Suspended"),
      " frame carrying the token (",
      link("/docs/learn/suspension", "Suspension as a typed error"),
      "). ",
      code("resolveApproval"),
      " re-enters the run with a one-shot approvals override for exactly the suspended call: ",
      code("Approved"),
      " executes the tool, ",
      code("Denied"),
      " feeds the model the same failed tool result as a core denial.",
    ),
    codeBlock({ label: "approval-resume.ts", source: approvalResume, expectedOutput: approvalResumeExpected }),
    p(
      "Over WebSocket the same operation is the ",
      code("ResolveApproval"),
      " client frame; ",
      code("Ws.handle"),
      " dispatches ",
      code("Attach"),
      ", ",
      code("SendMessage"),
      ", ",
      code("ResolveApproval"),
      ", and ",
      code("Cancel"),
      " to the matching registry methods.",
    ),
    h2("serve-the-routes", "3. Serve the routes"),
    p(
      "SSE is downstream-only, so hosts pair the event stream with ordinary command routes. This router mirrors ",
      link(
        "https://github.com/In-Time-Tec/batonfx/blob/main/examples/deep-research-agent/server/src/index.ts",
        "examples/deep-research-agent",
      ),
      ": WebSocket at ",
      code("/ws"),
      ", SSE at ",
      code("/sessions/:id/events"),
      ", and POST commands beside them.",
    ),
    codeBlock({ label: "http-routes.ts", source: httpRoutes }),
    p(
      "Launch ",
      code("serverLayer"),
      " with your platform's HTTP server. The example uses ",
      code("Layer.launch(serverLayer)"),
      " over ",
      code("BunHttpServer.layer({ port: 4000 })"),
      " from ",
      code("@effect/platform-bun"),
      ". Then drive a session from the terminal:",
    ),
    codeBlock({ label: "Terminal", language: "bash", source: curlSession }),
    h2("cursors-and-backpressure", "4. Cursors and backpressure"),
    bullets(
      [
        code("Sse.respond"),
        " reads the resume cursor from ",
        code("Last-Event-ID"),
        ", falling back to ",
        code("?after_seq="),
        "; each SSE event's ",
        code("id"),
        " is the frame ",
        code("seq"),
        ", so browser reconnects resume for free.",
      ],
      [
        "Each subscriber gets a bounded queue. A lagging subscriber fails with ",
        code("SubscriberLagged"),
        " (over WebSocket the socket closes with code ",
        code("4000"),
        ") while the run and other subscribers continue.",
      ],
      [
        code("stripTranscripts"),
        " removes transcripts from ",
        code("TurnCompleted"),
        " and ",
        code("Completed"),
        " frames; clients recover full history through ",
        code("Snapshot"),
        ".",
      ],
      [
        code("layerMemory"),
        " evicts idle sessions after ",
        code("idleTimeout"),
        " (default 15 minutes); persisted chat history survives as long as the provided persistence does.",
      ],
      [
        code("pendingMessageCapacity"),
        " bounds each opt-in message queue, while ",
        code("maxConcurrentRuns"),
        " optionally caps active runs across the registry. Accepted queued messages keep their session from being evicted.",
      ],
    ),
    p(
      "The frame-by-frame wire contract is in ",
      link("/docs/reference/transport", "the @batonfx/transport reference"),
      ". To consume these frames in a browser app, continue with ",
      link("/docs/guides/foldkit-chat", "How to build a chat UI with FoldKit"),
      ", or build the whole stack in ",
      link("/docs/start/research-agent", "the research-agent tutorial"),
      ".",
    ),
  ],
})
