import activateSkill from "../../snippets/guides/skills/activate-skill.ts?raw"
import activateSkillExpected from "../../snippets/guides/skills/activate-skill.expected.txt?raw"
import skillLoader from "../../snippets/guides/skills/skill-loader.ts?raw"
import skillMd from "../../snippets/guides/skills/SKILL.md?raw"
import { bullets, callout, code, codeBlock, definePage, h2, link, p } from "../../prose"
export const skills = definePage({
  path: "/docs/guides/skills",
  title: "How to add skills",
  navTitle: "Skills",
  group: "Guides",
  description:
    "Provide a SkillSource, let the loop advertise listings and the activate_skill tool, and load SKILL.md directories from the filesystem.",
  content: [
    p(
      "A skill is reusable instruction material the agent loads on demand: startup context carries only one-line listings, and the model calls the built-in ",
      code("activate_skill"),
      " tool to pull in a skill's full body when the task matches. Provide a ",
      code("SkillSource"),
      " layer and the loop handles the rest: listing injection, the activation tool, and lazy body loading.",
    ),
    h2("write-a-skill", "1. Write a SKILL.md"),
    p(
      "Skills follow the agentskills ",
      code("SKILL.md"),
      " format: a directory holding a ",
      code("SKILL.md"),
      " with YAML-style frontmatter and a Markdown body. Only ",
      code("description"),
      " is required; ",
      code("name"),
      " defaults to the directory name:",
    ),
    codeBlock({ label: "release-notes/SKILL.md", language: "markdown", source: skillMd }),
    h2("provide-a-source", "2. Provide a source and watch activation"),
    p(
      "For skills defined in code, build ",
      code("SkillSource.Skill"),
      " values and provide ",
      code("SkillSource.fromSkills"),
      ". The loop appends the listings to the system message, advertises ",
      code("activate_skill"),
      ", handles the activation call itself (it never reaches your executor), and returns ",
      code("{ name, body, allowedTools }"),
      " to the model as an ordinary tool result:",
    ),
    codeBlock({ label: "activate-skill.ts", source: activateSkill, expectedOutput: activateSkillExpected }),
    callout(
      "info",
      "Bodies are lazy",
      code("Skill.body"),
      " is an Effect evaluated only on activation, and each body loads once per run. Non-activated skills cost one listing line each.",
    ),
    h2("load-from-the-filesystem", "3. Load skill directories from the filesystem"),
    p(
      code("SkillLoader.layer"),
      " from ",
      code("@batonfx/skills"),
      " discovers ",
      code("SKILL.md"),
      " files under your roots (defaults: ",
      code(".agents/skills"),
      ", ",
      code(".claude/skills"),
      ", ",
      code(".pi/skills"),
      "), namespaces nested directories as ",
      code("parent:child"),
      ", and reads only frontmatter up front:",
    ),
    codeBlock({ label: "skill-loader.ts", source: skillLoader }),
    p(
      "Provide ",
      code("FileSystem"),
      " and ",
      code("Path"),
      " from your platform runtime. Later roots win on name collisions.",
    ),
    h2("mind-the-budget", "4. Mind the listing budget"),
    p(
      "The loop selects listings under a fixed 2,048-token budget with ",
      code("SkillSource.selectListings"),
      ": skills marked ",
      code("disableModelInvocation"),
      " are excluded, and least-recently-used listings drop first when over budget. Descriptions are capped at ",
      code("DESCRIPTION_CAP"),
      " (1,536 characters), so front-load the sentence that tells the model when to activate.",
    ),
    h2("next-steps", "Next steps"),
    bullets(
      [
        "Compose skills with the rest of the system message: ",
        link("/docs/guides/instructions", "How to compose instructions and context sources"),
        ".",
      ],
      [
        "Remember facts across runs instead of re-teaching them: ",
        link("/docs/guides/memory", "How to add memory"),
        ".",
      ],
    ),
  ],
})
